<?php
    date_default_timezone_set('Europe/London');
$return = $this->script('add-expense-process');
use Gc\User\Finance\Expense\CategoryCollection as CategoryCollection;
$categoryCollection = new CategoryCollection();
use GcFrontend\Controller\EndecryptController as Ecryption;
use GcFrontend\Helper\FinanceHelper as FinanceHelper;
$financeHelper = new FinanceHelper();
$encypt = new Ecryption();

$edit_id = null;
if (isset($_GET['e']) && $_GET['e'] != '') {
    $edit_id = $encypt->decryptIt($_GET['e']);
    $expenceedit =  $financeHelper->getOnlyFinanceexpence($edit_id);
}
$regdate = date_format(date_create($financeHelper->getCreatedDate($_SESSION['user_id'])), 'd/m/Y') ;

?>
<section id="breadcrum" class="breadcrum">
    <div class="breadcrum-sitemap">
        <div class="container">
            <div class="row">
                <ul>
                    <li><a href="<?php echo $this->serverUrl();?>">Home</a></li>
                    <li><a href="<?php echo $this->serverUrl();?>/user-profile">My Dashboard</a></li>
                    <li><a href="<?php echo $this->serverUrl();?>/finance-detail">Finance</a></li>
                    <li><a href="#"><?php /* echo $title ;*/ ?> <?php echo $edit_id != null ? 'Edit' : 'Add'; ?> Expense</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="breadcrum-title">
        <div class="container">
            <div class="row">
                <div class="set-icon registration-icon">
                    <i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
                </div>
                <div class="set-title">
                    <h3> <?php // echo $title ; ?> <?php echo $edit_id != null ? 'Edit' : 'Add'; ?> Expense </h3>
                </div>
            </div>

        </div>
    </div>
</section>
<div id="primary-content" class="main-content about">
<div class="container">
<div class="row">
<div class="contents white-bg add-expense">

<!---->
<section class="add_item text-left">

<div class="col-md-12 pad0">
    <div class="text-center finance-page-head"><?php echo $edit_id != null ? 'Edit' : 'Add'; ?> expense</div>
</div>
<div class="col-md-12 pad0"><?php echo $this->partial('flash-messages'); ?></div>

<?php if($edit_id != null && !empty($expenceedit)){ ?>


    <div class="col-md-12 pad0">
        <!-- form start -->
        <form role="form"  id="expense-form" action="<?php echo $this->escapeHtml($this->document('add-expense')->getUrl()); ?>" method="POST" onsubmit="validexpenseform()" class="add_item_form form-inline">
            <input type="hidden" name="edit_id" value="<?php echo @$expenceedit['id'] ? $expenceedit['id'] : '' ?>">
           
            
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Job Type</label></div>
                    <div class="col-md-7">
                        <select  class="form-control">
                            <option value="">Select</option>
                            <option value="1" <?php echo $expenceedit['job_type'] == '1' ? 'selected' : '' ;?>>Website</option>
                            <option value="2" <?php echo $expenceedit['job_type'] == '2' ? 'selected' : '' ;?>>Private</option>
                            <option value="3" <?php echo $expenceedit['job_type'] == '3' ? 'selected' : '' ;?>>Other</option>
                        </select>
                    </div>
                </div>
            </div>
            
            
            
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Job No.</label></div>
                    <div class="col-md-7"><input type="number"  value="<?php echo @$expenceedit['job_id'] ? $expenceedit['job_id'] : '' ?>" placeholder="Job No" class="form-control" disabled></div>
                </div>
            </div>

            <div class="col-md-12 no_field">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Date <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                            <input type="text" name="ex_job_date" id="ex_job_date" value="<?php echo $expenceedit['job_date'] ? date('d/m/Y',strtotime($expenceedit['job_date'])) : '' ;?>" placeholder="Date" class="form-control readonly" required  autocomplete="off">
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-12 no_field">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Expense cost <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <?php echo $this->config()->get('site_currency') ?>
                            </span>
                            <input type="text" name="ex_job_cost" id="ex_job_cost" value="<?php echo @$expenceedit['cost'] ? $expenceedit['cost'] : '' ?>" placeholder="Expense cost" class="form-control" required>
                            <div id="ex_job_cost_err"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Description</label></div>
                    <div class="col-md-7">
                        <textarea type="text" name="ex_job_description" id="ex_job_description" placeholder="Description" class="form-control"><?php echo @$expenceedit['description'] ? $expenceedit['description'] : '' ?></textarea>
                    </div>
                </div>
            </div>


            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Category <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <select name="ex_category" id="ex_category" class="form-control" required>
                            <option value="">Select Category</option>
                            <?php
                            $catCollections = $categoryCollection->getExpenseCategory();
                            foreach ($catCollections as $key => $catObj) {
                                if($expenceedit['expense_type_id'] == $catObj->getId()){ $select = 'selected'; }else{ $select = ''; }
                                echo '<option value="'.$catObj->getId().'" '.$select.' >'.$catObj->getExpense().'</option>';
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"></div>
                    <div class="col-md-7"><div class="checkbox">

                            <label for="ex_bank">
                                <input name="ex_bank" type="checkbox" id="ex_bank" <?php echo $expenceedit['bank'] == '1' ? 'checked' : '' ;?>>
                                Please click if the cash has already left the bank.
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12 new_bank_date no_field" <?php echo $expenceedit['bank'] == '1' ? 'style="display:block"' : 'style="display:none"' ;?> id="exbank_date" >
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Bank Date <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <div class="input-group date form_date" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                            <input type="text" class="form-control readonly" name="ex_bank_date" placeholder="Bank Date" value="<?php echo $expenceedit['bank_date'] ? date('d/m/Y',strtotime($expenceedit['bank_date'])) : '' ;?>" id="ex_bank_date" <?php echo $expenceedit['bank'] == '1' ? 'required' : '' ;?>  autocomplete="off">

                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-12">
                <div class="form-group text-center">
                    <button type="submit" name="expense_submit" value="expense_update" class="read-common-btn grad_btn">Update</button>
                </div>
            </div>
        </form>
    </div>







<?php }elseif($edit_id != null && empty($expenceedit)){ ?> <?php }else { ?>




    <div class="col-md-12 pad0">
        <!-- form start -->
        <form role="form"  id="expense-form" action="<?php echo $this->escapeHtml($this->document('add-expense')->getUrl()); ?>" method="POST" onsubmit="validexpenseform()" class="add_item_form form-inline">


            <div class="col-md-12">
                <input type="hidden" name="trans_type" value="2">
            </div>
            
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Job Type <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <select name="ex_job_type" id="ex_job_type" class="form-control" required="required">
                            <option value="">Select job type</option>
                            <option value="1">Website</option>
                            <option value="2">Private</option>
                            <option value="3">Other</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Job No</label></div>
                    <div class="col-md-7"><input type="number" name="ex_job_id" id="ex_job_id" placeholder="Please enter job no." class="form-control"></div>
                </div>
            </div>

            <div class="col-md-12 no_field">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Date <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                            <input type="text" name="ex_job_date" id="ex_job_date" placeholder="dd/mm/yyyy" class="form-control readonly" maxlength="10" required autocomplete="off">
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-12 no_field">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Expense cost <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <?php echo $this->config()->get('site_currency') ?>
                            </span>
                            <input type="text" name="ex_job_cost" id="ex_job_cost" placeholder="Please Enter Amount" class="form-control" required>
                            <div id="ex_job_cost_err"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Description</label></div>
                    <div class="col-md-7">
                        <textarea type="text" name="ex_job_description" id="ex_job_description" placeholder="Enter description of expense" class="form-control"></textarea>
                    </div>
                </div>
            </div>


            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Category <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <select name="ex_category" id="ex_category" class="form-control" required>
                            <option value="">Select category</option>
                            <?php
                            $catCollections = $categoryCollection->getExpenseCategory();
                            foreach ($catCollections as $key => $catObj) {
                                echo '<option value="'.$catObj->getId().'">'.$catObj->getExpense().'</option>';
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-3"></div>
                    <div class="col-md-7"><div class="checkbox">

                            <label for="ex_bank">
                                <input name="ex_bank" type="checkbox" id="ex_bank">
                                Please click if the cash has already left the bank.
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12 new_bank_date no_field" style="display:none" id="exbank_date" >
                <div class="form-group">
                    <div class="col-md-3"><label for="exampleInputPassword1">Bank Date <i class="fa fa-asterisk required-stars" aria-hidden="true" ></i></label></div>
                    <div class="col-md-7">
                        <div class="input-group date form_date" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd" autocomplete="off">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                            <input type="text" class="form-control readonly" name="ex_bank_date" placeholder="Bank Date" id="ex_bank_date" maxlength="10" autocomplete="off">

                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-12">
                <div class="form-group text-center">
                    <button type="submit" name="expense_submit" id="expense_submit" value="expense_submit" class="read-common-btn grad_btn">Submit</button>
      <button type="button"  id="expense_submit_loding"  class="read-common-btn grad_btn disabled" style="display: none">Loading...</button>
             
                    <!--<button type="button" class="read-common-btn grad_btn">Review</button>-->
                </div>
            </div>
        </form>
    </div>






<?php } ?>



</section>
<!---->
</div>
</div>
</div>
</div>
<style type="text/css">
    div#expence_form {
        text-align: left;
    }

    .checkbox.form-group.bank  input#ex_bank {
        margin-left: 0px;
    }
</style>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script type="text/javascript">


    $("#expense-form").submit(function(){
      $('#expense_submit').hide();
      $('#expense_submit_loding').show();

    });


    $(document).ready(function() {
        $('input#ex_bank_date').datepicker({
            maxDate: '0',
            dateFormat: 'dd/mm/yy'
        });
        $('input#ex_job_date').datepicker({
            maxDate: '0',
            //minDate: '<?php echo $regdate ; ?>',
            dateFormat: 'dd/mm/yy'
        });
    });
   
   /* $('input#ex_job_cost').keypress(function(event) {
        if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57)) {
            event.preventDefault();
        }
    });*/
    
    
      $("input#ex_job_cost").keyup(function() {
        var ex_job_cost = $("#ex_job_cost").val();
        if (isNaN(ex_job_cost)){ $("#ex_job_cost").val('');  }
    });
    
    
    
    function validexpenseform() {
        var exCost = $('input#ex_job_cost').val();
        var exCat = $('select#ex_category').val();
        if (exCost == '' || exCost == null) {
            $('#ex_job_cost_err').html('Please enter cost.');
            return false;
        }else{
            $('#ex_job_cost_err').html('');
        }
    }
    $('input#ex_bank').change(function(){
        var c = this.checked ? '1' : '0';
        if(c==1){
        $("input#ex_bank_date").prop('required', true);
            $('div#ex_bank_date_div').show(500);
        }else{
        $("input#ex_bank_date").prop('required', false);
            $('div#ex_bank_date_div').hide(300);
            $('input#ex_bank_date').val('');
        }
    });
    $("#ex_bank").click(function(){
        var job_type = $('#ex_bank:checked').val();
        var c = job_type ? '1' : 0 ;
        if(c == '1'){
            $('#exbank_date').show(1000);
        }else{
            $('#exbank_date').hide(1000);
            $('#ex_bank_date').val('');
        }
    });
    
    
       $('input#ex_job_date ,input#ex_bank_date').keydown(function (e) {
        var key = e.charCode || e.keyCode || 0;
        $goc = $(this);

        // Auto-format- do not expose the mask as the user begins to type
        if (key !== 8 && key !== 9) {
            if ($goc.val().length === 2) {
                $goc.val($goc.val() + '/');
            }
            if ($goc.val().length === 5) {
                $goc.val($goc.val() + '/');
            }
        }

        // Allow numeric (and tab, backspace, delete) keys only
        return (key == 8 || 
                key == 9 ||
                key == 46 ||
                (key >= 48 && key <= 57) ||
                (key >= 96 && key <= 105)); 
    })
    
    
    
</script>