<section id="breadcrum" class="breadcrum">
    <div class="breadcrum-sitemap">
         <div class="container">
            <div class="row">
                <ul>
                    <?php echo $this->partial('blog-categories'); ?>
                     <li><a href="javascript:void(0);"><?php echo $this->escapeHtml($this->title); ?></a></li>
                </ul>
                
             </div>
         </div>
     </div>
     <div class="breadcrum-title">
        <div class="container">
            <div class="row">
                <div class="set-icon registration-icon" style="   padding: 3px 16px 0px;">
                    <i class="fa fa-rss" aria-hidden="true"></i>
                </div>
                <div class="set-title">
                    <h3><?php echo $this->escapeHtml($this->title); ?></h3>
                </div>
            </div>
        </div>
     </div>
</section>
<div class="subpage" id="main-wrapper">
    <div class="container">
        <div class="row">
            
            <div class="9u skel-cell-mainContent">
                <?php
                $return = $this->script('blog-comment');
                if ($return === true) {
                    return;
                }
                $img=""; 
                $comment_table = new \Blog\Model\Comment();
                $comments = $comment_table->getList($this->currentDocument()->getId());
                $nb_comments = count($comments);
                ?>
               <?php $img2 = unserialize($this->image);$img=$this->image['original']['value']; ?>
                <?php echo $this->partial('flash-messages'); ?>
                    <article class="first post-content">                    
                        <div class="col-md-12 margin-top">
                            <?php if($img) {?>
                      <div class="post-feature-img margin-top"><img src="<?php echo $this->cdn($img);?>" alt="<?php echo $this->escapeHtml($this->title); ?>" width="200px">
                                </div>
                            <?php }?>    
                            <h2 class="title"><?php echo $this->escapeHtml($this->title); ?></h2>
                            <?php $parent = $this->currentDocument()->getParent(); ?>
                            <p class="sub">
                                <a href="<?php echo $this->escapeHtml($parent->getUrl()); ?>"><i class="fa fa-rss" aria-hidden="true"></i> <?php echo $this->escapeHtml($parent->getName()); ?></a> &nbsp; <i class="glyphicon glyphicon-calendar" aria-hidden="true"></i><?php echo $this->escapeHtml(date('d/m/Y', strtotime($this->published_at))); ?>
                                <?php if(!empty($nb_comments)): ?>
                                    &bull; <a href="#comments_list">
                                        <?php if($nb_comments == 1): ?>
                                            1 Comment
                                        <?php else: ?>
                                            <?php echo $nb_comments; ?> Comments
                                        <?php endif; ?>
                                    </a>
                                <?php endif; ?>
                            </p>
                            <div class="hr dotted clearfix">&nbsp;</div>
                            <?php echo $this->content; ?>
                            <p class="clearfix">
                                <a href="<?php echo $this->escapeHtml($this->document('blog')->getUrl()); ?>" class="button float">&lt;&lt; Back to Blog</a>
                                <!--<a href="#comment_form" class="button float right">Discuss this post</a>-->
                            </p>
                        </div>
                    </article>
                <div class="hr clearfix">&nbsp;</div>

                <?php //echo $this->modulePlugin('Blog', 'comment-list'); ?>

                <div class="hr clearfix">&nbsp;</div>

                <?php //echo $this->modulePlugin('Blog', 'comment-form'); ?>
            </div>
        </div>
    </div>
</div>
