<section id="breadcrum" class="breadcrum">
    <div class="breadcrum-sitemap">
         <div class="container">
            <div class="row">
                <ul>
                    <?php echo $this->partial('blog-categories'); ?>
                     <li><a href="javascript:void(0);"><?php echo $this->escapeHtml($this->title); ?></a></li>
                </ul>
                
             </div>
         </div>
     </div>
     <div class="breadcrum-title">
        <div class="container">
            <div class="row">
                <div class="set-icon registration-icon" style="   padding: 3px 16px 0px;">
                    <i class="fa fa-rss" aria-hidden="true"></i>
                </div>
                <div class="set-title">
                    <h3><?php echo $this->escapeHtml($this->title); ?></h3>
                </div>
            </div>
        </div>
     </div>
</section>
<div class="subpage" id="main-wrapper">
    <div class="container">
        <div class="row">
            
            <div class="9u skel-cell-mainContent">
               
                    <article class="first post-content">                    
                        <div class="col-md-12 margin-top">
                          
                      <div class="post-feature-img margin-top"><img src="" alt="" width="200px">
                                </div>
                              
                            <h2 class="title"></h2>                            
                            <p class="sub">
                                <a href=""><i class="fa fa-rss" aria-hidden="true"></i></a> &nbsp; <i class="glyphicon glyphicon-calendar" aria-hidden="true"></i>
                              
                                    &bull; <a href="#comments_list">                                     
                                            1 Comment
                                    </a>
                            </p>
                            <div class="hr dotted clearfix">&nbsp;</div>
                            <?php echo $this->content; ?>
                            <p class="clearfix">
                                <a href="" class="button float">&lt;&lt; Back to Blog </a>
                                <!--<a href="#comment_form" class="button float right">Discuss this post</a>-->
                            </p>
                        </div>
                    </article>
                <div class="hr clearfix">&nbsp;</div>

                <div class="hr clearfix">&nbsp;</div>

            </div>
        </div>
    </div>
</div>