<section id="breadcrum" class="breadcrum">
    <div class="breadcrum-sitemap">
         <div class="container">
            <div class="row">
                <ul>          
                    <li><a href="<?php echo $this->serverUrl();?>">Home</a></li>
		    <li><a href="javascript:void(0);"><?php echo $this->escapeHtml($this->translate($this->title)); ?></a></li>
                </ul>
             </div>
         </div>
     </div>
</section>
<div id="primary-content" class="main-content about">
    <div class="container">
        <div class="row">
            <div class="contents white-bg">
                <div class="welcome-heading">
                    <h1><span><?php echo $this->escapeHtml($this->translate($this->title)); ?></span></h1>
                    <hr class="shadow-line">
                </div>
                <section>               
                    <div class="mission-vision">
						    <?php if(isset($_GET['view']) && $_GET['view']==1){?>
                            <div class="col-md-4">
                            <img src="<?php echo $this->cdn($this->image['original']['value']); ?>" alt="<?php echo $this->title ?>" />
                            </div>
                            <div class="col-md-8"> 
                                <div class="full-content">
                                    <?php echo $this->translate($this->content); ?> 
                                </div>  
                            </div>
                            <?php }else{?>
                            <div class="col-md-2">
                                 <div class="feature-img"> 
                                     <figure>                    
                                      <img src="<?php echo $this->cdn($this->image['original']['value']); ?>" alt="<?php echo $this->title ?>" />
                                     </figure> 
                                 </div>
                             </div>
                             <div class="col-md-10"> 
                                <div class="full-content">
                                    <?php echo $this->translate($this->content); ?> 
                                </div>  
                            </div>
                            <?php }?> 
                    </div>
                </section>      
            </div>   
        </div>
    </div>
</div>