<?php
    use GcFrontend\Controller\DbController as DbController;
		
			
	use Gc\User\Role\Model;
	use Gc\User\Professional\Model as Model2;
	use Gc\User\Package\Model as Model3;
	use Gc\Db\AbstractTable;
	use Zend\Db\Sql\Sql;
	use Zend\Db\TableGateway\TableGateway;
	use Zend\Db\Sql\Where;
    $dbConfig = new DbController();
    $adapter = $dbConfig->locumkitDbConfig();	
    $sql = new Sql($adapter);
    $update = $sql->update();
    $select = $sql->select();
	$number_1 = mt_rand(1, 9);
	$number_2 = mt_rand(1, 9);
	$answer = substr(sha1($number_1+$number_2),5,10);
	if(!empty($_SESSION['user_id']) && $_SESSION['user_id']!=''){
		$uid = $_SESSION['user_id'];
	}else{
		?>
		<script type="text/javascript">
			window.location = "<?php echo $this->serverUrl();?>/404";
		</script>
		<?php
	}
    //echo $this->getRequest()->getServer();

	$sqlString_data="select u.password from user u where u.id='$uid'";	
    $results_get = $adapter->query($sqlString_data, $adapter::QUERY_MODE_EXECUTE);
	$result_data = $results_get->current();
	
?>
<section id="breadcrum" class="breadcrum">
    <div class="breadcrum-sitemap">
         <div class="container">
            <div class="row">
                <ul>          
                    <li><a href="<?php echo $this->serverUrl();?>">Home</a></li>
		    <li><a href="<?php echo $this->serverUrl().'/user-profile';?>">My Dashboard</a></li>
		    <li><a href="javascript:void(0)">Change Password</a></li>
		</ul>
             </div>
         </div>
     </div>
     <div class="breadcrum-title">
        <div class="container">
            <div class="row">
                <div class="set-icon registration-icon">
                    <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
                </div>
                <div class="set-title">
                    <h3>Change Password</h3>
                </div>
            </div>
        </div>
     </div>
</section>
<div id="primary-content" class="main-content profiles">
    <div class="container">
        <div class="row">
            <div class="contents gray-gradient">
                <div class="welcome-heading">
                    <h1>Change <span>Password</span></h1>
                    <hr class="shadow-line">
                </div>
                <div class="change-password">
        			<!-- Check password and update -->
        			<div class="notification_msg">
        				<?php 
	        				if (isset($_POST['Update_Password']) && $_POST['Update_Password'] != '') {
								$old_pass = $_POST['old-password'];
								$new_pass = $_POST['new-password'];
								$re_new_pass = $_POST['re-new-password'];
								$currentPassword = sha1($old_pass);
								if ($currentPassword != $result_data['password']) {
									echo "<h3 class='error'> Its look like you enter wrong old password, please check and retry. </h3>";
								}elseif(!empty($new_pass)){
									$pass = sha1($new_pass);
									$sqlUpdatePass="UPDATE user SET password = '$pass' where id='$uid'";	
    								$passUpdate = $adapter->query($sqlUpdatePass, $adapter::QUERY_MODE_EXECUTE);
    								echo "<h3 class='success'> Password change successfully. </h3>";
								}else{
									echo "<h3 class='error'> Some error is occure please contact to site administrator . </h3>";
								}
								
							}

	        			?>
        			</div>
        			
	            	<form method="POST" action="/change-password" id="change-password" onsubmit="return submit_change_pass_form(<?php echo $uid; ?>)">
	            		<div class="row">
	            			<div class="col-md-4 col-sm-4 col-xs-12">
	            				<label>Enter old password</label>
	            			</div>
	            			<div class="col-md-8 col-sm-8 col-xs-12">
	            				<input type="password" name="old-password" id="old-pass" value="" placeholder="Please enter your old password" class="form-control margin-bottom">	
	            				<div class="error_old_pass"></div>
	            			</div>
	            		</div>
	            		<div class="row">
	            			<div class="col-md-4 col-sm-4 col-xs-12">
	            				<label>Enter new password</label>
	            			</div>
	            			<div class="col-md-8 col-sm-8 col-xs-12">
	            				<input type="password" name="new-password" id="new-pass" value="" placeholder="Please enter new password" class="form-control margin-bottom">	
	            				<div class="error_new_pass"></div>
	            			</div>
	            		</div>
	            		<div class="row">
	            			<div class="col-md-4 col-sm-4 col-xs-12">
	            				<label>Re enter new password</label>
	            			</div>
	            			<div class="col-md-8 col-sm-8 col-xs-12">
	            				<input type="password" name="re-new-password" id="re-new-pass" value="" placeholder="Please re-enter the new password"  class="form-control margin-bottom">	
	            				<div class="error_re_new_pass"></div>
	            			</div>
	            		</div>
	            		<div class="row">
	            			<div class="col-sm-offset-4 col-md-offset-5 col-md-6"> 
	            				<input type="submit" name="Update_Password" value="Update Password" class="update-pass-btn btn btn-small btn-warning" >
	            				<!-- <a class="supdate-pass-btn btn btn-small btn-warning" <i class="glyphicon glyphicon-edit"></i> Update Password</a> -->
	            			</div>
	            		</div>
	            		
	            	</form>
	            </div>
            </div>
            
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
<script type="text/javascript">
	function submit_change_pass_form($uid) {
		var user_id = $uid;
		var old_pass = $("#old-pass").val();
		var new_pass = $("#new-pass").val();
		var re_new_pass = $("#re-new-pass").val();
		if(old_pass=='' || old_pass == null){
			$('.error_old_pass').html('Please enter old password.');
			$("#old-pass").focus();
			return false;
		}else if(new_pass==''  || new_pass == null){
			$('.error_old_pass').html('');
	   		$('.error_new_pass').html('Please enter new password.');
			$("#new-pass").focus();
			return false;
			
	   	}else if(re_new_pass=='' || re_new_pass == null){
		   $('.error_new_pass').html('');
		   $('.error_re_new_pass').html('Please enter confirm password.');
		   $("#re-new-pass").focus();
		   return false;
		   
	   	}else if (new_pass != re_new_pass) {
	   		$('.error_re_new_pass').html('');
			$('.error_re_new_pass').html('Password not match.');
	  		$("#re-new-pass").focus();
			return false;
		}else{
			$('.error_re_new_pass').html('');
		}
	}
	$(document).ready(function(){
		$('#old-pass').keyup( function() {
			var pass_val = $('#old-pass').val();
			var p_len = pass_val.length;
			if(p_len<6) {
			  $('.error_old_pass').html('Please enter proper password with at least six characters.');
			  $("#old-pass").focus();
                return false;
			}else{
			 	$('.error_old_pass').html('');
			 }
		});
		$('#new-pass').keyup( function() {
			var pass_val = $('#new-pass').val();
			var p_len = pass_val.length;
			if(p_len<6) {
			  $('.error_new_pass').html('Please enter proper password with at least six characters.');
			  $("#new-pass").focus();
                return false;
			}else{
			 	$('.error_new_pass').html('');
			 }
		});
	   	$('#re-new-pass').keyup(function() {
			var cpass = $('#new-pass').val();
			var pass = $('#re-new-pass').val();
			//alert(pass);
			if (pass != cpass) {
				$('.error_re_new_pass').html('Password not match.');
		  		$("#re-new-pass").focus();
				return false;
			}else{
				$('.error_re_new_pass').html('');
			}
		});
	});
</script>
<style type="text/css">
	.error_old_pass,.error_new_pass,.error_re_new_pass {
	    margin: 0px 0 12px;
	    color: red;
	}
</style>