<?php 

setcookie('PHPSESSID', session_id(), 0, '/');
session_start();



//if(0){
	if(!$_SESSION['is_allow'] && $_SESSION['is_allow'] != 1){
?>
		<html>
		<head>
			<title>Locumkit | Coming Soon</title>
			<style type="text/css">
				.coming-soon{
					text-align: center;	
					padding: 10% 0 0;	
					background: rgba(0, 0, 0, 0.46);
				    height: 100%;
				    width: 100%;		
				}
				input[type="password"] {
				    border: 1px solid #ccc;
				    border-radius: 3px;
				    padding: 8px 15px;
				}
				input[type="submit"] {
				    padding: 8px 10px;
				    border: 1px solid #03A9F4;
				    margin-left: -5px;
				    border-top-right-radius: 3px;
				    border-bottom-right-radius: 3px;
				    text-transform: uppercase;
				    background: #03A9F4;
				    cursor: pointer;
				    color: #fff;
				}
				p,a{
					color: #ccc;
				}
				img{
					position: absolute;
				    top: 0;
				    left: 0;
				    width: 100%;
				    height: 100%;
				    object-fit: cover;
				    z-index: -1;
				}
				h1{
					color: #fff;
				    font-size: 45px;
				    text-transform: capitalize;
				    margin-bottom: 0;
				}
				body{
					padding: 0;
		    		margin: 0;
				}

			</style>
		</head>
		<body>
			<?php 
				$status = '';
				if (isset($_POST['submit'])) {
				 $pass = isset($_POST['coming_soon_pass']) ? $_POST['coming_soon_pass'] : '';
					if ($pass && $pass == 'locumkit_in_2018') {
						//$_SESSION['is_allow_access_web'] = 1;
						$_SESSION['is_allow'] = 1;
						echo "<script type='text/javascript'> window.location.href='http:/ec2-18-163-113-25.ap-east-1.compute.amazonaws.com/' ;</script>";
					}else{
						$status = 'Not valid user to access website.';
					}
				}

				?>
				<div class="coming-soon">
					<img src="public/frontend/locumkit-template/css/img/bg.png">
					<h1>Coming soon....</h1>
					<h3>Launching Jan 2019</h3>
					<p><a href="javascript:void(0)">Click here</a> to login.</p>
					<p style="color:red"><?php echo $status ?></p>
					<div class="login-box" style="display:none;">
						<form method="POST">
							<input type="password" name="coming_soon_pass" placeholder="Enter web access password." required="required">
							<input type='submit' name="submit" value="Submit">
						</form>
					</div>
				</div>
				<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
				<script type="text/javascript">
					$('a').click(function(){
						$('.login-box').toggle(500);
					});
				</script>	
				<?php
				die();
				
			?>

		</body>
		</html>
<?php } ?>