<?php
	$return = $this->script('forgot-process');
	$number_1 = mt_rand(1, 9);
	$number_2 = mt_rand(1, 9);
	$answer = substr(sha1($number_1+$number_2),5,10);
	if(isset($_SESSION['user_id']) && $_SESSION['user_id']!=''){
		//$redirect=$this->redirect()->toUrl('http://google.com');
		//echo $redirect;
	//echo '1';	
	}
?>
<section id="breadcrum" class="breadcrum">
    <div class="breadcrum-sitemap">
         <div class="container">
            <div class="row">
                <ul>          
                    <li><a href="<?php echo $this->serverUrl();?>">Home</a></li>
					<li><a href="/forgot-password">Forgot Password</a></li>
                </ul>
             </div>
         </div>
     </div>
     <div class="breadcrum-title">
        <div class="container">
            <div class="row">
                <div class="set-icon registration-icon">
                    <i class="glyphicon glyphicon-log-in" aria-hidden="true"></i>
                </div>
                <div class="set-title">
                    <h3>Forgot Password</h3>
                </div>
            </div>
        </div>
     </div>
</section>
<div id="primary-content" class="main-content register">
	<div class="container">
    	<div class="row">
        	<div class="contents white-bg">
                    <div class="col-md-6 forgot_block">					
                    <div class="one-page-box visible widget-box no-border col-xs-12">
                        <div class="widget-body">
                            <div class="widget-main">
                               <div class="small-content">
                                    <?php echo $this->shortcontent; ?>
                                </div>
                    <?php echo $this->partial('flash-messages'); ?>
                                <form id="one-page-form" class="login-from forget-password-form" action="/forgot-password" method="post">
                                 <?php if(!empty($return['error_message'])): ?>
                                        <div class="notification error"><span><?php echo $this->escapeHtml($return['error_message']); ?><span></div>
                                    <?php endif; ?>
                                    <fieldset class="has-warning">
                                        <span class="block input-glyphicon input-glyphicon-right margin-bottom">
                                            <input name="email" type="text" class="form-control margin-bottom" placeholder="Enter email or username" autofocus required />
                                        </span>
                    
                                        <div class="clearfix buttons">
                                            <button class="pull-left btn btn-small btn-warning">
                                                <i class="glyphicon glyphicon-log-in"></i>
                                                Submit
                                            </button>
                                            <!--<a href="<?php echo $this->serverUrl();?>/login-form" class="pull-right">Login</a>-->
                                        </div>
                                    </fieldset>
                                </form>
                                <div class="login-footer">
                                     <p>If you are still having difficulty logging in<br>Please contact Locumkit admin by  <a href="<?php echo $this->serverUrl();?>/contact">clicking here</a> </p> <p>If you have not registerd for an account, please <a href="<?php echo $this->serverUrl();?>/register">register here</a></p><p><a href="javascript:void(0);" title="Log In" alt="Log In" data-toggle="modal" data-target="#login-form-model">Return to login</a></p>
                                </div>
                            </div>
                    
                            <div class="footer clearfix text-right">
                               
                            </div>
                        </div>
                    </div>
                </div><!-- col-md-6 end -->
                <div class="col-md-6" style="display:none;">
                    <div class="login-note">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
   	</div>
</div>