<!-- Home Banner -->
<div class="container-fluid homebanner">
    <div class="container">
    	<div class="row">  
        	<div class="col-md-7 col-sm-7 col-xs-12 bannercont animate" data-anim-type="fadeInLeft" data-anim-delay="800">
            	<!--<h1>Work the way you want. <br> Find opportunities around you.</h1>-->
                <div class="center">
                    <?php echo $this->translate($this->banner1content); ?>
                </div>

                <ul class="list-inline">
                <li><a href="/locums" class="btn btn-trans">For Locums</a></li>
                <li><a href="/employer" class="btn btn-trans">For Employers</a></li>
                </ul>                
                <a href="/register" class="btn btn-white lkbtn btn-1"><span>Register now for FREE</span></a>
            </div>
            <div class="col-md-5 col-sm-5 col-xs-12 bannervideo animate" data-anim-type="fadeInRight" data-anim-delay="800">
                <div class="inbox onclickvideo scalimg">
                    <figure>
                        <img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/hvideoround.png'); ?>" alt="Locumkit Video">
                    </figure>
                    <figcaption>
                    	<a href="javascript:void(0);" id="fs-pop-video" data-src="https://www.youtube.com/embed/<?php echo $this->utubevideoid; ?>?autoplay=1&showinfo=0&controls=0&modestbranding=1&rel=0&enablejsapi=1"><i class="fa fa-play" aria-hidden="true"></i></a>
                    </figcaption>
                </div>
            </div> 
        </div>
    </div>
</div>
<!-- .Home Banner -->

<section class="cmnhp hsec1 animate" data-anim-type="fadeInDown" data-anim-delay="800">
    <div class="container">
        <div class="row">
        	<div class="col-md-12 col-sm-12 col-xs-12 text-center">
            	<h2 class="head1">Your locumkit journey</h2>
                <?php //echo $this->translate($this->aboutcontent); ?>
            </div>        
        </div>
    </div>
</section>

<section class="leflow hsec2 animate" data-anim-type="fadeInDown" data-anim-delay="800">
    <div class="container-fluid">
        <div class="row">
        
            <div class="col-md-6 col-sm-12 col-xs-12 frempl">
                <div class="inbox">
                    <h2 class="text-center">For Locum</h2>
                    <div class="flowbx">
                    	<div class="col-md-3 col-sm-3 col-xs-12 cicon icon1 text-center">
                        	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/eicon1.png');?>" alt="Create a profile"></figure>
                            <figcaption><h5>Create a profile</h5></figcaption>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12 cicon icon2 text-center">
                            <figcaption class="lk_hide_mob"><h5>Get Proposal</h5></figcaption>
                        	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/eicon2.png');?>" alt="Get Proposal"></figure>
                            <figcaption class="lk_sh_mob"><h5>Get Proposal</h5></figcaption>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12 cicon icon3 text-center">
                        	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/eicon3.png');?>" alt="Manage Job"></figure>
                            <figcaption><h5>Manage Job</h5></figcaption>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12 cicon icon4 text-center">
                            <figcaption class="lk_hide_mob"><h5>Finance</h5></figcaption>
                        	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/eicon4.png');?>" alt="Finance"></figure>
                            <figcaption class="lk_sh_mob"><h5>Finance</h5></figcaption>
                        </div>
                    </div>
                </div>   
            </div>     
                <div class="col-md-6 col-sm-12 col-xs-12 frlocum">
                <div class="inbox">
                    <h2 class="text-center">For Employer</h2>
                    <div class="flowbx">
                        <div class="col-md-3 col-sm-3 col-xs-12 cicon icon1 text-center">
                            <figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/licon1.png');?>" alt="Create a profile"></figure>
                            <figcaption><h5>Create a profile</h5></figcaption>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12 cicon icon2 text-center">
                            <figcaption class="lk_hide_mob"><h5>Match</h5></figcaption>
                            <figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/licon2.png');?>" alt="Match Locum"></figure>
                            <figcaption class="lk_sh_mob"><h5>Match</h5></figcaption>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12 cicon icon3 text-center">
                            <figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/licon3.png');?>" alt="Engage Locum"></figure>
                            <figcaption><h5>Engage</h5></figcaption>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12 cicon icon4 text-center">
                            <figcaption class="lk_hide_mob"><h5>Hire</h5></figcaption>
                            <figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/licon4.png');?>" alt="Hire Locum"></figure>
                            <figcaption class="lk_sh_mob"><h5>Hire</h5></figcaption>
                        </div>
                    </div>
                </div>   
            </div>   
        </div>
    </div>
<!--     <div class="container">
        <div class="row btnrow animate" data-anim-type="fadeInUp" data-anim-delay="800">
        	<div class="col-md-12 col-sm-12 col-xs-12 text-center">
            	<a href="javascript:void(0);" data-toggle="modal" data-target="#login-form-model" class="btn btn-black lkbtn btn-1"><span>Sign in here</span></a>
            </div> 
        </div>
    </div> -->
</section>

<section class="cmnhp hsec3 animate" data-anim-type="fadeInDown" data-anim-delay="800">
    <div class="container">
        <div class="row">
        	<div class="col-md-12 col-sm-12 col-xs-12 text-center">
            	<h2 class="head1">A sample of jobs available</h2>
                <?php //echo $this->translate($this->interestedjob); ?>
            </div>        
        </div>
    </div>
</section>

<section class="jobtbl hsec4">
    <div class="container">
        <div class="row animate" data-anim-type="fadeInDown" data-anim-delay="800">
        	<div class="col-md-12 col-sm-12 col-xs-12">
            	<div class="table-responsive">
	                <!--<table class="table table-hover">
	                  <thead>
	                    <tr>
	                      <th>Job Id</th>
	                      <th>Job Date</th>
	                      <th>Job Rate</th>
	                      <th>Store Name</th>
	                      <th>Location</th>
	                    </tr>
	                  </thead>
	                  	<tbody>
		                    <tr>
		                      	<td>2365411</td>
			                   	<td><?php echo date('d/m/Y', strtotime('+7 days')) ?></td>
			                    <td><?php echo $this->config()->get('site_currency'); ?>1000.00</td>
			                    <td>Sample Store</td>
			                    <td>Nuneaton Warwickshire, EX 144 </td>
		                    </tr>
		                    <tr>
		                      	<td>2365412</td>
			                   	<td><?php echo date('d/m/Y', strtotime('+20 days')) ?></td>
			                    <td><?php echo $this->config()->get('site_currency'); ?>1000.00</td>
			                    <td>Sample Store</td>
			                    <td>Nuneaton Warwickshire, EX 144 </td>
		                    </tr>
		                    <tr>
		                      	<td>2365413</td>
			                   	<td><?php echo date('d/m/Y', strtotime('+23 days')) ?></td>
			                    <td><?php echo $this->config()->get('site_currency'); ?>1000.00</td>
			                    <td>Sample Store</td>
			                    <td>Nuneaton Warwickshire, EX 144 </td>
		                    </tr>
		                    <tr>
		                      	<td>2365414</td>
			                   	<td><?php echo date('d/m/Y', strtotime('+41 days')) ?></td>
			                    <td><?php echo $this->config()->get('site_currency'); ?>1000.00</td>
			                    <td>Sample Store</td>
			                    <td>Nuneaton Warwickshire, EX 144 </td>
		                    </tr>
	                  	</tbody>
	                </table>-->
	                <?php echo $this->interestedjob; ?>
              	</div>
            </div>        
        </div>
        <div class="row animate" data-anim-type="fadeInUp" data-anim-delay="800">
        	<div class="col-md-12 col-sm-12 col-xs-12 text-center">
            	<a href="<?php echo $this->serverUrl();?>/register" class="btn btn-default lkbtn btn-1"><span>Register to Apply</span></a>
            </div> 
        </div>
    </div>
</section>

<section class="cmnhp hsec5 animate" data-anim-type="fadeInDown" data-anim-delay="800">
    <div class="container">
        <div class="row">
        	<div class="col-md-12 col-sm-12 col-xs-12 text-center">
            	<h2 class="head1">Some of our partners</h2>
                <?php //echo $this->translate($this->ourclient); ?>
            </div>        
        </div>
        <div class="row clintlogo">
        	<div class="col-md-2 col-sm-3 col-xs-12 text-center ">
            	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/client-logo/Boots.jpg');?>" alt="Client Boots" width="100%"></figure>
            </div> 
            <div class="col-md-2 col-sm-3 col-xs-12 text-center">
            	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/client-logo/Optical-Express.jpg');?>" alt="Client Optical Express" width="100%"></figure>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-12 text-center">
            	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/client-logo/Scrivens.jpg');?>" alt="Client Scrivens" width="100%"></figure>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-12 text-center">
            	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/client-logo/Specsavers.jpg');?>" alt="Client Specsavers" width="100%"></figure>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-12 text-center">
            	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/client-logo/VE.jpg');?>" alt="Client VE" width="100%"></figure>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-12 text-center">
            	<figure><img src="<?php echo $this->cdn('/frontend/locumkit-template/new-design-assets/images/logo.png');?>" alt="Client Logo" width="100%"></figure>
            </div>
               
        </div>
    </div>
</section>

<!-- Single Resource Email Modal -->
<div class="modal fade-scale " id="sremail" tabindex="-1" role="dialog">
	<div class="modal-dialog cmnpopup bvpop" role="document">
		<div class="modal-content nobshadow col-md-12 col-sm-12 col-xs-12">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            	<span aria-hidden="true">&times;</span>
            </button>  
          	<div class="inbox" id="video-iframe">                
             	
            </div>	            
		</div>
	</div>
</div>
