<?php
	$return = $this->script('reset-password-process');
	$number_1 = mt_rand(1, 9);
	$number_2 = mt_rand(1, 9);
	$answer = substr(sha1($number_1+$number_2),5,10);
	if(isset($_SESSION['user_id']) && $_SESSION['user_id']!=''){
		$url= $this->serverUrl().'/login-form';
        echo "<script type='text/javascript'>window.location='".$url."'</script>";
	}
	$helper = new Zend\View\Helper\ServerUrl();
	$url = $helper->__invoke(true);
	//echo $url; //full url
	$str = explode('?',$url);
	$str2 = explode('-',$str[1]); 
	$get_uid=$str2[0];
	$get_email=$str2[1];
    
?>
<section id="breadcrum" class="breadcrum">
    <div class="breadcrum-sitemap">
         <div class="container">
            <div class="row">
                <ul>          
                    <li><a href="<?php echo $this->serverUrl();?>">Home</a></li>
		    <li><a href="/reset-password">Reset Password</a></li>
                </ul>
             </div>
         </div>
     </div>
     <div class="breadcrum-title">
        <div class="container">
            <div class="row">
                <div class="set-icon registration-icon">
                    <i class="glyphicon glyphicon-log-in" aria-hidden="true"></i>
                </div>
                <div class="set-title">
                    <h3>Reset Password</h3>
                </div>
            </div>
        </div>
     </div>
</section>
<div id="primary-content" class="main-content register">
	<div class="container">
    	<div class="row">
        	<div class="contents white-bg">
               <div class="col-md-8 col-md-offset-2">
			<?php echo $this->partial('flash-messages'); ?>
                    <div class="one-page-box visible widget-box no-border col-xs-12">
                        <div class="widget-body">
                            <?php if (!isset($_GET['reset']) && $_GET['reset'] != 'true') { ?>
                              <div class="widget-main">
                                  <h4 class="header">
                                     Reset Password
                                  </h4>
                                  
                                  <form id="one-page-form" action="/reset-password" method="post">
                                   <?php if(!empty($return['error_message'])): ?>
                                          <div class="notification error"><span><?php echo $this->escapeHtml($return['error_message']); ?><span></div>
                                      <?php endif; ?>
                                      <fieldset class="has-warning">
                                         <input type="hidden" name="get_uid" value="<?php echo $get_uid; ?>">
                                         <input type="hidden" name="get_email" value="<?php echo $get_email; ?>">  
                                          <span class="block input-glyphicon input-glyphicon-right margin-bottom">
                                              <input name="password" type="password" class="form-control margin-bottom" placeholder="Enter new password" autofocus required id="orig-password"/>
                                              <div class="css_error" id="orig_password_error"></div>
                                              <input name="password1" type="password" class="form-control margin-bottom" placeholder="Re-enter password" autofocus required id="re-password" />
                                              <div class="css_error" id="re_password_error"></div>
                                          </span>
                      
                                          <div class="clearfix buttons">
                                                        <button class="pull-right btn btn-small btn-warning">
                                                  <i class="glyphicon glyphicon-log-in"></i>
                                                  Reset Password
                                              </button>
                                          </div>
                                      </fieldset>
                                  </form>
                              </div>
                            <?php }else{ ?>
                              <h3 class="resetpass">You have successfully reset your password - Please try logging in with your new password</h3>
                              <h4 style="text-align: center;">Please <a href="javascript:void(0);" title="Log In" alt="Log In" data-toggle="modal" data-target="#login-form-model">click here</a> to login.</h4>
                            <?php } ?>
                            <div class="footer clearfix text-right">
                               
                            </div>
                        </div>
                    </div>
                </div><!-- col-md-6 end -->
            </div>
        </div>
   	</div>
</div>
<script type="text/javascript">
    $('#orig-password').on('keyup', function() {
      var pass_val = $('#orig-password').val();
      var p_len = pass_val.length;
      if(p_len<6) {
        $('#orig_password_error').html('Please enter password more than 6 character.');
        $("#orig-password").focus();
            return false;
        }else{
          $('#orig_password_error').html('');
        }
    });
    $('#re-password').on('keyup', function() {
      var pass_val = $('#re-password').val();
      var p_len = pass_val.length;
      if(p_len<6) {
        $('#re_password_error').html('Please enter confirm password.');
        $("#re-password").focus();
                    return false;
        }else{
          $('#re_password_error').html('');
        }
    });
    $('#re-password').on('keyup', function() {
      var cpass = $('#re-password').val();
      var pass = $('#orig-password').val();
      //alert(pass);
      if (pass != cpass) {
        $('#re_password_error').html('Password not match.');
          $("#re-password").focus();
        return false;
      }else{
        $('#re_password_error').html('');
      }
    });
</script>
<style type="text/css">
  .css_error {
    color: #FF0000;
    margin: -5px 0 15px;
  }
</style>