<?php
	if(isset($_SESSION['user_id']) && $_SESSION['user_id']!=''){
		$uid=$_SESSION['user_id'];
	}else{ 	echo "<script type='text/javascript'>alert('you are not valid user to access this page.');window.location='".$this->serverUrl()."/404'</script>";}

	use GcFrontend\Controller\DbController as DbController;
	use Gc\User\Role\Model;
	use Gc\User\Professional\Model as Model2;
	use Gc\User\Package\Model as Model3;
	use Gc\Db\AbstractTable;
	use Zend\Db\Sql\Sql;
	use Zend\Db\TableGateway\TableGateway;
	use Zend\Db\Sql\Where;
	use GcFrontend\Controller\FunctionsController as FunctionController;
	use GcFrontend\Controller\PackagePrivilegesController;
	$packagePrivilegesController = new PackagePrivilegesController();
	$dbConfig = new DbController();
    $adapter = $dbConfig->locumkitDbConfig();
	$functionController= new FunctionController();
    $sql = new Sql($adapter);
    $update = $sql->update();
    $select = $sql->select();
	$helper = new Zend\View\Helper\ServerUrl();
	$url = $helper->__invoke(true);
	$host=$this->serverUrl();
	
	$str = explode('?',$url);
	$str2 = explode('=',$str[1]); 
	if(isset($_GET['s']) && $_GET['s']!=''){
		//$job_search_id=$str2[1]; // google.com?s=8
		$job_search_id=$_GET['s']; // google.com?s=8
	    $_SESSION['job_search_id']=$job_search_id;
	}
	$currency=$this->config()->get('site_currency');
	$result_arr="";
	use GcFrontend\Controller\DistancecalculateController as Distancecal;
    $distancecal = new Distancecal();
	
	// check session for employer and get data with matching criteria	   
    if(isset($_SESSION['user_role_id']) && $_SESSION['user_role_id']=="3"){
		$uid=$_SESSION['user_id']; //user id from session
		
		$sqlString_anse="select * from user_answer where user_id='$uid'";  
		$results_anse = $adapter->query($sqlString_anse, $adapter::QUERY_MODE_EXECUTE);
		$result_data_anse = $results_anse->toArray(); 
		  foreach($result_data_anse as $res_qu){
			$questions[]=$res_qu['question_id'];
			$answers[$res_qu['question_id']]=$res_qu['type_value'];
		  }
		$_SESSION['emp_question_id']=$questions; // define session array of question id 
		$emp_ans_array=$answers; // define session array of ans to question
		
		//get Job Details
		$sql_job="select * from job_post where e_id='$uid' and job_id='$job_search_id' ";
		$rows_job = $adapter->query($sql_job, $adapter::QUERY_MODE_EXECUTE);
		$result_job = $rows_job->current();
		
		if(isset($result_job) && ($result_job['job_status']!=3 || $result_job['job_status']!=2)){
			$job_title=$result_job['job_title'];
			$job_id=$result_job['job_id'];
			$job_rate=$result_job['job_rate'];
			$job_date=$result_job['job_date'];
			$job_address=$result_job['job_address'];
			$job_type=$result_job['job_type'];
			$job_post_desc=$result_job['job_post_desc'];
			$job_zip=str_replace(' ', '',$result_job['job_zip']);
			// $job_region=$result_job['job_region'];
			$store_id=$result_job['store_id'];

			//get Job Details
			$sql_employer_job="select * from employer_store_list where emp_st_id='$store_id'";
			$employer_rows_job = $adapter->query($sql_employer_job, $adapter::QUERY_MODE_EXECUTE);
			$employer_store_result_job = $employer_rows_job->current();
			$job_region=$employer_store_result_job['emp_store_region'];

			echo "<strong>Employer-region:</strong>".$job_region."<br>"; 
			echo "<strong>Job-rate:</strong>".$job_rate."<br>"; 
		}
		$cat_id=$_SESSION['user_profession_id']; //cat id from session
		$user_role_id=$_SESSION['user_role_id'];
		
		$result_arr=""; $result_arr22=""; $count_pulist="";$valid_jobp="";
		
		// get list of private user
		$sql_pulist="select * from private_user where emp_id='$uid'";
		$rows_pulist = $adapter->query($sql_pulist, $adapter::QUERY_MODE_EXECUTE);
		$result_pulist=$rows_pulist->toArray();
		$count_pulist=$rows_pulist->count();
		
		if($count_pulist>0){
			foreach($result_pulist as $arr_pulist){
			$p_uid=$arr_pulist["p_uid"]; 
			$p_name=$arr_pulist['p_name'];
			$p_email=$arr_pulist['p_email'];   
			// select job accepted by privat user
	        $sql_job="select * from private_user_job_action where puid='$p_uid' and status=2"; // status=2 i.e job accepted by private user
	        $results_job = $adapter->query($sql_job, $adapter::QUERY_MODE_EXECUTE); 
		    $result_data_job = $results_job->current();
			if(isset($result_data_job) && $result_data_job >10){ $valid_jobp="0";}  // max 10 job allowed to private user
				if($valid_jobp==""){	
					$result_arr22.='<div class="col-md-12"><div class="col-md-1"><input type="checkbox" class="checkinvitep" name="checkinvitep[]" value="'.$p_email.'_'.$p_uid.'_'.$p_name.'"></div><div class="col-md-2"><span>'.$p_name.'</span></div><div class="col-md-4">'.$p_email.'</div><div class="col-md-2"><a href="javascript:void(0);" onclick=delete_puser('.$p_uid.')><i class="fa fa-trash-o" title="Delete private user" alt="Delete private user" aria-hidden="true"></i></a></div></div>';
				} // 
		    }// foreach end
			$result_arr22.="<input type='hidden' name='private_user_invite' value='1'>";
		}else{
			$result_arr22.='<div class="col-md-12 no_serach_result"><p class="record_not_found">No Private user found.</p></div>';
		}
		$where=""; $where2=""; $sortby_name="";
		
		if($job_type==1 || $job_type==2){
			if(isset($_GET['sortByName']) && $_GET['sortByName']!=''){
				$sortby_name=$_GET['sortByName'];
				$where="ORDER BY u.firstname ".$sortby_name;
			}else{
				$where="ORDER BY u.firstname ASC";
			}
			if(isset($_GET['sortByID']) && $_GET['sortByID']!=''){
				$sortby_name=$_GET['sortByID'];
				$where="ORDER BY u.id ".$sortby_name;
			}
		$start=0; $limit=10;
		$i=0;
		$j=0;
		$k=0;
		// array of freelancer user for search criteria 
		$sql="select u.* ,ux.* from user u , user_extra_info ux  where u.user_acl_role_id!='$user_role_id' and u.user_acl_role_id!=1 and  u.user_acl_profession_id='$cat_id' and u.id=ux.uid and u.active=1 and ux.max_distance!='' and ux.minimum_rate!='' $where";
		$rows = $adapter->query($sql, $adapter::QUERY_MODE_EXECUTE); //print_r($rows);
		$rows2=$rows->toArray();
		//$rows2 = (array)$rows009;
		$count_rows=$rows->count();
		$distance_match="";
		$rate_match="";
		$question_match="";
		$answer_match="";
		$block_date_match="";
		$valid_job="";
		$get_arr_list=array();
		$emp_ans=count(array_filter($emp_ans_array));
	    $qusmatch=$this->escapeHtml($this->config()->get('qusMatch')); // question match % from admin
	    $qusmatch_per=$qusmatch/100;
	    
	    echo "<b>Question match % = $qusmatch</b><br/>";
	    
	    // Check if qus is assign to both free and employer or not.	
	    $no_qus_need_to_match = 0;    
    	$sqlQueMatch="SELECT equestion FROM user_question WHERE cat_id ='$cat_id' AND fquestion != '' AND equestion != ''";
		$queMatchData = $adapter->query($sqlQueMatch, $adapter::QUERY_MODE_EXECUTE);
		if (!empty($queMatchData)) {
			$no_qus_need_to_match = $queMatchData->count();
		}

		/* Check if employer want this qus for match or not */
		$no_ans_need_to_match = 0;
		$sqlAnsMatch="SELECT * FROM user_answer WHERE user_id ='$uid' AND type_value != '' ";
		$ansMatchData = $adapter->query($sqlAnsMatch, $adapter::QUERY_MODE_EXECUTE);
		if (!empty($ansMatchData)) {
			$no_ans_need_to_match = $ansMatchData->count();
		}
		echo "$no_qus_need_to_match ==== $no_ans_need_to_match <br/>";
		if ($no_ans_need_to_match < $no_qus_need_to_match) {
			$no_qus_need_to_match = $no_ans_need_to_match ;
		}
	    

		$emp_ans_per=round($qusmatch_per*$no_qus_need_to_match); echo "<strong>Answer Need to Match:</strong>".$emp_ans_per."<br>";
		$allow_job_count="";
		$notification_count="";	
		$result_usedList_count="";
		$cancellation_rate=0;
		$where3="";
		if(!empty($count_rows)){
			$paginatorEmp = new \Zend\Paginator\Paginator(new \Zend\Paginator\Adapter\ArrayAdapter($rows2));
            $paginatorEmp->setItemCountPerPage(3);
            $paginatorEmp->setCurrentPageNumber(empty($_GET['page']) ? 1 : (int)$_GET['page']); //print_r($paginatorEmp);
			foreach($rows2 as $resultset){
				$search_userid=$resultset['uid'];

				if ($resultset['max_distance'] == 'Over 50') {
					$max_distance = 6371;
				}else{
					$max_distance=$resultset['max_distance'];
				}
				$search_pack_id=$resultset['user_acl_package_id'];
				$search_user_zip=$resultset['zip'];
				$search_user_region=$resultset['city'];
				$search_fname=$resultset['firstname'];
				$search_login=$resultset['login'];
				$search_lname=$resultset['lastname'];
				$search_email=$resultset['email'];
				$search_category_id=$resultset['user_acl_profession_id'];
				$gender=ucfirst($resultset['gender']);
				$last_worked="N/A";
				$year_qualified="N/A";
				$feedback_avg="0";
				
				$used_list="";
				// calculate feedback
				if(isset($_GET['sortByFeedAvg']) && $_GET['sortByFeedAvg']!=''){
					$sortby_feed=$_GET['sortByFeedAvg'];
					$where2=" ORDER BY feedback_id ".$sortby_feed;
			    }
				
				$sql_fedbk="SELECT SUM(rating) as sum_total,COUNT(*)as total_count FROM job_feedback where fre_id='".$search_userid."' and status=1 ".$where2." ";
			    $results_fedbk = $adapter->query($sql_fedbk, $adapter::QUERY_MODE_EXECUTE);
				$result_fedbk_data=$results_fedbk->current();
				$result_fedbk_count = $results_fedbk->count(); 
				if($result_fedbk_count>0){
					$sum_total=$result_fedbk_data['sum_total'];
					$total_count=$result_fedbk_data['total_count'];
					$feedback_avgold=($sum_total/($total_count*5))*100;
					$feedback_avg=$feedback_avgold.'%';
				}
				//Cancellation Rate
				if(isset($_GET['sortByCancelRate']) && $_GET['sortByCancelRate']!=''){
					$sortby_canrate=$_GET['sortByCancelRate'];
					$where3=" ORDER BY a_id ".$sortby_canrate;
			    }
				$sql_cancelrate="SELECT SUM(f_notification) as sum_total,(SELECT f_notification FROM job_action WHERE f_notification =3) as sum_accept,COUNT(*)as total_count FROM job_action where f_id='".$search_userid."' and action!='' ".$where3." ";
				
			    $results_cnrate = $adapter->query($sql_cancelrate, $adapter::QUERY_MODE_EXECUTE);
				$result_cnrate_data=$results_cnrate->current();
				$result_cnrate_count = $results_cnrate->count(); 
				if($result_cnrate_count>0){
					$sum_total=$result_cnrate_data['sum_total'];
					$total_count=$result_cnrate_data['total_count'];
					$sum_accept=$result_cnrate_data['sum_accept'];
					$cancel_rate=($sum_total-$sum_accept);
					$cancellation_rate=$functionController->getFreCancellationRate($search_userid,$adapter).'%';
				}
				
				// last worked
				$sql_lastWorked="SELECT ja.f_id,jp.e_id,u.firstname FROM job_post jp,job_action ja,user u where ja.f_id='".$search_userid."' and ja.action=4 and ja.job_id=jp.job_id and jp.e_id=u.id order by ja.a_id DESC";
			    $results_lastWorked = $adapter->query($sql_lastWorked, $adapter::QUERY_MODE_EXECUTE);
				$result_lastWorked_data = $results_lastWorked->current();
				$result_lastWorked_count = $results_lastWorked->count(); 
				if($result_lastWorked_count>0){
					$last_worked=$result_lastWorked_data['firstname'];
				}
				
				// used list
				$sql_usedList="SELECT ja.f_id,jp.e_id FROM job_post jp,job_action ja where ja.f_id='".$search_userid."' and ja.action=4 and jp.e_id='".$uid."'";
			    $results_usedList = $adapter->query($sql_usedList, $adapter::QUERY_MODE_EXECUTE);
				$result_usedList_count = $results_usedList->count();
				$result_usedList_data = $results_usedList->current();  
				
				/*****Freelancer private job date**********/
				$pvj_date=str_replace('/','-',$job_date);
				$pvj_date_new=date('Y-m-d',strtotime($pvj_date));
				$sql_pvj="select priv_job_start_date from freelancer_private_job where priv_job_start_date like '%$pvj_date_new%' and f_id='".$search_userid."' ";
				$get_pvj = $adapter->query($sql_pvj, $adapter::QUERY_MODE_EXECUTE);
				$count_pvj = $get_pvj->count(); // count==0 means freelancer is available
				
				// get freelancer qualified year from answer table
				$sql_qu_year="select type_value as qualified from user_answer where question_id IN (select id from user_question where fquestion like '%qualified%' and cat_id='$cat_id') and user_id='$search_userid'";
				$get_qu_year = $adapter->query($sql_qu_year, $adapter::QUERY_MODE_EXECUTE);
				$result_qu_year=$get_qu_year->current();
				$count_qu_year=$get_qu_year->count();
				if($count_qu_year>0){ $year_qualified=$result_qu_year['qualified']; }
				
				/* Get min rate of freelancer at job date */
				$sqlGetRecord="SELECT available_date FROM user_work_calender  WHERE uid = '$search_userid'"; 
			  	$getRecord = $adapter->query($sqlGetRecord, $adapter::QUERY_MODE_EXECUTE);
			  	$allRecord = $getRecord->toArray();
			  	$recordArray = unserialize($allRecord[0]['available_date']);			  	
			  	$infoDate = date("Y-m-d", strtotime(str_replace('/','-',$job_date)));
			  	$isSetupRate = 0;
			  	if (!empty($recordArray)) {
			  		foreach ($recordArray as $key => $value) {
				  		if (date("Y-m-d", strtotime($value['date'])) == $infoDate) {
				  			$search_rate = $value['min_rate'];
				  			$isSetupRate = 1;
				  			break;
				  		}else{
				  			$isSetupRate = 0;
				  		}
				  		//print_r($value);
				  	}
			  	}
			  	
				if ($isSetupRate == 0) {
					$currentDay = date('l');
					$fre_rate = unserialize( $resultset['minimum_rate'] );
					$search_rate = $fre_rate[$currentDay];
				}
				//echo $search_rate;
				echo "<pre>";
				echo "<strong>Freelancer Login Name</strong>:".$search_login."<br>";
				echo $isSetupRate == 0 ? '' : '<strong style="color:red;">Special Rate:'.$search_rate.'</strong><br>';
				echo "</pre>";
				// answer match for user
				foreach ($emp_ans_array as $key => $value) {
					//echo $value."<br>";
					//$condition_arr=array("1"=>"Greater than","2"=>"Greater than OR equal to","3"=>"Less than","4"=>"Less than OR equal","5"=>"Equal to");
					$condition_arr=array("1"=>">","2"=>">=","3"=>"<","4"=>"<=","5"=>"=");
					$this_qus_match = 0;
					// get question range option for search criteria
					$sqlString_qu2="select * from user_question where id='".$key."' and range_type_condition!=0 ";
					echo "<br/>";
					$results_qu2 = $adapter->query($sqlString_qu2, $adapter::QUERY_MODE_EXECUTE);
					$results_qu22 = $results_qu2->current();
					$result_qu2_count = $results_qu2->count();
					if($result_qu2_count>0 && $value!=''){
						$condition=$results_qu22['range_type_condition'];
						$qu_value=unserialize($results_qu22['type_value']);
						$replace_str=str_replace('minutes','',$value);
						//$con_ser = $condition_arr[$condition].$replace_str;implode(',',$qu_value)
						//$con_ser = $value;
						$new_val=str_replace(",","','",$value);
						$con_ser = "'".$new_val."'";
						//$sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' and type_value LIKE '%$value%' ";           
						$sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' and type_value IN($con_ser) ";
						
					}else{
						if($value!='' && $key!=''){
						    $myArray = explode(',', $value); //echo $value; print_r($myArray);
							$myarr_count=count($myArray);
							if($myarr_count>1){
							   $new_val=str_replace(",","','",$value);
						       $con_ser = "'".$new_val."'";
							   $inarr=in_array('All', $myArray);
							   if($inarr==1){
								   $sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' and type_value !='' ";
							   }else{
							   		
							   		foreach ($myArray as $ans_value) {
							   			//echo "====$ans_value<br/>";
							   			$sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' and  FIND_IN_SET('".$ans_value."',type_value) "; 
							   			$multiselect_match = $adapter->query($sqlString_ans2, $adapter::QUERY_MODE_EXECUTE)->toArray();
							   			if (!empty($multiselect_match)){
							   				echo "<pre>"; 
							   				print_r($multiselect_match);
							   				echo "</pre>"; 
							   				$this_qus_match=1;
							   				//break;
							   			}else{
							   				$this_qus_match=0;
							   				break;
							   			}
							   		}
								   
							   }
							   
							}
							if($myarr_count==0 || $myarr_count==1){ 
							   //echo $sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' and type_value LIKE '%$value%' ";
							   if($value=="All"){
								   $sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' and type_value !=''";
								}else{
									$sqlchecktype6="select * from user_question where id=".$key;
									$checktype6 = $adapter->query($sqlchecktype6, $adapter::QUERY_MODE_EXECUTE);
									echo "<div style='background:green;border-bottom:1px solid #fff;color:#fff;'>Answer match : $value</div>";
									$result_checktype6 = $checktype6->current();
									if($result_checktype6['type_key'] == 6 ){
										if ($value == 'Yes') {
											$sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' and LOCATE( '$value', type_value )"; 
										}elseif($value == 'No' || $value == ''){
											$sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' "; 
										}										
									}else{
										$sqlString_ans2="select * from user_answer where question_id='".$key."' and user_id='".$search_userid."' and LOCATE( '$value', type_value )"; 
									}
							    }
							}      
						
						}    
					}
					if($value!='') {	
						$results_ans2 = $adapter->query($sqlString_ans2, $adapter::QUERY_MODE_EXECUTE); //die();
						$result_ans2_count = $results_ans2->count(); 
						
						//echo $result_ans2_count;print_r($results_ans2);
						$result_ans2_data = $results_ans2->current();

						/*echo "<pre style='background:red;'>";
						print_r($result_ans2_data);
						echo "</pre>";*/

						if($result_ans2_count > 0){
						   $get_arr_list[$search_userid][] = $result_ans2_count;
						}elseif($this_qus_match == 1){
							$get_arr_list[$search_userid][] = 1;
						}
						if($result_ans2_count==0 || $result_ans2_count==""){
							$sqlString_qutest="select * from user_question where id='".$key."' AND equestion != ' ' AND fquestion != ' ' ";
					        $results_qutest = $adapter->query($sqlString_qutest, $adapter::QUERY_MODE_EXECUTE);
							$result_anstest_data = $results_qutest->current();
							if ($result_anstest_data['equestion']) {
								echo "<pre>";
								echo "<strong>Question not matched-</strong>".$result_anstest_data['equestion'];
								echo "</pre>";
							}
							
						}
					}
				}
				/*echo "<pre>";
				print_r($get_arr_list[$search_userid]);
				echo "</pre>";*/
				$ans2_count=count($get_arr_list[$search_userid]); //echo 'ANS-count'.count($get_arr_list[$search_userid]).'<br>';//print_r($get_arr_list); 
				//echo count(array_filter($emp_ans_array)); echo "<br>";print_r($emp_ans_array);
				//get package -resourses
				$sql_pack="select * from user_acl_package where id='$search_pack_id'";
				$results_pack = $adapter->query($sql_pack, $adapter::QUERY_MODE_EXECUTE); 
				$result_data_pack = $results_pack->current();
				$search_package_userid = $result_data_pack['id'];
				$search_user_package = strtolower($result_data_pack['name']); // for gold=unlimited,silver=20 and bronze=10
				$pack_resource=unserialize($result_data_pack['user_acl_package_resources_id']);
				foreach($pack_resource as $pack_arr){
					$sql_pack_res="select * from user_acl_package_resources where id='$pack_arr' and allow_count!=0";
				    $results_pack_res = $adapter->query($sql_pack_res, $adapter::QUERY_MODE_EXECUTE);
					$results_pack_get = $results_pack_res->current(); 
					/*echo "<pre>";
					print_r($results_pack_get);
					echo "</pre>";*/
					//resource_key=10_notification,15_notification,10_jobs,20_jobs,100_jobs
					if($results_pack_get['resource_key']=="8_notification"){
						$notification_count=$results_pack_get['allow_count'];
					}
					if($results_pack_get['resource_key']=="10_notification"){
						$notification_count=$results_pack_get['allow_count'];
					}
					if($results_pack_get['resource_key']=="15_notification"){
						$notification_count=$results_pack_get['allow_count'];
					}
					if($results_pack_get['resource_key']=="10_jobs"){
						$allow_job_count=$results_pack_get['allow_count'];
					}
					if($results_pack_get['resource_key']=="20_jobs"){
						$allow_job_count=$results_pack_get['allow_count'];
					}
					if($results_pack_get['resource_key']=="100_jobs"){
						$allow_job_count=$results_pack_get['allow_count'];
					}
				}
				
				// get user job done and there count
				$count_accept=$functionController->jobAcceptCount($search_userid,$adapter);
				//echo "PACK-".$search_user_package;
				
				if(isset($count_accept) && $count_accept!="" && $search_user_package!="gold"){ 
				/*echo "<pre>";
				echo $allow_job_count."-".$notification_count."-".$count_accept." -Accept Count <br>";
				echo "</pre>";*/

				    if($search_user_package=="bronze" && $count_accept>$notification_count && $notification_count!=''){$valid_job="0";}				
					if($search_user_package=="silver" && $count_accept>$notification_count && $notification_count!=''){$valid_job="0";}
					
				}if($search_user_package=="gold"){$valid_job="";}
				
				// get block user from table
				$count_date_bkl=$functionController->blockByEmp($search_userid,$uid,$adapter);
				if ($count_date_bkl == 1) {
					echo "<pre>";
						echo "<b>Block by employer.</b>";
					echo "</pre>";
				}
				
				// get user membership expire date
				$check_membership = $functionController->checkUserMembershipPlan($search_userid,$adapter);
				$is_expired = 0;
				if ($check_membership == 0) {
					$is_expired = 1;
					echo "<pre style='background:red; color:#fff;'>";
						echo "<b>Membership package expired.</b>";
					echo "</pre>";
				}
				
				// get block dates


				$count_block_date=$functionController->userBlockDate($search_userid,$job_date,$adapter);
				if ($count_block_date == 1) {
					echo "<pre>";
						echo "<b>Not avilable on this date.</b>";
					echo "</pre>";
				}

				// get booked dates
				$count_book_date=$functionController->getBookDate($search_userid,$job_date,$adapter);
				if ($count_book_date == 1) {
					echo "<pre>";
						echo "<b>You have already booking ont this date so you are Not avilable on this date.</b>";
					echo "</pre>";
				}
				
				
				//get lat and lon of town for distance calculate
				$town_lat1 = '';
				$town_lon1 = '';
				$town_lat2 = '';
				$town_lon2 = '';
				$distance22 = '';
				$word_region_count= str_word_count($job_region);
				$user_region_count= str_word_count($search_user_region);

				// echo "+=+=+=$job_region";

				if($word_region_count==1){
					$job_region_new=ucfirst($job_region);
					$sql_jtown = "SELECT * from site_town_table WHERE Town like '%$job_region_new%' AND Lat != '' AND Lon !='' "; 
				}else{
					$job_region_new=ucfirst($job_region);
					$sql_jtown = "SELECT * from site_town_table WHERE Town like '%$job_region_new%' AND Lat != '' AND Lon !='' ";
				}
				if($user_region_count==1){
					$user_region_new=ucfirst($search_user_region);
					$sql_utown = "SELECT * from site_town_table WHERE Town like '%$user_region_new%' AND Lat != '' AND Lon !='' ";
				}else{
					$user_region_new=ucfirst($search_user_region);
					$sql_utown = "SELECT * from site_town_table WHERE Town like '%$user_region_new%' AND Lat != '' AND Lon !='' ";
				}

				echo "+=+=+=$user_region_new";
				
				/*echo "$sql_jtown <br/>";
				echo "$sql_utown <br/>";*/


				$res_jtown = $adapter->query($sql_jtown, $adapter::QUERY_MODE_EXECUTE);
				$res_get11 = $res_jtown->current(); 
				// echo "<pre>res_get11===";
				// print_r($res_get11);
				// echo "<pre>";
				
				echo '======='.$town_lat1 = $res_get11['Lat']; $tw_id1 = $res_get11['tw_id']; $town_lon1= $res_get11['Lon'];
				$res_utown = $adapter->query($sql_utown, $adapter::QUERY_MODE_EXECUTE);
				$res_get22 = $res_utown->current(); 
				// echo "<pre>";
				// print_r($res_get22);
				// echo "<pre>";

				$town_lat2 = $res_get22['Lat']; 
				$town_lon2= $res_get22['Lon'];

				// echo "town_lat1--". $town_lat1."</br>";
				// echo "town_lat2--". $town_lat2."</br>";

				//search calculate criteria
				if($town_lat1!="" && $town_lat2!=""){
				echo '----------------------------------max_distance '.$max_distance;
					/*$sql_utowns = "SELECT * from user_store_list WHERE store_list like '%$tw_id1%' AND s_uid='$search_userid' ";    
					$res_utowns = $adapter->query($sql_utowns, $adapter::QUERY_MODE_EXECUTE);
				    $res_gets22 = $res_utowns->current();
					$res_gets22_count = $res_utowns->count(); //print_r($res_gets22);*/
					//$distance2222 = round($distancecal->getDistanceTown($town_lat1,$town_lon1, $town_lat2,$town_lon2,'N'));
					echo "<pre>";
					echo "<h5>Store town : ".$res_get11['Town']."</h5>";
					echo $town_lat1."==".$town_lon1;
					echo "<h5>Freelancer Town : ".$res_get22['Town']."</h5>";
					echo  $town_lat2."==".$town_lon2;
					echo "</pre>";
					$new_diff = $distancecal->distance($town_lat1,$town_lon1, $town_lat2,$town_lon2,"M");
					//$dis_diff=$distancecal->distanceCalculation($town_lat1,$town_lon1, $town_lat2,$town_lon2,'mi',2);
					//if($new_diff == ""){$distance22 = $max_distance;}
					
					if($new_diff == 0){$distance22 = "zero";}
					if($new_diff != 0){ 
					   $distance22=round($new_diff);
					}
				}else{
							$lat_long_user = $distancecal->getLnt($user_region_new);
							$lat_long_job  = $distancecal->getLnt($job_region);
							$town_lat1 = $lat_long_job['lat']; 
							$town_lon1 = $lat_long_job['lng']; 
							$town_lat2 = $lat_long_user['lat']; 
							$town_lon2 = $lat_long_user['lng'];
							$new_diff  = $distancecal->distance($town_lat1,$town_lon1, $town_lat2,$town_lon2,"M");
							if($new_diff == 0){$distance22 = "zero";}
							if($new_diff != 0){ 
							   $distance22 = round($new_diff);
							}
							if($town_lat1 == "" && $new_diff == "" ){
								$distance22 = 'Undefined';
							}
						}
				if($town_lat1=="" && $new_diff==""){
					$distance22='Undefined';
					//echo '<p style="background:red;color:#fff">Location Latitude Or Longitude is not present in databse.</p>';
				}
				//get user categoryid
				$professionalTable = new Model2();
				$row2              = $professionalTable->fetchRow($professionalTable->select(array('id' => (int) $search_category_id)));
				$category_name=$row2['name'];

				//get min rate of all freelancer for job date

				//check all parameter for search
				if(isset($search_userid))
				{	
                    echo "<pre>";				
					echo 'Distance DIFFENENCE--'.$distance22.'-Distance REQUIRED-'.$max_distance.'<br>';
                    echo "</pre>";
					if($distance22 != ""){ // check for distance

						echo '------------------'.$distance22."--".$new_diff;
						if($distance22 == $new_diff || $distance22 == "zero"){  
							$distance_match=1;
						}
						echo "<b> $max_distance > $distance22</b>";
						if($distance22 > 0){
							if($distance22 > $max_distance){
								$distance_match=0;
							}
							if($distance22 < $max_distance && $distance22!=0){
								$distance_match=1;
							}
							if($distance22 == $max_distance){
								$distance_match=1;
							}
							if($max_distance=="Over 50"){
								$distance_match=1;
							}
						}
					}
					
					//echo $job_rate.'Job rate'.round($search_rate);
					//Check for rates 

					if ($search_rate <= $job_rate) {
						$rate_match = 1;
					}else{
						$rate_match = 0;
					}
					//echo $ans2_count.'-'.$emp_ans_per;
					//echo "$job_rate == $search_rate === $rate_match";	
					//pagination div
					$div_show=$i+$k;
					if($div_show>=$limit){
						$visible='style="display:none;"';
					}
					
					if($div_show % $limit == 0 ){
						if($i<=$limit){
							$div_show_class='show_list'.$div_show;
						}else{
							$div_show_class='show_list'.$div_show;
						}
					}
					
					if($result_usedList_count>0){
						if($result_usedList_data['f_id']==$search_userid){ //echo 'inside';
						   $result_arr.='<div class="col-md-12 '.$div_show_class.'" '.$visible.'><div class="col-md-1"><input type="checkbox" class="checkinvite" name="checkinvite[]" value="'.$search_email.'_'.$search_userid.'_'.$search_fname.'"></div><div class="col-md-2"><a href="javascript:void(0);" onclick="open_modal('.$search_userid.')">'.$search_fname.'</a></div><div class="col-md-1">'.$search_userid.'</div><div class="col-md-2">'.$last_worked.'</div><div class="col-md-2">'.$year_qualified.'</div><div class="col-md-2">'.$feedback_avg.'</div><div class="col-md-2" align="center"><a href="javascript:void(0);" class="color-red" onClick="block_user('.$search_userid.')" title="Block Freelancer" alt="Block Freelancer"><i class="fa fa-ban" aria-hidden="true" ></i></a></div></div>
				    <div class="col-md-12" style="display:none;" id="open_'.$search_userid.'">
					<div class="col-md-10"><div class="col-md-4"><h5>Name:</h5></div><div class="col-md-6">'.$search_fname.' '.$search_lname.'</div></div>
					<div class="col-md-10"><div class="col-md-4"><h5>Max Distance:</h5></div><div class="col-md-6">'.$max_distance.'</div></div><div class="col-md-10"><div class="col-md-4"><h5>Minimum Rate :</h5></div><div class="col-md-6">'.$currency.$search_rate.'</div></div>
				</div>		
				';   $k++;}
				 }
echo "<pre>";
echo '====='.$this_qus_match;
echo "<br/>";
					echo 'Distance-'.$distance_match.' Ans-'.$ans2_count.' BlDATe-'.$count_block_date.' BLdate-'.$count_date_bkl.' Valid job-'.$valid_job.' Rate-'.$rate_match.' Private-'.$count_pvj.' UID-'.$search_userid.' LOGIN-'.$search_login.'<br>';



/*echo $distance_match.'<br/>';
echo $ans2_count.'<br/>';
echo $emp_ans_per.'<br/>';
echo $count_block_date.'<br/>';
echo $valid_job.'<br/>';
echo $rate_match .'<br/>';
echo $count_pvj.'<br/>';*/


echo "</pre>";
                    echo "---------------------------------------------<br>";    
echo $distance_match;
echo '<br/>';
echo "$ans2_count>=$emp_ans_per";
echo '<br/>';
echo $valid_job;
echo '<br/>';
echo $rate_match;               
					/* Check user privileges */
					$is_user_pkg_allow_job_invitation = $packagePrivilegesController->getCurrentPackagePrivilegesResources('job_invitation',$search_userid,$adapter);

if($is_user_pkg_allow_job_invitation == 0){
echo '<div style="background:red; padding : 5px 10px; color:#fff;">OFSSS.. Package is not applicable for the invitation </div>';
}

echo '<div style="background:blue; padding : 5px 10px; color:#fff;">-----User END -----</div>';


					//show result on going from various condition
					if(($distance_match==1) && ($ans2_count>=$emp_ans_per) && ($count_block_date==0) && ($count_book_date==0) && ($count_date_bkl==0)  && ($rate_match == 1) && ($count_pvj==0) && $is_expired == 0 && $is_user_pkg_allow_job_invitation == 1){
		  echo 'Yesss...match';
					   $result_arr.='<div class="col-md-12 '.$div_show_class.'" '.$visible.'><div class="col-md-1"><input type="checkbox" class="checkinvite" name="checkinvite[]" value="'.$search_email.'_'.$search_userid.'_'.$search_fname.'"></div><div class="col-md-2"><a href="javascript:void(0);" onclick="open_modal('.$search_userid.')">'.$search_fname.'</a></div><div class="col-md-2">'.$search_userid.'</div><div class="col-md-2" style="display:none;">'.$last_worked.'</div><div class="col-md-2" style="display:none;">'.$year_qualified.'</div><div class="col-md-2">'.$cancellation_rate.'</div><div class="col-md-2">'.$feedback_avg.'</div><div class="col-md-2" align="center"><a href="javascript:void(0);" class="color-red" onClick="block_user('.$search_userid.')" title="Block Freelancer" alt="Block Freelancer"><i class="fa fa-ban" aria-hidden="true" ></i></a></div></div>
				    <div class="col-md-12" style="display:none;" id="open_'.$search_userid.'">
					<div class="col-md-10"><div class="col-md-4"><h5>Name:</h5></div><div class="col-md-6">'.$search_fname.' '.$search_lname.'</div></div>
					<div class="col-md-10"><div class="col-md-4"><h5>Max Distance:</h5></div><div class="col-md-6">'.$max_distance.'</div></div><div class="col-md-10"><div class="col-md-4"><h5>Minimum Rate :</h5></div><div class="col-md-6">'.$currency.$search_rate.'</div></div>
				</div>		
				';
					 
					   $i++;
					} // 
				}
			} // foreach end
			$total_records=$result_usedList_count+$i;
			$h=1;$css="";
			if($total_records>$limit){
				$result_arr.='<div class="col-md-12 margin-top" align="center">';
				for($r=0;$r<=$total_records;$r++){
					if($r%$limit==0){
						$div_list.='"show_list'.$r.'",';
						if($h==1){$css='style="font-size: 15px; border: 1px solid lightblue; padding: 5px; background-color: rgb(255, 255, 255);"';
						}else{
							$css="";
						}
						$result_arr.='<span><a href="javascript:void(0);" '.$css.' id="show_list'.$r.'" onclick="switchdivs(\'show_list'.$r.'\');" > '.$h.' </a></span>';
						$h++;
					}
				}
				$result_arr.='</div>';
			}
			if($i>0){
				$result_arr.="<input type='hidden' name='normal_user_invite' value='1'>";
			}
			//$result_arr.="<div class='pagination'>".$this->paginationControl($paginatorEmp, 'sliding', 'paginator', array('path' => $this->serverUrl().'/test?s='.$job_search_id))."</div>";
		}
		// when no record found 
		if($count_rows==0 || ($i==0)){ 
			$result_arr.='<div class="col-md-12 no_serach_result" align="center"><p class="record_not_found">No Matching Freelancers. <a href="/managejob?e='.$job_search_id.'"><i class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp;<a href="javascript:void(0);" onclick=delete_post('.$job_search_id.')><i class="fa fa-trash-o" aria-hidden="true"></i></a></p></div>';
		}
		
	  }// job_type=first come first server
	  
	  /*if($job_type==2){ // job_type=Build list
	   $valid_job="";
	   $sql_private="select * from private_user where emp_id='$uid'";
	   $results_private = $adapter->query($sql_private, $adapter::QUERY_MODE_EXECUTE);
	   $result_count=$results_private->count();
	   $result=$results_private->toArray();
	      
	   if($result_count>0){
		   $paginatorpri = new \Zend\Paginator\Paginator(new \Zend\Paginator\Adapter\ArrayAdapter($result));
           $paginatorpri->setItemCountPerPage(10);
           $paginatorpri->setCurrentPageNumber(empty($_GET['page']) ? 1 : (int)$_GET['page']);
		   foreach($result as $resultset){
			 $p_uid=$resultset["p_uid"];
			 $p_email=$resultset["p_email"]; 
			 $p_name=$resultset['p_name'];  
				// select job accepted by privat user
				$sql_job="select * from private_user_job_action where puid='$p_uid' and status=2"; // status=2 i.e job accepted by private user
				$results_job = $adapter->query($sql_job, $adapter::QUERY_MODE_EXECUTE); 
				$result_data_job = $results_job->current();
				if(isset($result_data_job) && $result_data_job >10){ $valid_job="0";}  // max 10 job allowed to private user  
				   
				if($valid_job==""){
					$result_arr.='<div class="col-md-12">
					<div class="col-md-2"><input type="checkbox" class="checkinvite2" name="checkinvite2[]" value="'.$p_email.'_'.$resultset['p_uid'].'_'.$p_name.'"></div>
					<div class="col-md-2">'.$p_name.'</div><div class="col-md-2">'.$p_email.'</div>
					<div class="col-md-2"><a href="javascript:void(0);" onclick=delete_puser('.$p_uid.')><i class="fa fa-trash-o" title="Delete private user" alt="Delete private user" aria-hidden="true"></i></a></div>
					</div>';
				 }
	       }
		   
		   $result_arr.="<div class='pagination'>".$this->paginationControl($paginatorpri, 'sliding', 'paginator', array('path' => $this->serverUrl().'/test'))."</div>";
	    }//if end
	  }*///if job_type==2 :buildlist
   } // check for session end
   
    // delete job
   if(isset($_POST['job_id']) && $_POST['job_id']!=''){
	$job_id=$_POST['job_id'];
	//$sql_del3="delete from job_post where job_id='$job_id'";
	$sql_del3="update job_post set job_status='7' where job_id='$job_id'";
	$results3 = $adapter->query($sql_del3, $adapter::QUERY_MODE_EXECUTE);
   }
    // block job
   if(isset($_POST['block_id']) && $_POST['block_id']!=''){
	$frelan_id=$_POST['block_id'];
	$sql_blck="insert into block_user(emp_id,frelan_id,user_block_date) values('$uid','$frelan_id',NOW())";
	$results3 = $adapter->query($sql_blck, $adapter::QUERY_MODE_EXECUTE);
   }
	
	// delete private user
	if((isset($_POST['del_puser'])) && $_POST['del_puser']==1){
    	$p_uid=$_POST['p_uid'];
		$sql_pdel="delete from  private_user where p_uid='$p_uid'";
		$results_pdel = $adapter->query($sql_pdel, $adapter::QUERY_MODE_EXECUTE);
	}
 
?>
<?php $return = $this->script('job-search-process'); ?>
<section id="breadcrum" class="breadcrum">
    <div class="breadcrum-sitemap">
         <div class="container">
            <div class="row">
                <ul>          
                    <li><a href="<?php echo $this->serverUrl();?>">Home</a></li>
					<li><a href="/job-listing">Job List</a></li>
					<li><a href="/job-search">Search List</a></li>
                </ul>
             </div>
         </div>
     </div>
     <div class="breadcrum-title">
        <div class="container">
            <div class="row">
                <div class="set-icon registration-icon">
                    <i class="glyphicon glyphicon-search" aria-hidden="true"></i>
                </div>
                <div class="set-title">
                    <h3>Search List</h3>
                </div>
            </div>
        </div>
     </div>
</section>
<div id="primary-content" class="main-content profiles">
    <div class="container">
        <div class="row">
            <div class="contents gray-gradient">
                <div class="welcome-heading">
                    <h1><span>Search Listing page</span></h1>
                    <hr class="shadow-line">
                </div>
                <div class="job-details">
                <?php echo $this->partial('flash-messages'); ?>
                 <?php if(!empty($return['error_message'])): ?>
                    <div class="notification error"><span><?php echo $this->escapeHtml($return['error_message']); ?><span></div>
                 <?php endif; ?>
                    <form id="jobsearch" name="jobsearch" action="<?php echo $this->escapeHtml($this->document('job-search')->getUrl()).'?s='.$job_search_id; ?>" method="post">
                    <input type="hidden" name="j_id" value="<?php echo $job_search_id;?>">
                    <input type="hidden" name="invite_send" value="1">
                    <input type="hidden" name="jtype" value="1">
                    <?php if($job_type==1 || $job_type==2){?>
					<div class="profile-edit-scroll">
                    <div class="profile-edit">
                        <div class="col-md-6 searc-re-sult">
                        	<div class="col-md-12 normal_user_list no-padding-left">
                        		<h5>Search Result</h5>
                        	</div>
                       	</div>
                       	<div class="col-md-6" align="right"> 
                        	<div class="job-edit-btn">
                                <a href="#add_puser"  id="add_puser_div" >Add Private User</a>
                                <input type="submit" name="invitation_send" class="invite-user-btn" value="Invite">
                                <!--<a href="javascript:void(0);"  id="print_page" class="print_page-btn">Print</a>-->
                        	</div>
                     	</div>
                        <div class="col-md-12 job_listing_details_table"> 
                        	<?php $sort_name="ASC"; $sort_name_icon="fa-sort-up"; $sort_id="ASC"; $sort_id_icon="fa-sort-up"; $sort_feed="ASC"; $sort_feed_icon="fa-sort-up"; $sort_canrate="ASC"; $sort_canrate_icon="fa-sort-up";
							     if(isset($_GET['sortByName']) && $_GET['sortByName']=='ASC'){
								     $sort_name="DESC";
									 $sort_name_icon="fa-sort-desc";
								 }
								 if(isset($_GET['sortByID']) && $_GET['sortByID']=='ASC'){
								     $sort_id="DESC";
									 $sort_id_icon="fa-sort-desc";
								 }
								 if(isset($_GET['sortByFeedAvg']) && $_GET['sortByFeedAvg']=='ASC'){
								     $sort_feed="DESC";
									 $sort_feed_icon="fa-sort-desc";
								 }
								 if(isset($_GET['sortByCancelRate']) && $_GET['sortByCancelRate']=='ASC'){
								     $sort_canrate="DESC";
									 $sort_canrate_icon="fa-sort-desc";
								 }
							?>                       	
                    		<table class="table table-hover">
                                <colgroup>
                                	<col width="10%">
	                                <col width="20%">
	                                <col width="20%">
	                                <col width="20%">
	                                <col width="10%">	                                
                                </colgroup>
                                <thead class="job_listing_heading title-by-search">
                                    <tr>
                                        <th>
                                        	<h5>
                                        		<input type="checkbox" name="checkinvite_1[]" onclick="checkAll(this);">
                                        	</h5>
                                        	
                                        </th>                                        
                                        <th>
                                        	<h5>
                                        		<a href="job-search?s=<?php echo $job_search_id;?>&sortByID=<?php echo $sort_id;?>" title="Sort by User ID">User ID &nbsp;<i class="fa <?php echo $sort_id_icon;?>" aria-hidden="true"></i></a>
                                        	</h5>
                                        </th>
                                        <th>
                                        	<h5>
                           				<a href="job-search?s=<?php echo $job_search_id;?>&sortByCancelRate=<?php echo $sort_canrate;?>" title="Cancellation Rate">Cancellation Rate &nbsp;	</a>
											</h5>
                                        </th>
                                        <th>
                                        	<h5>
                                        		<a href="job-search?s=<?php echo $job_search_id;?>&sortByFeedAvg=<?php echo $sort_feed;?>" title="Feedback Avg">Feedback Avg &nbsp;</a>
                                        	</h5>
                                        </th>
                                        <th style="text-align: center;">
                                        	<h5>
                                        		<a href="javascript:void();" title="View Applicant">Action</a>
                                        	</h5>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                	                          	
                                </tbody>
                        	</table>
<?php echo $result_arr;?>      
                        </div>
					</div>
					</div>
					<div class="profile-edit-scroll">
					<div class="profile-edit">
                       	  
					  <div class="col-xs-12 col-sm-12 col-md-12"><div class="private_user_head no-padding-left"><h5>Private User List</h5></div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 job_listing_heading">
                        <div class="user_list_title_bar">
                        <div class="col-xs-1 col-sm-1 col-md-1">
                            <h5><p>Invite</p></h5> 
                        </div>
                        <div class="col-xs-3 col-sm-3 col-md-3">
                            <h5>Name</h5> 
                        </div>
                        <div class="col-xs-5 col-sm-5 col-md-5">
                            <h5>Email</h5> 
                        </div>  
                        <div class="col-xs-2 col-sm-2 col-md-2">
                            <h5><p>Phone</p></h5> 
                        </div>                      
                        <div class="col-xs-1 col-sm-1 col-md-1">
                            <h5><p>Action</p></h5> 
                        </div>
                        </div>
                        </div>
                        <div class="private_user_list-item">
                        	<?php echo $result_arr22;?>
                        </div>
                  </div>
				  </div>
                  <?php }?>
                  <?php if($job_type==2){/*?>
                  <input type="hidden" name="invite_private" value="1">
                  <input type="hidden" name="jtype" value="2">
                  <div class="profile-edit">
                      <div class="col-md-12">
					  <div class="col-md-6 searc-re-sult">
                        	<div class="col-md-12 normal_user_list no-padding-left">
                        		<h5>Search Result</h5>
                        	</div>
                       	</div>
                       	<div class="col-md-6" align="right"> 
                        	<div class="job-edit-btn"><a href="javascript:void(0);"  id="add_puser_div" >Add Private User</a>
                             <input type="submit" name="invitation_send" class="invite-user-btn" value="Invite">
                        	</div>
                        </div>
					  </div>  
					  <div class="col-md-12 margin-top"><div class="col-md-12 private_user_head no-padding-left"><h5>Private User List</h5></div>
                        </div>
                        <div class="col-md-12 job_listing_heading">
					    <div class="user_list_title_bar">
                        <div class="col-md-2">
                            <h5><p><input type="checkbox" name="checkinvite2[]" onclick="checkAll(this);"></p></h5> 
                        </div>
						<div class="col-md-2">
                            <h5>Name</h5> 
                        </div>
                        <div class="col-md-2">
                            <h5>Email</h5> 
                        </div>                        
                        
                        <div class="col-md-1">
                            <h5><p>Action</p></h5> 
                        </div>
						</div>
                        </div>
                        <?php echo $result_arr;?>
                  </div>
                  <?php */}?>
                  </form>
             </div>
             <div class="private_user margin-top" style="display:none;">
             <form id="add_puser" name="add_puser" action="<?php echo $this->escapeHtml($this->document('job-search')->getUrl()).'?s='.$job_search_id; ?>" method="post">
              <input type="hidden" name="j_id" value="<?php echo $job_search_id;?>">
              <input type="hidden" name="add_private_user" value="1">
             
              <div class="col-md-12 margin-bottom heading_add">
              	<div class="add_private_user_table">
              		<h5>Add Private User</h5>
              	</div>
              </div>
              <div class="col-md-12 list_div margin-top">
                <div class="col-md-12 add_div">
                    <div class="col-md-4 margin-bottom no-padding-left">
                        <div class="col-md-2 no-padding-left" style="line-height: 30px;">
                            Name
                        </div>
                        <div class="col-md-8 no-padding-left-right">
                            <input type="text" name="p_name[]" placeholder="Enter name" class="form-control margin-bottom" required>
                        </div>
                    </div>
                    <div class="col-md-4 margin-bottom">
                        <div class="col-md-2 no-padding-left" style="line-height: 30px;">
                            Email
                        </div>
                        <div class="col-md-8 no-padding-left-right">
                            <input type="text" name="p_email[]" placeholder="Enter email" class="form-control margin-bottom" required>
                        </div>
                    </div>
                    <div class="col-md-3 margin-bottom">
                        <div class="col-md-3 no-padding-left" style="line-height: 30px;">
                            Mobile
                        </div>
                        <div class="col-md-8 no-padding-left-right">
                            <input type="text" name="p_mobile[]" placeholder="Enter mobile" class="form-control margin-bottom numbersOnly" maxlength="11">
                        </div>
                    </div>
                    <div class="col-md-1"><a href="javascript:void(0);" class="color-red" id="add_privateuser"><i class="fa fa-plus" aria-hidden="true" title="Add Freelancer"></i></a></div>
                </div>
              </div>
              <div class="col-md-12 privet-save-btn-wrap">
                <div class="col-md-offset-6 col-md-6" align="right">
                    <input type="submit" name="add_user" class="gradient-threeline" value="Save">
                </div>
              </div>
             </form>
             </div>
        </div>
    </div> 
</div>
<div id="detail_box" class="modal fade" role="dialog">
  	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header no-border-bottom">
				<button type="button" class="close" data-dismiss="modal" onclick="close_dive('detail_box');">&times;</button>
				<h4 class="modal-title">Freelancer Details</h4>
			</div>
			<div class="modal-body" id="fre_details">
				<h3 id="load_fre_details" style="display:none"><img src="../public/frontend/locumkit-template/img/loader.gif"> Please wait... </h3>
			</div>	  
		</div>
  	</div>
</div>
<script type="text/javascript">

function open_modal(id){
	if (id!='') {
		//Logic to copy the item
        $("#emp_details").html($("#open_"+id).html())

		$('#detail_box').show();
		$('#detail_box').addClass('in');
		$('#detail_box').css('display','block');		
	}
}
 
 function close_dive(id){
	$("#"+id).hide();
	$('.modal-backdrop').hide();
	//location.reload();
 }
  function checkAll(ele) {
     var checkboxes = document.getElementsByTagName('input');
     if (ele.checked) {
         for (var i = 0; i < checkboxes.length; i++) {
             if (checkboxes[i].type == 'checkbox') {
                 checkboxes[i].checked = true;
             }
         }
     } else {
         for (var i = 0; i < checkboxes.length; i++) {
             console.log(i)
             if (checkboxes[i].type == 'checkbox') {
                 checkboxes[i].checked = false;
             }
         }
     }
 }
  
  function send_invitation(id){ 
	 var checkinvite=$('.checkinvite').val(); 
	  chks = document.getElementsByName('checkinvite[]');
	  for (i = 0; i < chks.length; i++){
        if (chks[i].checked){
		 document.jobsearch.submit();
		 /*$.ajax({
		  'url'   :'/ajax-request',
		  'type'  :'POST',
		  'data'  : {check_invite : checkinvite},
		  'success':function(result){ alert(result);
			alert("Invitation Send.");
		  }
		});*/
	  }else{
		  alert("Please select atlest on freelancer.");
	  }
	}
  }
</script>
<script type="text/javascript">
	// print page 
	/*$("#print_page").click(function () {
	 window.print();
	});*/
	// delete private user
	function delete_puser(id){
		$('div#alert-confirm-modal #alert-message').html('Do you really want to delete private user?');
		$('div#alert-confirm-modal').addClass('in');
		$('div#alert-confirm-modal').css('display','block');
		$('div#alert-confirm-modal #confirm').click(function(){
			$.ajax({
				'url'   :'/job-search',
				'type'  :'POST',
				'data'  : {p_uid : id,del_puser: 1},
				'success':function(result){ 
					messageBoxClose();
					messageBoxOpen('Private user deleted.');
					$('.alert-modal .modal-footer button.btn.btn-default').attr('onclick',"window.location.reload()");					
				}
			});    
  		});	
	}
	function delete_post(id){
		var result = confirm("Do you really want to delete post?");
		if(result){ //alert('inside');
		 	$.ajax({
			  'url'   :'/job-search',
			  'type'  :'POST',
			  'data'  : {job_id : id},
			  'success':function(result){ 
				alert("Job post deleted.");
				window.location="<?php $this->serverurl(); ?>/job-listing";
			  }
		  });
		}
	}
  function view_user(id){ 
  	$("#fre_details").html('<h3 id="load_fre_details" ><img src="../public/frontend/locumkit-template/img/loader.gif"> Please wait... </h3>');
  	open_modal(id);
	$.ajax({
		'url'   :'/ajax-request',
		'type'  :'POST',
		'data'  : {'view_applicant_id' : id},
		'success':function(result){ 
			$('#load_fre_details').hide();			
			$("#fre_details").html(result);			
		}
	});
	
  }
  // for adding private user 
  
  $("#add_puser_div").click(function () {
	$(".private_user").show();
  });
  /// add private user
  var i = $(".add_div").size() + 1;
  $("#add_privateuser").click(function () {
		
		if(i > 1)
		{   
			$('.list_div').append('<div class="col-md-12 add_div"><div class="col-md-4 margin-bottom no-padding-left"><div class="col-md-2 no-padding-left">Name</div><div class="col-md-8 no-padding-left-right"><input type="text" name="p_name[]" placeholder="Enter name" class="form-control margin-bottom" required></div></div><div class="col-md-4 margin-bottom"><div class="col-md-2 no-padding-left">Email</div><div class="col-md-8 no-padding-left-right"><input type="text" name="p_email[]" placeholder="Enter email" class="form-control margin-bottom" required></div></div><div class="col-md-3 margin-bottom"><div class="col-md-3 no-padding-left">Mobile</div><div class="col-md-8 no-padding-left-right"><input type="text" name="p_mobile[]" placeholder="Enter mobile" class="form-control margin-bottom numbersOnly2" required maxlength="11"></div></div><span class="removeclass small2 remove-p-user"><i class="fa fa-times" aria-hidden="true" title="remove" alt="remove"></i></span></div>');
			i++;
			$('.numbersOnly2').keyup(function () {
				if (this.value != this.value.replace(/[^0-9\.]/g, '')) {
				   this.value = this.value.replace(/[^0-9\.]/g, '');
				}
			});
		}
		return false;
  });

  $("body").on("click",".removeclass", function(e){
	//event.returnValue = false;  // mozilla giving error rest working in safari ,crome and IE
	if( i > 1 ) { 
			$(this).parent('.add_div').remove();i--;
	}
  });
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>
    $(document).ready(function(){
		$("#print_page").click(function () {
            var contents = $(".contents").html();
            var frame1 = $('<iframe />');
            frame1[0].name = "frame1";
            frame1.css({ "position": "absolute", "top": "-1000000px" });
            $("body").append(frame1);
            var frameDoc = frame1[0].contentWindow ? frame1[0].contentWindow : frame1[0].contentDocument.document ? frame1[0].contentDocument.document : frame1[0].contentDocument;
            frameDoc.document.open();
            //Create a new HTML document.
            frameDoc.document.write('<html><head><title>Search Result</title>');
            frameDoc.document.write('</head><body>');
            //Append the external CSS file.
            frameDoc.document.write('<link href="<?php echo $this->cdn('/frontend/locumkit-template/css/style.css'); ?>" rel="stylesheet" type="text/css" /><link href="<?php echo $this->cdn('/frontend/locumkit-template/css/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css" /><link href="<?php echo $this->cdn('/frontend/locumkit-template/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css" />');
            //Append the DIV contents.
            frameDoc.document.write(contents);
            frameDoc.document.write('</body></html>');
            frameDoc.document.close();
            setTimeout(function () {
                window.frames["frame1"].focus();
                window.frames["frame1"].print();
                frame1.remove();
            }, 500);
        });
    });
	$('.numbersOnly').keyup(function () {
    if (this.value != this.value.replace(/[^0-9\.]/g, '')) {
       this.value = this.value.replace(/[^0-9\.]/g, '');
    }
});
<!--oprn div for pagination -->
var nextnum = 1;
function switchdivs(id){ 
nextnum++;
//var theid="show_list"+nextnum;
var theid=id;
var thearray= new Array(<?php echo isset($div_list) ? substr($div_list,0,-1) : '';?>); 
for(i=0; i<thearray.length; i++){ 
      if(thearray[i] == theid){ 
            //document.getElementsByClassName(theid).style.display="block";
			$("."+theid).show(1000);
			$("#"+theid).css({"background-color": "white", "font-size": "15px","border": "1px solid lightblue","padding": "5px"}); 
      }else{ 
	        $("."+thearray[i]).hide(1000); 
			$("#"+thearray[i]).css({"background-color": "none", "font-size": "12px","border": "none","padding": "5px"}); 
            //document.getElementsByClassName(thearray[i]).style.display="none"; 
      } 
     //alert(theid); 
   } 
} 
</script>