<div id="primary-content" class="main-content about">
    <div class="container">
        <div class="row">
            <div class="contents white-bg">
                <section id="suplier-add" class="suplier-add">
                    <div class="container" id="content_profitloss">
                        <div class="col-sm-10" style=" font-size: 14px; font-weight: bold;">
                            <div class="col-md-4">User No. : <?php echo $userData->getId() ; ?></div>
                            <div class="col-md-4">Name : <?php echo ucfirst($userData->getFirstname()) .' '.$userData->getLastname() ;  ?></div>
                            <div class="col-md-4">Email : <?php echo $userData->getEmail() ; ?></div>
                        </div>
                        <br/>
                            <h3>PROFIT AND LOSS</h3>
                            <div class="col-md-12 col-sm-12">

                                <div class="row">
                                    <div class="col-md-10 col-sm-10">
                                        <a href="#" onClick ="$('#tableID').tableExport({type:'pdf',escape:'true'});">Export</a>


                                         <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tableID">

                                            <tr>
                                                <td>Revenue</td>
                                                <td><?php echo  $revenue = $revenue1; ?></td>
                                            </tr>
                                            <tr>
                                                <td>Revenue</td>
                                                <td><?php echo  $revenue = $revenue1; ?></td>
                                            </tr>
                                            <tr>
                                                <td>Revenue</td>
                                                <td><?php echo  $revenue = $revenue1; ?></td>
                                            </tr>
                                            <tr>
                                                <td>Revenue</td>
                                                <td><?php echo  $revenue = $revenue1; ?></td>
                                            </tr>
                                            <tr>
                                                <td>Revenue</td>
                                                <td><?php echo  $revenue = $revenue1; ?></td>
                                            </tr>

                                        </table>

                                            <form class="form-horizontal">
                                                    <fieldset>
                                                    <!-- Name input-->
                                                    <div class="form-group">
                                                        <div class="col-md-6">
                                                            <h4>Revenue</h4>
                                                         </div>
                                                        <div class="col-md-6">
                                                            <h4>x</h4>
                                                         </div>
                                                    </div>



                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="cname">Cost of Sales</label>
                                                        <div class="col-md-6">
                                                            <?php echo $cos = $cos1; ?>
                                                        </div>
                                                    </div>

                                                    <!-- Store input-->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="sname">Gross Profit</label>
                                                        <div class="col-md-6">
                                                            <?php echo $gross = $revenue - $cos ; ?>
                                                        </div>
                                                    </div>

                                                    <!-- Address -->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="address">GP %</label>
                                                        <div class="col-md-6">
                                                            <?php echo $grossper = $gross/$revenue ; ?>
                                                        </div>
                                                    </div>

                                                    <!-- contact input-->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="email">Administrative expenses</label>
                                                        <div class="col-md-6">
                                                            <?php echo $othercost = $othercost1; ?>
                                                        </div>
                                                    </div>

                                                    <!-- contact input-->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="email">Profit from operations</label>
                                                        <div class="col-md-6">
                                                            <?php echo $pfo = $gross-$othercost ; ?>
                                                        </div>
                                                    </div>

                                                    <!-- contact input-->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="email">OP %</label>
                                                        <div class="col-md-6">
                                                            <?php echo $op = $pfo/$revenue ; ?>
                                                        </div>
                                                    </div>

                                                    <!-- contact input-->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="email">Interest income</label>
                                                        <div class="col-md-6">
                                                            <input id="interestincome" name="interestincome" type="number" value="" placeholder="Interest Income" class="form-control" >
                                                        <span id="inin"></span>
                                                        </div>
                                                    </div>

                                                    <!-- contact input-->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="email">Profit before taxs</label>
                                                        <div class="col-md-6">
                                                            <span id="pbt">N/A</span>
                                                        </div>
                                                    </div>

                                                    <!-- contact input-->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="email">Income tax</label>
                                                        <div class="col-md-6">
                                                            <?php echo $totaltax ;?>
                                                        </div>
                                                    </div>

                                                    <!-- contact input-->
                                                    <div class="form-group">
                                                        <label class="col-md-6 control-label" for="email">Profit after tax</label>
                                                        <div class="col-md-6">
                                                           <span id="pat">N/A</span>
                                                        </div>
                                                    </div>

                                                    <!-- Form actions -->
                                                    <div class="form-group">
                                                        <div class="col-md-12">
                                                            <div class="profile-edit-btn">
                                                                <button type="button" id="freeze" class="btn btn-info pull-right">Freeze</button>

                                                                <div id="editor"></div>
                                                                <button type="button" id="cmd">generate PDF</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </fieldset>
                                            </form>
                                    </div>
                                </div>
                            </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sprintf/1.1.0/sprintf.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-base64/2.0.5/angular-base64.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.4/js/tableexport.js"></script>
<script>
    $("#interestincome").keyup(function(){
       var totaltax =  '<?php echo $totaltax ;?>';
       var pfo =  '<?php echo $pfo ;?>';
       var inin =  $("#interestincome").val();
        if(inin == ''){
            $("#pbt").html('N/A');
            $("#pat").html('N/A');
        }else{
            var income = parseFloat(pfo) + parseFloat(inin);
            var pat = parseFloat(income) + parseFloat(totaltax);
            $("#pbt").html(income);
            $("#pat").html(pat);
        }
    });

    $("#freeze").click(function(){
       var inin =  $("#interestincome").val();
        $("#inin").html(inin);
        $("#interestincome").remove();
    });

    var doc = new jsPDF();
    var specialElementHandlers = {
        '#editor': function (element, renderer) {
            return true;
        }
    };


</script>