<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=1.3
 *
 * @category    Gc
 * @package     Config
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

if (isset($_POST['setUserNameOrder'])) {
    if (isset($_POST['setUserNameOrder']) && $_POST['setUserNameOrder'] == 1 ) {
        $_SESSION['setUserNameOrder'] = 1;
    }elseif(isset($_POST['setUserNameOrder']) && $_POST['setUserNameOrder'] == 2){
        $_SESSION['setUserNameOrder'] = 2;
    }
    if (isset($_SESSION['setUserFNameOrder'])||isset($_SESSION['setUserLNameOrder'])||isset($_SESSION['setUserEmailOrder'])){
        unset($_SESSION['setUserFNameOrder']);
        unset($_SESSION['setUserLNameOrder']);
        unset($_SESSION['setUserEmailOrder']);
    }
}
if(isset($_POST['setUserFNameOrder'])){
    if (isset($_POST['setUserFNameOrder']) && $_POST['setUserFNameOrder'] == 1 ) {
        $_SESSION['setUserFNameOrder'] = 1;
    }elseif(isset($_POST['setUserFNameOrder']) && $_POST['setUserFNameOrder'] == 2){
        $_SESSION['setUserFNameOrder'] = 2;
    }
    if (isset($_SESSION['setUserNameOrder'])||isset($_SESSION['setUserLNameOrder'])||isset($_SESSION['setUserEmailOrder'])){
        unset($_SESSION['setUserNameOrder']);
        unset($_SESSION['setUserLNameOrder']);
        unset($_SESSION['setUserEmailOrder']);
    }
}
if(isset($_POST['setUserLNameOrder'])){
    if (isset($_POST['setUserLNameOrder']) && $_POST['setUserLNameOrder'] == 1 ) {
        $_SESSION['setUserLNameOrder'] = 1;
    }elseif(isset($_POST['setUserLNameOrder']) && $_POST['setUserLNameOrder'] == 2){
        $_SESSION['setUserLNameOrder'] = 2;
    }
    if (isset($_SESSION['setUserNameOrder'])||isset($_SESSION['setUserFNameOrder'])||isset($_SESSION['setUserEmailOrder'])){
        unset($_SESSION['setUserNameOrder']);
        unset($_SESSION['setUserFNameOrder']);
        unset($_SESSION['setUserEmailOrder']);
    }
}
if(isset($_POST['setUserEmailOrder'])){
    if (isset($_POST['setUserEmailOrder']) && $_POST['setUserEmailOrder'] == 1 ) {
        $_SESSION['setUserEmailOrder'] = 1;
    }elseif(isset($_POST['setUserEmailOrder']) && $_POST['setUserEmailOrder'] == 2){
        $_SESSION['setUserEmailOrder'] = 2;
    }
    if (isset($_SESSION['setUserNameOrder'])||isset($_SESSION['setUserFNameOrder'])||isset($_SESSION['setUserLNameOrder'])){
        unset($_SESSION['setUserNameOrder']);
        unset($_SESSION['setUserFNameOrder']);
        unset($_SESSION['setUserLNameOrder']);
    }
}

$paginatorFre = new \Zend\Paginator\Paginator(new \Zend\Paginator\Adapter\ArrayAdapter($this->userFre));
$paginatorFre->setItemCountPerPage(20);
$paginatorFre->setCurrentPageNumber(empty($_GET['page']) ? 1 : (int)$_GET['page']);

?>
<?php
    $qus = 'fre';
    if (isset($_GET['q']) && $_GET['q'] == 'emp') {
        $qus = 'emp';
    }elseif(isset($_GET['q']) && $_GET['q'] == 'adm'){
        $qus = 'adm';
    }

    if (isset($_GET['c']) && $_GET['c'] != '') {
        $cat = $_GET['c'];
    }else{
        $cat = 1;
    }
?>
<div id="tabs">
  <!--  <div class="qus-tabs">
        <ul>
            <li class="<?php // if ($qus == 'fre') {echo "active";} ?>"><a href="<?php // echo $this->serverUrl() ?>/admin/config/user/finance?q=fre">Freelancer</a></li>
            <li class="<?php // if ($qus == 'emp') {echo "active";} ?>"><a href="<?php // echo $this->serverUrl() ?>/admin/config/user/finance?q=emp">Employer</a></li>
            <li class="<?php // if ($qus == 'adm') {echo "active";} ?>"><a href="<?php // echo $this->serverUrl() ?>/admin/config/user/finance?q=adm">Admin</a></li>
        </ul>
    </div>-->

         <div id="fre-tab">
            <div class="cat-tabs">
                <ul>
                    <?php foreach ($this->professions as $profession) { ?>
                        <li class="<?php if ($cat == $profession->getId()) {echo "active";} ?>"><a href="<?php echo $this->serverUrl() ?>/admin/config/user/finance?q=fre&c=<?php echo $profession->getId()  ?>"><?php echo $profnm = $profession->getName() ?></a></li>
                    <?php } ?>
                </ul>
            </div>
            <?php if(!empty($paginatorFre)): ?>
            <table class="table clickable table-striped table-hover">
                <colgroup>
                    <col width="20%">
                    <col width="20%">
                    <col width="20%">
                    <col width="20%">
                    <col width="10%">
                    <col width="1%">
                </colgroup>
                <thead>
                    <tr>
                         <th><?php if(isset($_SESSION['setUserNameOrder']) && $_SESSION['setUserNameOrder'] == 2){ ?><a href="javascript:void(0);" onclick="changeUserNameOrder(10);"><?php echo $this->escapeHtml($this->translate('Login')); ?></a><?php }else{?><a href="javascript:void(0);" onclick="changeUserNameOrder(2);"><?php echo $this->escapeHtml($this->translate('Login')); ?></a><?php } ?></th>
                        <th><?php if(isset($_SESSION['setUserFNameOrder']) && $_SESSION['setUserFNameOrder'] == 2){ ?><a href="javascript:void(0);" onclick="changeUserFNameOrder(10);"><?php echo $this->escapeHtml($this->translate('Firstname')); ?></a><?php }else{?><a href="javascript:void(0);" onclick="changeUserFNameOrder(2);"><?php echo $this->escapeHtml($this->translate('Firstname')); ?></a><?php } ?></th>
                        <th><?php if(isset($_SESSION['setUserLNameOrder']) && $_SESSION['setUserLNameOrder'] == 2){ ?><a href="javascript:void(0);" onclick="changeUserLNameOrder(10);"><?php echo $this->escapeHtml($this->translate('Lastname')); ?></a><?php }else{?><a href="javascript:void(0);" onclick="changeUserLNameOrder(2);"><?php echo $this->escapeHtml($this->translate('Lastname')); ?></a><?php } ?></th>
                        
                        <th><?php if(isset($_SESSION['setUserEmailOrder']) && $_SESSION['setUserEmailOrder'] == 2){ ?><a href="javascript:void(0);" onclick="changeUserEmailOrder(10);"><?php echo $this->escapeHtml($this->translate('Email')); ?></a><?php }else{?><a href="javascript:void(0);" onclick="changeUserEmailOrder(2);"><?php echo $this->escapeHtml($this->translate('Email')); ?></a><?php } ?></th>
                        <th class="text-center">Profit&nbsp;and&nbsp;loss</th>
                        <th class="text-center">Balance&nbsp;sheet</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    /*echo "<pre>";
                    print_r($this->users);
                    echo "</pre>";*/

                    foreach ($paginatorFre as $user):  ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($user->getLogin()); ?><?php echo $this->escapeHtml($user->getId()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getFirstname()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getLastname()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
                            <td class="text-center">
                                <a href="<?php echo $this->url('config/user/finance/profitloss', array('id' => $user->getId())); ?>" class="btn btn-xs btn-block btn-info">Profit and loss</a>
                               </td>
                            <td>
                                <a href="<?php echo $this->url('config/user/finance/balancesheet', array('id' => $user->getId())); ?>" class="btn btn-xs btn-block btn-info">Balance sheet</a>
                            </td>
                        </tr>
                    <?php  endforeach; ?>
                        <?php if(count($paginatorFre)==0){ ?>
                            <tr>
                                <td colspan="6" align="center">No record found in..!</td>
                             </tr>
                        <?php }?>
                </tbody>
            </table>
            <div class="pagination">
                 <?php echo $this->paginationControl($paginatorFre, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/user/finance?q=fre&c='.$cat));?>
            </div>
            <?php
                else:
                    echo "<h3>No record found..!</h3>";
                endif;
            ?>  
        </div>



<script type="text/javascript">    
    Gc.initTableList();
    function changeUserNameOrder(order){
        $.ajax({
            'url'   :'/admin/config/user',
            'type'  :'POST',
            'data'  :{'setUserNameOrder':order},
            'success':function(result){ //alert('question'+result);
                //alert("Order change");
                location.reload();
            }
        });
    }
    function changeUserFNameOrder(order){
        $.ajax({
            'url'   :'/admin/config/user',
            'type'  :'POST',
            'data'  :{'setUserFNameOrder':order},
            'success':function(result){ //alert('question'+result);
                //alert("Order change");
                location.reload();
            }
        });
    }
    function changeUserLNameOrder(order){
        $.ajax({
            'url'   :'/admin/config/user',
            'type'  :'POST',
            'data'  :{'setUserLNameOrder':order},
            'success':function(result){ //alert('question'+result);
                //alert("Order change");
                location.reload();
            }
        });
    }
    function changeUserEmailOrder(order){
        $.ajax({
            'url'   :'/admin/config/user',
            'type'  :'POST',
            'data'  :{'setUserEmailOrder':order},
            'success':function(result){ //alert('question'+result);
                //alert("Order change");
                location.reload();
            }
        });
    }
</script>
