<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>


<script type="text/javascript">
    $(document).ready(function(){
        $('#jobTable').DataTable({
            "lengthMenu": [[50, 100, 150, -1], [50, 100, 150, "All"]],
            "order": [[ 0, "desc" ]],
            "columnDefs": [ {"targets": [6,7,8,9], "orderable": false, }],
        });
    });
</script>
<?php
    $paginator = new \Zend\Paginator\Paginator(new \Zend\Paginator\Adapter\ArrayAdapter($this->jobs));
    $paginator->setItemCountPerPage(1000000000000);
    $paginator->setCurrentPageNumber(empty($_GET['page']) ? 1 : (int)$_GET['page']);
    //$paginator = $this->jobs;
    use Gc\User\Professional\Collection as ProfessionalCollection;
    use Gc\User\Collection as UserCollection;
    use GcFrontend\Controller\FunctionsController as FunctionsController;
    use Gc\Registry;
    use GcFrontend\Controller\DbController as DbController;
    $categoryCollection = new ProfessionalCollection();
    $categories = $categoryCollection->getProfessionals();
    $userCollection = new UserCollection();
    $functionsController = new FunctionsController();
    $dbConfig = new DbController();
    $adapter = $dbConfig->locumkitDbConfig();
    //$users = $userCollection->getUsers();

    $configGet = Registry::get('Application')->getServiceManager()->get('ViewHelperManager')->get('Config');
    $currency = $configGet->get('site_currency');
?>
<!-- <div class="row filter-job">
    <form method="get" action="/admin/config/user/job/search">
        <div class="col-md-3">
            <select name="jobId">
                <option value="">Select job id</option>
                <?php foreach ($this->jobs as $key => $value) { ?>
                    <option value="<?php echo $value->getJobId() ?>"><?php echo $value->getJobId() ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="col-md-3">
            <select name="catId">
                <option value="">Select job category</option>
                <?php foreach ($categories as $key => $value) { ?>
                    <option value="<?php echo $value->getId(); ?>"><?php echo $value->getName(); ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="col-md-3">
            <select name="uId">
                <option value="">Select Employer Email</option>
                <?php 
                    foreach ($users as $key => $value) { 
                        if ($value->getUserAclRoleId() == 3) {
                ?>
                    <option value="<?php echo $value->getId()?>"><?php echo $value->getEmail()?></option>
                <?php } } ?>
            </select>
        </div>
        <div class="col-md-3">
            <input type="submit" value="Search">
        </div>
    </form>
</div> -->

<br/>
<table id="jobTable" class="table clickable table-striped table-hover">
    <colgroup>
        <col width="5%">
        <col width="10%">
        <col width="10%">
        <col width="10%">
        <col width="10%">
        <col width="11%">
        <col width="13%">
        <col width="10%">
        <col width="13%">
        <col width="8%">
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->escapeHtml($this->translate('Id')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Title')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Category')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Date')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Rate')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Employer Id')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Employer Name')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Locum Id')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Locum Name')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Status')); ?></th>
            <!-- <th class="no-sort"><?php echo $this->escapeHtml($this->translate('Action')); ?></th> -->
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($paginator as $job):  
        ?>
            <tr>
                <td data-order="<?php echo $this->escapeHtml($job->getJobId()); ?>">#<?php echo $this->escapeHtml($job->getJobId()); ?></td>
                <td><?php echo $this->escapeHtml($job->getJobTitle()); ?></td>
                <?php 
                    $catName = '';
                    foreach ($categories as $key => $value) {
                        if ($value->getId() == $job->getCatId()) {
                            $catName = $value->getName();
                        }
                    }
                ?>
                <td><?php echo $this->escapeHtml($catName); ?></td>
                <td data-order="<?php echo date('Y-m-d', strtotime(str_replace('/', '-', $job->getJobDate()))); ?>"><?php echo $this->escapeHtml($job->getJobDate()); ?></td>
                <td data-order="<?php echo $this->escapeHtml($job->getJobRate()); ?>"><?php echo $currency.$this->escapeHtml( number_format($job->getJobRate(),2)); ?></td>
                <?php 
                    $eName = '';
                    $eEmail = '';
                    $userInfo = $functionsController->getUserInfo($job->getEId(),$adapter); 
                    if (empty($userInfo)) {
                        $userInfo = $functionsController->getDeleteUserInfo($job->getEId(),$adapter); 
                    }
                    if ($userInfo->firstname && $userInfo->lastname) {
                        $eName = $userInfo->firstname.' '.$userInfo->lastname;
                    }else{
                        $eName = $userInfo->user_name;
                    }
                    if ($userInfo->email) {
                        $eEmail = $userInfo->email;
                    }else{
                        $eEmail = $userInfo->user_email;
                    }
                    $eId = $job->getEId();                    
                ?>                
                <td style="text-align:center;"><?php echo $this->escapeHtml($eId); ?></td>
                <td><?php echo $this->escapeHtml($eName); ?></td>
                <td data-order="<?php echo $this->escapeHtml($job->freId); ?>"><?php echo $this->escapeHtml($job->freId); ?></td>
                <td><?php echo $this->escapeHtml($job->freName); ?></td>
                <td><?php 
                        
                        switch ($job->getJobStatus()) {
                            case 1:
                                echo '<sapn style="color: green;   font-weight: 700;">Open</span>'; 
                                break;
                            case 2:
                                echo '<sapn style="color: red;   font-weight: 700;">Close</span>'; 
                                break;
                            case 3:
                                echo '<sapn style="color: red;   font-weight: 700;">Disable</span>'; 
                                break;
                            case 4:
                                echo '<sapn style="color: green;   font-weight: 700;">Accepted</span>'; 
                                break;
                            case 5:
                                echo '<sapn style="color: #00A9E0;   font-weight: 700;">Completed</span>'; 
                                break;
                            case 6:
                                echo '<sapn style="color: #F0AD4E;   font-weight: 700;">Freeze</span>'; 
                                break;
                            case 8:
                                echo '<sapn style="color: #ff8200;   font-weight: 700;">Cancel</span>'; 
                                break;

                        }
                        
                    ?></td>
                <!-- <td>
                    <a href="<?php echo $this->url('config/user/job/view', array('id' => $job->getJobId())); ?>" class="edit-line" alt="View" style="font-size: 18px;color: #00A9E0;display: block;  float: left;margin-right: 8px;">
                       <i class="glyphicon glyphicon-eye-open"></i>
                    </a>
                    &nbsp;
                    <a href="<?php echo $this->url('config/user/job/delete', array('id' => $job->getJobId())); ?>" class="delete-line" style="display: block;  float: left;">
                        <img src="<?php echo $this->cdnBackend('backend/images/icones/delete.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Delete')); ?>">
                    </a>
                </td> -->
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="pagination">
     <?php echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/user/job'));?>
</div>
<script type="text/javascript">
    Gc.initTableList();
</script>
<style type="text/css">
    div#jobTable_wrapper {
        background: #f0f0f0;
    }
    div#jobTable_filter, div#jobTable_length {
        padding: 20px 15px;
    }
    table#jobTable {
        background: #fff;
        border-top: 1px solid;
    }
    div#jobTable_info{
        padding: 15px;
    } 
    div#jobTable_paginate {
        padding: 10px 15px;
    }
</style>