    <div class="col-md-9" style="padding-right: 15px;padding-bottom: 25px;" >
        <div class="row">
            <div class="contents white-bg">
                <section class="add_item text-left pb30">
                    <div class="col-md-12 pad0">
                        <div class="text-center finance-page-head" style="font-size:20pt">LOCAL AREA PROTOCOLS

                        </div>
                    </div>
                    <div class="col-md-12 pad0">
                        <div  class="add_item_form form-inline">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <label for="area" style="padding-top: 6px;">Area</label>
                                    </div>
                                    <div class="col-md-7">
                                        <input class="form-control" name="area" id="area" placeholder="Please enter area name" required>
                                    </div>
                                </div>
                                <div id="error_div" class="has-error"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <label for="extended_services" style="padding-top: 6px;">Extended Services</label>
                                    </div>
                                    <div class="col-md-7">
                                        <input class="form-control" name="extended_services" id="extended_services" placeholder="Please enter extended services in place" required>
                                    </div>
                                </div>
                                <div id="error_div" class="has-error"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <label for="emergency_department" style="padding-top: 6px;">Emergency Department</label>
                                    </div>
                                    <div class="col-md-7">
                                        <input class="form-control" name="emergency_department" id="emergency_department" placeholder="Please enter details of emerg dept." required>
                                    </div>
                                </div>
                                <div id="error_div" class="has-error"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <label for="routine_referrals" style="padding-top: 6px;">Routine Referrals</label>
                                    </div>
                                    <div class="col-md-7">
                                        <input class="form-control" name="routine_referrals" id="routine_referrals" placeholder="Details of referral pathways in place" required>
                                    </div>
                                </div>
                                <div id="error_div" class="has-error"></div>
                            </div>
                            

                            <div class="col-md-12" style="padding-top: 20px;">
                                <div class="form-group text-center">
                                    <button id="submit" class="read-common-btn grad_btn" style="display: inline">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

        <script type="text/javascript">
            

            $('#submit').click(function(){
                var postdata = {
                    'area' : $('#area').val(),
                    'extended_services' : $('#extended_services').val(),
                    'emergency_department' : $('#emergency_department').val(),
                    'routine_referrals' : $('#routine_referrals').val()
                }

                $.ajax({
                    url : '<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/add4post',
                    type: 'POST',
                    dataType: 'JSON',
                    async: true,
                    data: {'data': postdata},
                    beforeSend : function() {
                        /* Logic before ajax request sent */
                    },
                    success: function(data){
                        if (data.success && data.success == 1) window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list4');
                        else confirm('error');
                    },
                    error : function(xhr, textStatus, errorThrown) {
                        if (xhr.status === 0) {
                            alert('Not connect.\n Verify Network.');
                        } else if (xhr.status == 404) {
                            alert('Requested page not found. [404]');
                        } else if (xhr.status == 500) {
                            alert('Server Error [500].');
                        } else if (errorThrown === 'parsererror') {
                            alert('Requested JSON parse failed.');
                        } else if (errorThrown === 'timeout') {
                            alert('Time out error.');
                        } else if (errorThrown === 'abort') {
                            alert('Ajax request aborted.');
                        } else {
                            alert('There was some error. Try again.');
                        }
                    }
                });
            });
            $(document).ready(function() {
                $('#questionaire1_listbtn').click(function(){
                    window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list1');
                });
                $('#practice_matters').click(function(){
                    window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list2');
                });
                $('#daytoday_practice').click(function(){
                    window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list3');
                });
                $('#localarea_protocols').click(function(){
                    window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list4');
                });
                $('#practice_checklist').click(function(){
                    window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list5/1');
                });
                $('#follow_up').click(function(){
                    window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list6');
                });
            })


        </script>

</html>