<style type="text/css">
    tr td{
        white-space: nowrap;
        max-width: 80px;
        overflow: hidden;
        text-overflow: ellipsis;
    }
    th{
        padding-left: 15px !important;
        padding-right: 15px !important;
    }
</style>
    <div class="col-md-9 pad0 finacedetable" style="padding-right: 0px !important;">
            <section id="Income-tansc" class="Income-tansc"  style="width:113%">
                    <div class="col-md-12 col-sm-12 income">
                        <div class="col-md-12 pad0 head_box">
                            <span>
                                <h1 class="mar0 text-none" id="register_head_blue" style="display: inline-block;padding-top: 15px;">
                                    LOCAL AREA PROTOCOLS - ie referral pathways, phone numbers, etc.
                                </h1>    
                            </span>
                             <div class="pad0" style="display: inline;">
                                <a href="<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/add4" class="read-common-btn grad_btn pull-right" style="height:38px;width:142px;">
                                    ADD NEW
                                </a>
                            </div>
<!--                             <select name="" class="form-control margin-bottom" required="" style="width:130px; display: inline-block; float:right;margin-top: 13px;margin-right: 20px;">
                                <option value="0" selected="">Latest</option>
                                <option value="1">Oldest</option>
                                <option value="2">Completed</option>
                                <option value="3">In progress</option>
                            </select> -->
                        </div>
                        <div class="col-md-12 pad0">
                                    <table class="table table-striped table-bordered" style="width:100%" id="questionaire_list4">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Area</th>
                                                <th>Extended Service</th>
                                                <th>Emergency Department</th>
                                                <th>Routine referrals</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $no = 1; ?>
                                            <?php foreach ($q_lists as $item){ ?>
                                            <tr>
                                                <td><?php echo $no; $no++; ?></td>
                                                <td><?php echo $item['area'] ?></td>
                                                <td><?php echo $item['extended_services'] ?></td>
                                                <td><?php echo $item['emergency_department'] ?></td>
                                                <td><?php echo $item['routine_referrals'] ?></td>
                                                <td>
                                                    <a href="<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/edit4/<?php echo 
                                                    $item['id'] ?>" class="btn btn-xs btn-info">
                                                        <i class="fa fa-fw fa-edit"></i>
                                                    </a>
                                                    <button type="button" class="btn btn-xs btn-danger" name="in_data_delete" value="in_data_delete" onclick="deletebyid(<?php echo $item['id']?>)">
                                                        <i class="fa fa-fw fa-close"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
               </section>
    </div>

    <script type="text/javascript">

        $(document).ready(function() {
            $('#questionaire_list4').DataTable();
            $('#questionaire1_listbtn').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list1');
            });
            $('#practice_matters').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list2');
            });
            $('#daytoday_practice').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list3');
            });
            $('#localarea_protocols').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list4');
            });
            $('#practice_checklist').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list5/1');
            });
            $('#follow_up').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list6');
            });
        });

        function deletebyid(id){
            var question = confirm ( "Are you sure to delete this questionaire?") 
            if (question != "0")
            {
                $.ajax({
                    url : '<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/delete4post',
                    type: 'POST',
                    dataType: 'JSON',
                    async: true,
                    data: {'id' : id},
                    beforeSend : function() {
                        /* Logic before ajax request sent */
                    },
                    success: function(data){
                        //console.log(data);
                        if (data.success && data.success == 1) window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list4');
                        else confirm('error');
                    },
                    error : function(xhr, textStatus, errorThrown) {
                        if (xhr.status === 0) {
                            alert('Not connect.\n Verify Network.');
                        } else if (xhr.status == 404) {
                            alert('Requested page not found. [404]');
                        } else if (xhr.status == 500) {
                            alert('Server Error [500].');
                        } else if (errorThrown === 'parsererror') {
                            alert('Requested JSON parse failed.');
                        } else if (errorThrown === 'timeout') {
                            alert('Time out error.');
                        } else if (errorThrown === 'abort') {
                            alert('Ajax request aborted.');
                        } else {
                            alert('There was some error. Try again.');
                        }
                    }
                });
            }
        }
    </script>