<style type="text/css">
    tr td{
        white-space: nowrap;
        max-width: 80px;
        overflow: hidden;
        text-overflow: ellipsis;
    }
    th{
        padding-left: 15px !important;
        padding-right: 15px !important;
    }
</style>
    <div class="col-md-9 pad0 finacedetable" style="padding-right: 0px !important;">
            <section id="Income-tansc" class="Income-tansc" style="width:113%">
                    <div class="col-md-12 col-sm-12 income">
                        <div class="col-md-12 pad0 head_box">
                            <span>
                                <h1 class="mar0 text-capitalize" id="register_head_blue" style="display: inline-block;padding-top: 15px;">INTERNAL REFERRALS AND INVESITGATION REQUESTS
                                </h1>   
      <h1 class="mar0 text-none" id="register_head_blue" style="display: inline-block;padding-top: 1px;">Use this section to monitor internal referrals and requests for repeat procedures
                                </h1>    
                            </span>
                             <div class="pad0" style="display: inline;">
                                <a href="<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/add1" class="read-common-btn grad_btn pull-right" style="height:38px;width:142px;">
                                    ADD NEW
                                </a>
                            </div>
                        </div>
                        <div class="col-md-12 pad0">
                                    <table class="table table-striped table-bordered" style="width:100%" id="questionaire_list1">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Practice Name</th>
                                                <th>Date</th>
                                                <th>Patient ID</th>
                                                <th>Referred to</th>
                                                <th>Issue</th>
                                                <th>Action required</th>
                                                <th>Reminder Date Time</th>
                                                <th>Notes</th>
                                                <th>Completed</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $no = 1; ?>
                                            <?php foreach ($q_lists as $item){ ?>
                                            <tr>
                                                <td><?php echo $no; $no++;  ?></td>
                                                <td><?php echo $item['practice_name'] ?></td>
                                                <td><?php 
                                                    if ($item['date'] != '')  
                                                    {
                                                        $date = date_create($item['date']);
                                                        echo date_format($date,"j/n/Y");   
                                                    }
                                                 ?></td>
                                                <td><?php echo $item['patient_id']?></td>
                                                <td><?php echo $item['referred_to'] ?></td>
                                                <td><?php echo $item['issue_hand'] ?></td>
                                                <td><?php echo $item['action_required'] ?></td>
                                                <td>
                                                    <?php
                                                    if ($item['reminder_datetime'] != ''){
                                                        $date = date_create($item['reminder_datetime']);
                                                        echo date_format($date,"j/n/Y H:i");
                                                    }
                                                     ?>
                                                </td>
                                                <td><?php echo $item['notes'];  ?></td>
                                                <td><?php 
                                                    if ($item['completed_tick'] != null){
                                                        if ($item['completed_tick'] == 0) echo 'In Progress';
                                                        else echo 'Completed';
                                                    }
                                                    else echo 'In Progress'
                                                 ?></td>
                                                <td>
                                                    <a href="<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/edit1/<?php echo 
                                                    $item['id'] ?>" class="btn btn-xs btn-info">
                                                        <i class="fa fa-fw fa-edit"></i>
                                                    </a>
                                                    <button type="button" class="btn btn-xs btn-danger" name="in_data_delete" value="in_data_delete" onclick="deletebyid(<?php echo $item['id']?>)">
                                                        <i class="fa fa-fw fa-close"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                       </div>
                    </div>
               </section>
    </div>

    <script type="text/javascript">

        function deletebyid(id){
            var question = confirm ( "Are you sure to delete this questionaire?") 
            if (question != "0")
            {
                $.ajax({
                    url : '<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id; ?>/delete1post',
                    type: 'POST',
                    dataType: 'JSON',
                    async: true,
                    data: {'id' : id},
                    beforeSend : function() {
                        /* Logic before ajax request sent */
                    },
                    success: function(data){
                        //console.log(data);
                        if (data.success && data.success == 1) window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id  ?>/list1');
                        else confirm('error');
                    },
                    error : function(xhr, textStatus, errorThrown) {
                        if (xhr.status === 0) {
                            alert('Not connect.\n Verify Network.');
                        } else if (xhr.status == 404) {
                            alert('Requested page not found. [404]');
                        } else if (xhr.status == 500) {
                            alert('Server Error [500].');
                        } else if (errorThrown === 'parsererror') {
                            alert('Requested JSON parse failed.');
                        } else if (errorThrown === 'timeout') {
                            alert('Time out error.');
                        } else if (errorThrown === 'abort') {
                            alert('Ajax request aborted.');
                        } else {
                            alert('There was some error. Try again.');
                        }
                    }
                });
            }
        }

        $(document).ready(function() {
            $('#questionaire_list1').DataTable();

            $('#questionaire1_listbtn').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list1');
            });
            $('#practice_matters').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list2');
            });
            $('#daytoday_practice').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list3');
            });
            $('#localarea_protocols').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list4');
            });
            $('#practice_checklist').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list5/1');
            });
            $('#follow_up').click(function(){
                window.location.replace('<?php echo $this->basePath(); ?>/questionaire/<?php echo $user_id ?>/list6');
            });

        });
    </script>