<?php
    date_default_timezone_set('Europe/London');
	use Gc\Registry;
    use Gc\User\Finance\Collection as FinanceCollection;
    use Gc\User\Finance\Expense\Collection as ExpenseCollection;
    use GcFrontend\Controller\JobmailController as MailController;
	use GcFrontend\Controller\EndecryptController as Ecryption;
    use GcFrontend\Controller\DbController as DbController;
    use Gc\User\Feedback\Collection as FeedbackCollection;
  use GcFrontend\Controller\PackagePrivilegesController;
  $packagePrivilegesController    = new PackagePrivilegesController();
    $encrypt 			= new Ecryption();
	$mailController 	= new MailController();
    $financeCollection  = new FinanceCollection();
    $expenseCollection  = new ExpenseCollection();
    $feedbackCollection 	= new FeedbackCollection();
	$dbConfig 			= new DbController();
    $adapter 			= $dbConfig->locumkitDbConfig();
    $currentDate 	    = date("Y-m-d ");
    $notfDate           = date('Y-m-d', strtotime($currentDate .' -2 days'));


    /* Get job reminder dates information */
   /* $sqlFinanceInfo = "SELECT * from user_finance WHERE DATE(STR_TO_DATE(created_at, '%Y-%m-%d')) = '$notfDate'"; */
   
      echo $sqlFinanceInfo = "SELECT inf.fre_id as fre_id , inf.emp_id as emp_id , inf.job_date as jobdate  , inf.job_id as jobid , inf.job_rate AS job_rate , SUM(exf.cost) AS cost FROM finance_income_table AS inf JOIN finance_expense_table AS exf ON inf.job_id = exf.job_id where date(inf.job_date) = '$notfDate' and inf.job_type = '1' and inf.income_type = '1' GROUP BY inf.job_id";
      		
    $financeInfoData = $adapter->query($sqlFinanceInfo, $adapter::QUERY_MODE_EXECUTE);
    $financeInfoArray = $financeInfoData->toArray();
    
 
echo '<pre>';
print_r($financeInfoArray);
echo '</pre>';

    foreach ($financeInfoArray as $key => $financeInfo) {
    	$jobId 		= $financeInfo['jobid'];
    	$freId 		= $financeInfo['fre_id'];
    	$empId 		= $financeInfo['emp_id'];
    	$income 	= $financeInfo['job_rate'];
    	$expense 	= $financeInfo['cost'];   
        $empFeedback= $feedbackCollection->getFeedbackEmployerById($empId, $jobId);   
        $freFeedback= $feedbackCollection->getFeedbackFreelancerById($freId, $jobId);

        if($packagePrivilegesController->getCurrentPackagePrivilegesResources('job_reminders',$freId,$adapter) == 1){
                $mailController->sendFreJobSummaryNotification($freId,$jobId,$income,$expense,$freFeedback,$adapter); 
        }
        $mailController->sendEmpJobSummaryNotification($empId,$freId,$jobId,$income,$expense,$empFeedback,$adapter);  
    }