<?php
    date_default_timezone_set('Europe/London');
  use GcFrontend\Controller\DbController as DbController;
  $dbConfig = new DbController();
  $adapter = $dbConfig->locumkitDbConfig();
   use Zend\Serializer\Serializer;
	use Zend\Db\Sql\Sql;
	use Zend\Db\TableGateway\TableGateway;
	use Gc\User\Packageresource\Model;
	use GcFrontend\Controller\FunctionsController as FunctionsController;
	$functionsController = new FunctionsController();
	if(isset($_SESSION['user_id']) && $_SESSION['user_id']!=''){
		$uid=$_SESSION['user_id'];
    }
    $request = $this->getRequest();
    if($request->isPost())
    {
        $post     = $request->getPost();
		$store_id = $post->get('store_id');
		$add_st   = $post->get('add_st'); // add store variable 
		// add store
		if($add_st && $add_st==1){
			//employer store list
			$emp_store_name = str_replace("'", '', $post->get('emp_store_name'));
			$emp_store_address =str_replace("'", '', $post->get('emp_store_address'));
			$emp_store_region =str_replace("'", '', $post->get('emp_store_region'));
			$emp_store_zip =$post->get('emp_store_zip');
			$emp_start_time =$post->get('job_start_time');
			$emp_end_time =$post->get('job_end_time');
			$emp_lunch_time =$post->get('job_lunch_time');
			$emp_language =$post->get('emp_language');
			$emp_store_result = array();
			foreach ( $emp_store_name as $key=>$name ) {
				$emp_store_result[] = array( 
					'emp_store_name' => $name, 
					'emp_store_address' => $emp_store_address[$key], 
					'emp_store_region' => $emp_store_region[ $key ], 
					'emp_store_zip' => $emp_store_zip[ $key ],
					'emp_language' => $emp_language[ $key ],
					'start_time'=> $functionsController->setTime($emp_start_time,$key),
					'end_time' 	=> $functionsController->setTime($emp_end_time,$key),
					'lunch_time'=> $functionsController->setTime($emp_lunch_time,$key)  
				);
			}
			//print_r($emp_store_result);
			// employer store list insert query
			if(isset($emp_store_result)){
				foreach($emp_store_result as $emp_store){
				$sql_emp_store="insert into employer_store_list (emp_id,emp_store_name,emp_store_address,emp_store_region,emp_store_zip,store_start_time,store_end_time,store_lunch_time,emp_language,date_added) values('".$uid."','".$emp_store['emp_store_name']."','".$emp_store['emp_store_address']."','".$emp_store['emp_store_region']."','".$emp_store['emp_store_zip']."','".$emp_store['start_time']."','".$emp_store['end_time']."','".$emp_store['lunch_time']."','".$emp_store['emp_language']."',NOW())";
				$resultsemp = $adapter->query($sql_emp_store, $adapter::QUERY_MODE_EXECUTE);
				}
			  $this->flashMessenger()->addSuccessMessage('Store added');
			}
			
		} else{
			foreach($store_id as $storearr){
				$emp_store_name=$post->get('emp_store_name_'.$storearr);
				$emp_store_address=$post->get('emp_store_address_'.$storearr);
				$emp_store_region=$post->get('emp_store_region_'.$storearr);
				$emp_store_zip=$post->get('emp_store_zip_'.$storearr);
				$emp_language=$post->get('emp_language_'.$storearr);
				$emp_start_time =$functionsController->setTime($post->get('job_start_time_'.$storearr.'_'),0);
				$emp_end_time =$functionsController->setTime($post->get('job_end_time_'.$storearr.'_'),0);
				$emp_lunch_time =$functionsController->setTime($post->get('job_lunch_time_'.$storearr.'_'),0);
				
				
				// update query for employer_store_list table
				$sqlString_update="update employer_store_list set emp_store_name='".$emp_store_name."',emp_store_address='".$emp_store_address."' ,emp_store_region='".$emp_store_region."', emp_store_zip='".$emp_store_zip."',store_start_time='".$emp_start_time."',store_end_time='".$emp_end_time."',store_lunch_time='".$emp_lunch_time."', emp_language='".$emp_language."' where emp_id='".$uid."' and emp_st_id='".$storearr."'";	
				$results_get = $adapter->query($sqlString_update, $adapter::QUERY_MODE_EXECUTE);
			}
			
			$this->flashMessenger()->addSuccessMessage('Information updated');
		}
		
        $this->redirect()->toUrl('/manage-store');
        return TRUE;
	}

?>