<?php
    date_default_timezone_set('Europe/London');
    use Zend\Db\Sql\Sql;
    use Zend\Db\TableGateway\TableGateway;
    use Zend\Db\Sql\Where;
    use Gc\Registry;
    use Gc\User\Collection as UserCollection;
    use Gc\User\UserExtraInfo as UserExtraInfo;
    use GcConfig\Controller\ReportController as ReportController;
    use GcFrontend\Controller\DbController as DbController;
    use Gc\User\PackageRateReport;
    $userProfessional = new Gc\User\Professional\Collection();
    $userCollection = new UserCollection();
    $dbConfig = new DbController();
    $adapter = $dbConfig->locumkitDbConfig();
    $sql = new Sql($adapter);
    $select = $sql->select();
    $select1 = $sql->select();
    //execute the SQL query and return records
    $configGet = Registry::get('Application')->getServiceManager()->get('ViewHelperManager')->get('Config');
    $currency = str_replace(chr(194),"",$configGet->get('site_currency'));
    $type = $_GET['type'];

    /* User Report */ 
    if ($type == 'Block_User') {
        $startdate = isset($_GET['startdate']) ? $_GET['startdate'] : '';
        $enddate = (isset($_GET['enddate']) && $_GET['enddate'] != '') ? $_GET['enddate'] : date('Y-m-d');
        $redirect_url = '';
        $select->from('user');
        if ($startdate != '' &&  $enddate != '') {            
            $select->where("active = '2' AND updated_at BETWEEN '$startdate' AND '$enddate' ");
            $select->order('id DESC');
            $redirect_url = "startdate=$startdate&enddate=$enddate";
            
        }else{
            $select->where("active = '2'");
            $select->order('id DESC');
        }
        
        $statement = $sql->prepareStatementForSqlObject($select);
        $results = $statement->execute();        
        $allrecord = $results->getResource()->fetchAll();
        
        if (empty($allrecord)) {             
            exit();
        } 
        //fetch tha data from the database
                 
        // Write data to file
        $newArray = '';
        $flag = false;
        foreach ($allrecord as $key => $value) {
            $newArray[] = array(
                    'User ID'        =>  $value['id'],                    
                    'Last Name'  =>  $value['lastname'],
                    'First Name' =>  $value['firstname'],
                    'Email'     =>  $value['email'],                 
                );
        }
            
            //exit();
        $filename =  $type.'_Report_'.date('Y-m-d').'.xls'; // File Name
         
        // Download file
        header("Content-Type: application/xls");    
        header("Content-Disposition: attachment; filename=\"$filename\"");  
        header("Pragma: no-cache"); 
        header("Expires: 0");
        $k = 0;
        $count = count($newArray);            
        foreach ($newArray as $key => $value) {  
            if(!$flag) {
                // display field/column names as first row
                echo implode("\t", array_keys($value)) . "\r\n";
                $flag = true;
            }
            echo implode("\t", array_values($value)) . "\r\n";  
            $k++;
            if ($k >= $count) {
                exit();
            }
        }
        
    }elseif ($type == 'Package_User') {
        $package_name = $_GET['pkg'];

        $select->from('user');
        if ($package_name) {            
            $select->where("user_acl_package_id = '$package_name' AND user_acl_role_id = '2'");
        }
        
        $statement = $sql->prepareStatementForSqlObject($select);
        $results = $statement->execute();        
        $allrecord = $results->getResource()->fetchAll();

        $select1->from('user_acl_package');
        $select1->where("id = '$package_name'");
        $statement1 = $sql->prepareStatementForSqlObject($select1);
        $results1 = $statement1->execute();        
        $allrecord1 = $results1->getResource()->fetchAll();
        
        if (empty($allrecord1) || empty($allrecord)) { 
            ?>
                <script type="text/javascript">
                    window.location.href = "http:/ec2-18-163-113-25.ap-east-1.compute.amazonaws.com/admin/config/report/package-report?user_record=1";
                </script>  
            <?php
            exit();
        } 
        //fetch tha data from the database
                 
        // Write data to file
        $newArray = '';
        $flag = false;
        foreach ($allrecord as $key => $value) {
            if ($value['user_acl_profession_id'] != '') {
                $profInfo = $userProfessional->getProfessionalById($value['user_acl_profession_id']);
                foreach ($profInfo as $key => $profInfo) {
                    $profName = $profInfo->getName();
                }
            }
            if($value['user_acl_role_id'] == 2){
                $userType = 'Freelancer';
            }elseif ($value['user_acl_role_id'] == 3) {
                $userType = 'Employer';
            } 
            foreach ($allrecord1 as $k => $v) { 
                $pkName = $v['name'];                   
                $newArray[] = array(
                    'User Id'    =>  $value['id'],
                    'Last Name'  =>  $value['lastname'],
                    'First Name' =>  $value['firstname'],
                    'Email'      =>  $value['email'],
                    'Category'   =>  $profName,
                    'User Type'  =>  $userType,
                    'Package'    =>  $v['name'],                 
                );
            }
        }
        /*print_r($newArray) ;
        exit();*/
        $filename =  $pkName.'_Package_User_Report_'.date('Y-m-d').'.xls'; // File Name
         
        // Download file
        header("Content-Type: application/xls");    
        header("Content-Disposition: attachment; filename=\"$filename\"");  
        header("Pragma: no-cache"); 
        header("Expires: 0");
        $k = 0;
        $count = count($newArray);            
        foreach ($newArray as $key => $value) {  
            if(!$flag) {
                // display field/column names as first row
                echo implode("\t", array_keys($value)) . "\r\n";
                $flag = true;
            }
            echo implode("\t", array_values($value)) . "\r\n";  
            $k++;
            if ($k >= $count) {
                exit();
            }
        }
    }elseif($type == 'New_User') {
        $startdate = isset($_GET['startdate']) ? $_GET['startdate'] : '';
        $enddate = (isset($_GET['enddate']) && $_GET['enddate'] != '' )? $_GET['enddate'] : date('Y-m-d');

        $select->from('user');            
        if ($startdate != null && $enddate != '') {            
            $select->where("created_at BETWEEN '$startdate' AND '$enddate' AND (active < 3 ) AND ( user_acl_role_id = '2' OR user_acl_role_id = '3' )");
        }else{   
            $select->where("active < 3  AND ( user_acl_role_id = '2' OR user_acl_role_id = '3' ) ");
        }
        $select->order('created_at DESC');
        $statement = $sql->prepareStatementForSqlObject($select);
        $results = $statement->execute();        
        $allrecord = $results->getResource()->fetchAll();
        if (empty($allrecord)) { 
            ?>
                <script type="text/javascript">
                    window.location.href = "http:/ec2-18-163-113-25.ap-east-1.compute.amazonaws.com/admin/config/report/new-user-report?user_record=1";
                </script>  
            <?php
            exit();
        } 
        //fetch tha data from the database
                 
        // Write data to file
        $newArray = '';
        $flag = false;
        foreach ($allrecord as $key => $value) {
            if($value['user_acl_role_id'] == 2){
                $userType = 'Freelancer';
            }elseif ($value['user_acl_role_id'] == 3) {
                $userType = 'Employer';
            } 
            $profInfo = $userProfessional->getProfessionalById($value['user_acl_profession_id']);
            foreach ($profInfo as $key => $profInfo) {
                $profName = $profInfo->getName();
            }
            if ($value['active'] == 1) {
                $status = 'Active';    
            }elseif ($value['active'] == 2){
                $status = 'Block';
            }else{
                $status = 'Guset User';
            }
            $newArray[] = array(
                    'User Id'        =>  $value['id'], 
                    'Sign up date' =>  date('d/m/Y', strtotime($value['created_at'])),                    
                    'Lastname'  =>  $value['lastname'],
                    'Firstname' =>  $value['firstname'],
                    'Email'     =>  $value['email'],
                    'Category'  =>  $profName,
                    'User Type' =>  $userType,
                    'Status'    =>  $status,
                );
        }

            
            //exit();
        $filename =  $type.'_Report_'.date('Y-m-d').'.xls'; // File Name
         
        // Download file
        header("Content-Type: application/xls");    
        header("Content-Disposition: attachment; filename=\"$filename\"");  
        header("Pragma: no-cache"); 
        header("Expires: 0");
        $k = 0;
        $count = count($newArray);            
        foreach ($newArray as $key => $value) {  
            if(!$flag) {
                // display field/column names as first row
                echo implode("\t", array_keys($value)) . "\r\n";
                $flag = true;
            }
            echo implode("\t", array_values($value)) . "\r\n";  
            $k++;
            if ($k >= $count) {
                exit();
            }
        }
        
    }elseif($type == 'Leave_User') {
        $startdate = isset($_GET['startdate']) ? $_GET['startdate'] : '';
        $enddate = (isset($_GET['enddate']) && $_GET['enddate'] != '' )? $_GET['enddate'] : date('Y-m-d');

        $select->from('user_leavers_table');
        if ($startdate != null && $enddate != null) {            
            $select->where("created_at BETWEEN '$startdate' AND '$enddate'");
        }
        
        $statement = $sql->prepareStatementForSqlObject($select);
        $results = $statement->execute();        
        $allrecord = $results->getResource()->fetchAll();
        if (empty($allrecord)) {             
            exit();
        } 
        //fetch tha data from the database
                 
        // Write data to file
        $newArray = '';
        $flag = false;
        foreach ($allrecord as $key => $value) {
            $reason = implode(', ',unserialize($value['user_reason_to_leave']));
            $newArray[] = array(
                    'User ID'               =>  $value['uid'],   
                    'Date of leave' =>  date('d/m/Y', strtotime($value['created_at'])),                  
                    'Name'             =>  $value['user_name'],                        
                    'Email'            =>  $value['user_email'],                 
                    'Reson Of Leaving' =>  is_array($reason) ? $reason : $value['user_reason_to_leave'],                 
                );
        }
            
            //exit();
        $filename =  $type.'_Report_'.date('Y-m-d').'.xls'; // File Name
         
        // Download file
        header("Content-Type: application/xls");    
        header("Content-Disposition: attachment; filename=\"$filename\"");  
        header("Pragma: no-cache"); 
        header("Expires: 0");
        $k = 0;
        $count = count($newArray);            
        foreach ($newArray as $key => $value) {  
            if(!$flag) {
                // display field/column names as first row
                echo implode("\t", array_keys($value)) . "\r\n";
                $flag = true;
            }
            echo implode("\t", array_values($value)) . "\r\n";  
            $k++;
            if ($k >= $count) {
                exit();
            }
        }
        
    }elseif ($type == 'last_login_user') {
        $startdate = isset($_GET['startdate']) ? $_GET['startdate'] : '';
        $enddate = (isset($_GET['enddate']) && $_GET['enddate'] != '' )? $_GET['enddate'] : date('Y-m-d');
        $select->from('last_login_user');
        if ($startdate != '') {
            $select->where("last_login_at BETWEEN '$startdate' AND '$enddate'");
        }        
        $select->order("last_login_at DESC");
        $statement = $sql->prepareStatementForSqlObject($select);
        $results = $statement->execute();        
        $allrecord = $results->getResource()->fetchAll();
        $arrayLastLogin = array();
        foreach ($allrecord as $key => $lastLoginRecord) {
            $user_id = $lastLoginRecord['uid'];
            $user_record = $userCollection->getUserById($user_id);
            if (!empty($user_record)) {
                foreach ($user_record as $key => $value) {
                    if ($value->getUserAclProfessionId() != '') {
                        $profInfo = $userProfessional->getProfessionalById($value->getUserAclProfessionId());
                        foreach ($profInfo as $key => $profInfo) {
                            $profName = $profInfo->getName();
                        }
                    }
                    if($value->getUserAclRoleId() == 2){
                        $userType = 'Freelancer';
                    }elseif ($value->getUserAclRoleId() == 3) {
                        $userType = 'Employer';
                    } 
                    $newArray[] = array(
                        'Last login Date' =>  date('d-m-Y', strtotime($lastLoginRecord['last_login_at'])),
                        'User Id'    =>  $lastLoginRecord['uid'], 
                        'First Name' =>  $value->getFirstname(),
                        'Last Name'  =>  $value->getLastname(),
                        'User Email' =>  $value->getEmail(),
                        'Category'   =>  $profName,
                        'User Type'  =>  $userType,                                    
                    );
                }
            }
        }
        
        
        if (empty($newArray)) {             
            exit();
        } 
        //fetch tha data from the database
                 
        // Write data to file
        
        $flag = false;
        
        $filename = 'Last_Login_User_Report_'.date('Y-m-d').'.xls'; // File Name
         
        // Download file
        header("Content-Type: application/xls");    
        header("Content-Disposition: attachment; filename=\"$filename\"");  
        header("Pragma: no-cache"); 
        header("Expires: 0");
        $k = 0;
        $count = count($newArray);            
        foreach ($newArray as $key => $value) {  
            if(!$flag) {
                // display field/column names as first row
                echo implode("\t", array_keys($value)) . "\r\n";
                $flag = true;
            }
            echo implode("\t", array_values($value)) . "\r\n";  
            $k++;
            if ($k >= $count) {
                exit();
            }
        }
    }elseif($type == 'all_emp_job') {
            $jobPostReport = new ReportController();            
            $enddate = (isset($_GET['enddate']) && $_GET['enddate'] != '') ? $_GET['enddate'] : date('Y-m-d'); 
            if (isset($_GET['startdate']) && $_GET['startdate'] != '') {                
                $startdate = $_GET['startdate'];
                $date = strtotime("+1 day", strtotime($enddate));
                $enddate = date('Y-m-d', $date);
                $allrecord = $jobPostReport->empJobReportAction($startdate,$enddate);
            }else{
                //$month = 'All_Month';
                $allrecord = $jobPostReport->empJobReportAction();
            }
            
            
            
            if (empty($allrecord)) {                 
                exit();
            } 
            //fetch tha data from the database
                     
            // Write data to file
            $newArray = '';
            $flag = false;
            foreach ($allrecord as $key => $value1) {
                foreach ($value1 as $key => $value) {
                    $newArray[] = array(
                        'User ID'           =>  $value['emp_id'],
                        'Name'              =>  $value['name'],
                        'Job Listed'        =>  $value['job_list'],
                        'Jobs accepted'     =>  $value['job_accepted'],
                        'Success rate (%)'   =>  $value['success_rate'],
                        'Cancellation rate (%)'   =>  $value['cancellation_rate'],
                        'Number of private job requests sent'=> $value['private_user_req'],
                    );
                }
            }
                
                //exit();
            $filename =  'Employer_Job_Status_Report_'.date('Y-m-d').'.xls'; // File Name
             
            // Download file
            header("Content-Type: application/xls");    
            header("Content-Disposition: attachment; filename=\"$filename\"");  
            header("Pragma: no-cache"); 
            header("Expires: 0");
            $k = 0;
            $count = count($newArray);            
            foreach ($newArray as $key => $value) {  
                if(!$flag) {
                    // display field/column names as first row
                    echo implode("\t", array_keys($value)) . "\r\n";
                    $flag = true;
                }
                echo implode("\t", array_values($value)) . "\r\n";  
                $k++;
                if ($k >= $count) {
                    exit();
                }
            }
            
        }elseif($type == 'single_emp_job') {
           $jobPostReport = new ReportController();
            if (isset($_GET['emp_year']) && $_GET['emp_year'] != '') {
                $year = $_GET['emp_year'];
                $allrecord = $jobPostReport->singleEmpJobRecordByYear($year);
            }else{
                $year = 'All_year';
                $allrecord = $jobPostReport->singleEmpJobRecordByYear(date('Y'));
            }
            
            if (empty($allrecord)) { 
                ?>
                    <script type="text/javascript">
                        window.location.href = "http:/ec2-18-163-113-25.ap-east-1.compute.amazonaws.com/admin/config/report/leave-user?user_record=1";
                    </script>  
                <?php
                exit();
            } 
            //fetch tha data from the database
                     
            // Write data to file
            $newArray = '';
            
            $flag = false;
            foreach ($allrecord['allRecord']['record'] as $key => $value) {
                $newArray[] = array(
                    'Month'          =>  $value['month'],
                    'Job Listed'     =>  $value['job_list'],
                    'Jobs accepted'  =>  $value['job_accepted'],
                    'Success rate (%)'   =>  $value['success_rate'],
                    'Cancellation rate (%)'   =>  $value['cancellation_rate'],
                    'Number of private job requests sent'=> $value['private_user_req'],
                );
                
            }
            
            $empName = str_replace(' ', '_', $allrecord['empName']);
            $filename =  'Employer_'.$empName.'_'.$year.'_Job_Report.xls'; // File Name

            
            // Download file
            header("Content-Type: application/xls");    
            header("Content-Disposition: attachment; filename=\"$filename\"");  
            header("Pragma: no-cache"); 
            header("Expires: 0");
            $k = 0;
            $count = count($newArray);            
            foreach ($newArray as $key => $value) {  
                if(!$flag) {
                    // display field/column names as first row
                    echo implode("\t", array_keys($value)) . "\r\n";
                    $flag = true;
                }
                echo implode("\t", array_values($value)) . "\r\n";  
                $k++;
                if ($k >= $count) {
                    exit();
                }
            }
            
        }elseif($type == 'all_fre_job') {
            $jobPostReport = new ReportController();
            if (isset($_GET['startdate']) && $_GET['startdate'] != '' && isset($_GET['enddate']) && $_GET['enddate'] != '') {
                
                $startdate = $_GET['startdate'];
                $date = strtotime("+1 day", strtotime($_GET['enddate']));
                $enddate = date('Y-m-d', $date);
                $allrecord = $jobPostReport->freJobReportAction($startdate,$enddate);
            }else{
                $month = 'All_Month';
                $allrecord = $jobPostReport->freJobReportAction();
            }
            
            

            if (empty($allrecord)) { 
                ?>
                    <script type="text/javascript">
                        window.location.href = "http:/ec2-18-163-113-25.ap-east-1.compute.amazonaws.com/admin/config/report/leave-user?user_record=1";
                    </script>  
                <?php
                exit();
            } 
            //fetch tha data from the database
                     
            // Write data to file
            $newArray = '';
            $flag = false;
            foreach ($allrecord as $key => $value1) {
                foreach ($value1 as $key => $value) {
                    $newArray[] = array(
                        'User ID'           =>  $value['fre_id'],
                        'Name'           =>  $value['name'],
                        'Job Applied'     =>  $value['job_applied'],
                        'Jobs accepted'  =>  $value['job_accepted'],
                        'Success rate (%)'   =>  $value['job_success_rate'],
                        'Cancellation rate (%)'   =>  $value['job_cancellation_rate'],
                        'Jobs frozen'   =>  $value['job_freeze'],
                        'Jobs frozen and accepted'   =>  $value['job_freeze_accepted'],
                        'Frozen Success rate (%)'   =>  $value['job_freeze_success_rate'],
                        'Number of private jobs added into system'=> $value['private_job'],
                    );
                }
            }
                
                //exit();
            $filename =  'Freelancer_Job_Status_Report_'.date('Y-m-d').'.xls'; // File Name
             
            // Download file
            header("Content-Type: application/xls");    
            header("Content-Disposition: attachment; filename=\"$filename\"");  
            header("Pragma: no-cache"); 
            header("Expires: 0");
            $k = 0;
            $count = count($newArray);            
            foreach ($newArray as $key => $value) {  
                if(!$flag) {
                    // display field/column names as first row
                    echo implode("\t", array_keys($value)) . "\r\n";
                    $flag = true;
                }
                echo implode("\t", array_values($value)) . "\r\n";  
                $k++;
                if ($k >= $count) {
                    exit();
                }
            }
            
        }elseif($type == 'single_fre_job') {
            
            if (isset($_GET['fre_year']) && $_GET['fre_year'] != '') {
                $year = $_GET['fre_year'];
            }else{
                $year = date('Y');
            }
            
            
            $jobPostReport = new ReportController();
            $allrecord = $jobPostReport->singleFreJobRecordByYear($year);
            
           

            if (empty($allrecord)) { 
                ?>
                    <script type="text/javascript">
                        window.location.href = "http:/ec2-18-163-113-25.ap-east-1.compute.amazonaws.com/admin/config/report/leave-user?user_record=1";
                    </script>  
                <?php
                exit();
            } 
            //fetch tha data from the database
                     
            // Write data to file
            $newArray = '';
            
            $flag = false;
            foreach ($allrecord['allRecord'] as $key => $value) {
                $newArray[] = array(
                    'Month'           =>  $value['month'],
                    'Job Applied'     =>  $value['job_applied'],
                    'Jobs accepted'  =>  $value['job_accepted'],
                    'Success rate (%)'   =>  $value['success_rate'],
                    'Cancellation rate (%)'   =>  $value['cancellation_rate'],
                    'Jobs frozen'   =>  $value['job_freeze'],
                    'Jobs frozen and accepted'   =>  $value['job_freeze_accepted'],
                    'Frozen Success rate (%)'   =>  $value['job_freeze_success_rate'],
                    'Number of private jobs added into system'=> $value['private_job'],
                );
                
            }
            
            $freName = str_replace(' ', '_', $allrecord['freName']);
            $filename =  'Freelancer_'.$freName.'_'.$year.'_Job_Report.xls'; // File Name

            
            // Download file
            header("Content-Type: application/xls");    
            header("Content-Disposition: attachment; filename=\"$filename\"");  
            header("Pragma: no-cache"); 
            header("Expires: 0");
            $k = 0;
            $count = count($newArray);            
            foreach ($newArray as $key => $value) {  
                if(!$flag) {
                    // display field/column names as first row
                    echo implode("\t", array_keys($value)) . "\r\n";
                    $flag = true;
                }
                echo implode("\t", array_values($value)) . "\r\n";  
                $k++;
                if ($k >= $count) {
                    exit();
                }
            }
            
        }elseif($type == 'pkg_income') {           
            
            $packageRateReport = new PackageRateReport();
            $pkg_year = $pkg_month = '';
            if (isset($_GET['pkg_year'])) {
                $year = $pkg_year = $_GET['pkg_year'];
            }
            if (isset($_GET['pkg_month'])) {
                $pkg_month = $_GET['pkg_month'];
            }
            if ($pkg_month == '' && $pkg_year != '') {
                $start_date = $pkg_year.'-01-01';
                $end_date   = $pkg_year.'-12-31';
                $package_rate_report = $packageRateReport->getPackageRates($start_date,$end_date);
                $year = $pkg_year;
                $month = 'All_Month';
            }elseif($pkg_month != '' && $pkg_year == ''){
                $start_date = date('Y-m-01', strtotime($pkg_month));
                $end_date   = date('Y-m-t', strtotime($pkg_month));
                $package_rate_report = $packageRateReport->getPackageRates($start_date,$end_date);
                $year = 'All_Year';
                $month = $pkg_month;
            }elseif($pkg_month != '' && $pkg_year != ''){
                $start_date = date('Y-m-01', strtotime($pkg_month.'-'.$pkg_year));
                $end_date   = date('Y-m-t', strtotime($pkg_month.'-'.$pkg_year));
                $package_rate_report = $packageRateReport->getPackageRates($start_date,$end_date);
                $year = $pkg_year;
                $month = $pkg_month;
            }else{
                $package_rate_report = $packageRateReport->getPackageRates();
                $year = 'All_Year';
                $month = 'All_Month';
            }

            if (empty($package_rate_report)) { 
                ?>
                    <script type="text/javascript">
                        window.location.href = "http:/ec2-18-163-113-25.ap-east-1.compute.amazonaws.com/admin/config/report/package-income-report?user_record=1";
                    </script>  
                <?php
                exit();
            } 
            //fetch tha data from the database
                     
            // Write data to file
            $newArray = '';
            $flag = false;
            $totalIncome = 0;
            foreach ($package_rate_report as $key => $value) {
                $i = 1;
                foreach ($value['details'] as $key => $v) {
                    $newArray[] = array(
                        'Package'           =>  ($i == 1) ? $value['name'] : '',
                        'Rate'              =>  $currency.''.number_format($v['rate'],2),
                        'Number of Users'    =>  $v['no_records'],
                        'Total Users'    =>  ($i == 1) ? $value['count'] : '',
                        'Income Expected'   =>  ($i == 1) ? $currency.''.number_format($value['total_rate'],2) : ''
                    );
                    $i++;
                }               

                $totalIncome += $value['total_rate'];
            }
            $newArray[] = array();
            $newArray[] = array(
                    'Package'      =>  'Total Income',
                    'Rate'     =>  $currency.''.number_format($totalIncome,2),
                ); 
            
            
            $filename =  $month.'_'.$year.'_Package_Income_Report.xls'; // File Name

            
            // Download file
            header("Content-Type: application/xls");    
            header("Content-Disposition: attachment; filename=\"$filename\"");  
            header("Pragma: no-cache"); 
            header("Expires: 0");
            $k = 0;
            $count = count($newArray);            
            foreach ($newArray as $key => $value) {  
                if(!$flag) {
                    // display field/column names as first row
                    echo implode("\t", array_keys($value)) . "\r\n";
                    $flag = true;
                }
                echo implode("\t", array_values($value)) . "\r\n";  
                $k++;
                if ($k >= $count) {
                    exit();
                }
            }
            
        }elseif($type == 'user_extra_info_export'){
            
                $userId = $_GET['uid'];
                $role = $_GET['user_acl_role_id'];
                $userExtraInfo = new UserExtraInfo();
                $extraInfo = $userExtraInfo->getUserExtraInfo($userId);
                
                $extraInfoArray = array();
                foreach ($extraInfo as $key => $value) {
                    if ($value->getGender() && $value->getGender() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Gender',
                            'Answer' => $value->getGender(),
                        );
                    }
                    /*if ($value->getDob() && $value->getDob() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Date Of Birth',
                            'Answer' => $value->getDob(),
                        );
                    }*/
                    if ($value->getMobile() && $value->getMobile() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Mobile Number',
                            'Answer' => $value->getMobile(),
                        );
                    }
                    if ($value->getTelephone() && $value->getTelephone() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Telephone Number',
                            'Answer' => $value->getTelephone(),
                        );
                    }
                    if ($value->getAocId() && $value->getAocId() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'AOC ID',
                            'Answer' => $value->getAocId(),
                        );
                    }
                    if ($value->getAddress() && $value->getAddress() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Address',
                            'Answer' => $value->getAddress(),
                        );
                    }
                    if ($value->getCity() && $value->getCity() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Region',
                            'Answer' => $value->getCity(),
                        );
                    }
                    if ($value->getZip() && $value->getZip() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Post Code',
                            'Answer' => $value->getZip(),
                        );
                    }
                    if ($value->getMaxDistance() && $value->getMaxDistance() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Maximum distance to traval',
                            'Answer' => $value->getMaxDistance(),
                        );
                    }
                    if ($value->getMinimumRate() && $value->getMinimumRate() != '') {
                        $minRate = unserialize($value->getMinimumRate());
                        $mRateStr = '';
                        foreach ($minRate as $key => $mRate) {
                            $mRateStr .= $key.':'.$mRate.', ';
                        }
                        if ($mRateStr && $mRateStr != '') {
                            $extraInfoArray[] = array(
                                'Question' => 'Minimum rate',
                                'Answer' => $mRateStr,
                            );
                        }
                        
                    }
                    if ($value->getCompany() && $value->getCompany() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'Company',
                            'Answer' => $value->getCompany(),
                        );
                    }
                    if ($value->getGoc() && $value->getGoc() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'GOC',
                            'Answer' => $value->getGoc(),
                        );
                    }
                    if ($value->getCet() && $value->getCet() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'CET',
                            'Answer' => $value->getCet(),
                        );
                    }
                    if ($value->getAop() && $value->getAop() != '') {
                        $extraInfoArray[] = array(
                            'Question' => 'AOP',
                            'Answer' => $value->getAop(),
                        );
                    }
                   
                   
                }

                $sqlString_data="select qu.fquestion as fq,qu.equestion as eq,qu.type_key as tk,qu.type_value as tv,qu.id as qid,ua.* from user_question qu, user_answer ua where ua.user_id='$userId' and ua.question_id=qu.id";  
                $results_get = $adapter->query($sqlString_data, $adapter::QUERY_MODE_EXECUTE);
                $result_data = $results_get->toArray();
                $answer_value = array();
                foreach($result_data as $resultset){
                    if($role==2){
                        if ($resultset['type_value'] && $resultset['type_value'] != '') {
                            $extraInfoArray[] = array(
                                'Question' => $resultset['fq'],
                                'Answer' => $resultset['type_value'],
                            );
                        }
                        
                    }else{
                         if ($resultset['type_value'] && $resultset['type_value'] != '') {
                            $extraInfoArray[] = array(
                                'Question' => $resultset['eq'],
                                'Answer' => $resultset['type_value'],
                            );
                        }
                    }
                }
                /*echo "<pre>";
                print_r($extraInfoArray);
                echo "</pre>";*/
                //exit();
                $filename =  'User_Info_'.date('Y-m-d').'.xls'; // File Name
                 
                // Download file
                header("Content-Type: application/xls");    
                header("Content-Disposition: attachment; filename=\"$filename\"");  
                header("Pragma: no-cache"); 
                header("Expires: 0");
                $flag = false;
                $k = 0;
                $count = count($extraInfoArray);            
                foreach ($extraInfoArray as $key => $value) {  
                    if(!$flag) {
                        // display field/column names as first row
                        echo implode("\t", array_keys($value)) . "\r\n";
                        $flag = true;
                    }
                    echo implode("\t", array_values($value)) . "\r\n";  
                    $k++;
                    if ($k >= $count) {
                        exit();
                    }
                }
            
        }elseif($type == 'privateUserRecords') {

            $jobPostReport = new ReportController();
            $allrecord = $jobPostReport->privateFreelancerReportAction();
            

            if (empty($allrecord['privateUserRecords'])) { 
                
                exit();
            } 
            //fetch tha data from the database
                     
            // Write data to file
            $newArray = '';
            $flag = false;
            
            foreach ($allrecord['privateUserRecords'] as $key => $privateUserRecords) {
                $userInfo = $userCollection->getUserById($privateUserRecords->getEmpId());
                foreach ($userInfo as $key => $userInfo) {
                    $eName = $userInfo->getName();
                    $eId = $userInfo->getId();
                    $professionId = $userInfo->getUserAclProfessionId();
                }
                if ($professionId != '') {
                    $profInfo = $userProfessional->getProfessionalById($professionId);
                    foreach ($profInfo as $key => $profInfo) {
                        $profName = $profInfo->getName();
                    }
                }
                $newArray[] = array(
                    'Name'  =>  $privateUserRecords->getPName(),
                    'Email'     =>  $privateUserRecords->getPEmail(),
                    'Employer Name'  =>  $eName != '' ? $eName : 'May be delete',
                    'Employer Id' =>  $eId != '' ? $eId : 'May be delete',
                    'Employer Profession' =>  $profName != '' ? $profName : 'May be delete',
                );

                
            }
            
            
            
            $filename =  date('d_m_Y').'_private_freelancer_report.xls'; // File Name

            
            // Download file
            header("Content-Type: application/xls");    
            header("Content-Disposition: attachment; filename=\"$filename\"");  
            header("Pragma: no-cache"); 
            header("Expires: 0");
            $k = 0;
            $count = count($newArray);            
            foreach ($newArray as $key => $value) {  
                if(!$flag) {
                    // display field/column names as first row
                    echo implode("\t", array_keys($value)) . "\r\n";
                    $flag = true;
                }
                echo implode("\t", array_values($value)) . "\r\n";  
                $k++;
                if ($k >= $count) {
                    exit();
                }
            }
            
        }elseif($type == 'privateStoreRecords') {

            $jobPostReport = new ReportController();
            $allrecord = $jobPostReport->privateStoreReportAction();
            

            if (empty($allrecord)) { 
                ?>
                    <script type="text/javascript">
                        window.location.href = "http:/ec2-18-163-113-25.ap-east-1.compute.amazonaws.com/admin/config/report/private-store-report?user_record=1";
                    </script>  
                <?php
                exit();
            } 
            //fetch tha data from the database
                     
            // Write data to file
            $newArray = '';
            $flag = false;
            
            foreach ($allrecord['privateStoreRecords'] as $key => $privateStoreRecords) {
                $userInfo = $userCollection->getUserById($privateStoreRecords->getFId());
                foreach ($userInfo as $key => $userInfo) {
                    $fName = $userInfo->getName();
                    $fId = $userInfo->getId();
                }
                
                $newArray[] = array(
                    'Freelancer name'  =>  $fName != '' ? $fName : 'May be delete',
                    'Freelancer Id'     =>  $fId != '' ? $fId : 'May be delete',
                    'Store name'  =>  $privateStoreRecords->getEmpName(),
                    'Location' =>  $privateStoreRecords->getPrivJobLocation(),
                    'Rate' =>  $currency.number_format($privateStoreRecords->getPrivJobRate(),2),
                    'Date' =>  $privateStoreRecords->getPrivJobStartDate(),
                );

                
            }
            
            
            
            $filename =  date('d_m_Y').'_private_store_report.xls'; // File Name

            
            // Download file
            header("Content-Type: application/xls");    
            header("Content-Disposition: attachment; filename=\"$filename\"");  
            header("Pragma: no-cache"); 
            header("Expires: 0");
            $k = 0;
            $count = count($newArray);            
            foreach ($newArray as $key => $value) {  
                if(!$flag) {
                    // display field/column names as first row
                    echo implode("\t", array_keys($value)) . "\r\n";
                    $flag = true;
                }
                echo implode("\t", array_values($value)) . "\r\n";  
                $k++;
                if ($k >= $count) {
                    exit();
                }
            }
            
        }
    
?>
