<?php
use GcFrontend\Controller\DbController as DbController;
use Zend\Db\Sql\Sql;
$dbConfig = new DbController();
$adapter = $dbConfig->locumkitDbConfig();
$sql = new Sql($adapter);
$update = $sql->update();
$select = $sql->select();

$select->from('user');

$statement = $sql->prepareStatementForSqlObject($select);
$results = $statement->execute();
$row = $results->current();
$name = $row['firstname']; // working

$request = $this->getRequest();
if($request->isPost())
{
    $post = $request->getPost(); 
    if ($post->get('password') == $post->get('password1')) {
        $password = sha1($post->get('password'));
        $get_email = sha1($post->get('get_email'));
        $get_uid = $post->get('get_uid');
        $answer_hash = $post->get('answer_hash');
        $answer = substr(sha1($post->get('answer')), 5, 10);
        
        $sqlString_get="select * from user where id='$get_uid'"; 
        $results0 = $adapter->query($sqlString_get, $adapter::QUERY_MODE_EXECUTE);
        $row111 = $results0->current(); //print_r($row111);
        $id = $row111['id'];
        $email = sha1($row111['email']);
        $email22 = $row111['email'];
        

        if(empty($get_email) || empty($id))
        {
            return array('password' => $password, 'error_message' => 'Incorrect Details.');
        }
        if($id!='')
        {
        $keyValues=array('updated_at'=>'NOW()','password'=>$password);
        $update = $sql->update();
        $update->table('user');
        $update->set( $keyValues );
        $update->where( array( 'email' => $email22 ) );
            $statement  = $sql->prepareStatementForSqlObject( $update );
            $results    = $statement->execute(); //print_r($results); die('STOP');
            $this->flashMessenger()->addSuccessMessage('Password reset successfully.');
            $this->redirect()->toUrl('/reset-password?reset=true');
            return TRUE;
        }
    }else{
        $this->flashMessenger()->addErrorMessage('Please recheck the password you enter.');
        $this->redirect()->toUrl('/reset-password');
    }
    
}