<?php
$start_date = $end_date = '';
if (isset($_GET['startdate']) && isset($_GET['enddate']) ){
    $start_date = $_GET['startdate'];
    $end_date = $_GET['enddate'];
}

$paginator = new \Zend\Paginator\Paginator(new \Zend\Paginator\Adapter\ArrayAdapter($this->allRecord));
$paginator->setItemCountPerPage(20);
$paginator->setCurrentPageNumber(empty($_GET['page']) ? 1 : (int)$_GET['page']);
?>
<form id="filter" action="" method="GET">
    <div class="row">        
        <div class="col-md-3">
            <input type="text"  name="startdate" id="datepicker1" placeholder="From date"  value="<?php echo $start_date; ?>">
        </div>
        <div class="col-md-3">
            <input type="text"  name="enddate" id="datepicker2" placeholder="To date" value="<?php echo $end_date; ?>">
        </div>       
        <div class="col-md-2">
            <input type="hidden"  name="type" value="all_fre_job">
            <input id="user_record" type="submit" value="export" style="margin-top: 0px; float:left;  border: 1px solid #0a9aca;  padding: 5px 10px;  text-decoration: none;  background: #00a9e0;  color: #fff;  font-size: 16px; margin-right: 10px; border-radius: 3px;">
            <?php  if (isset($_GET['startdate']) && isset($_GET['enddate']) && !isset($_GET['downloaded'])) { ?>
                <a href="<?php echo $this->serverUrl().'/admin/config/report/fre-job-report'; ?>"  style="  margin-top: 0px; float:left;  border: 1px solid #b5b3b3;  padding: 5px 10px;  text-decoration: none;  background: #ccc;  color: #000000;  font-size: 16px; border-radius: 3px;">Clear</a>
            <?php } ?>
        </div>
    </div>
</form>
<?php 
    
    if (isset($_GET['startdate']) && isset($_GET['enddate']) && !isset($_GET['downloaded'])) {
        echo '<iframe src="'.$this->serverUrl().'/report?startdate='.$_GET['startdate'].'&enddate='.$_GET['enddate'].'&type=all_fre_job&downloaded=1" style="display:none;"></iframe> ';
    }
?>
<hr/>

<table class="table clickable table-striped table-hover">
    <colgroup>
        <col width="7%">
        <col width="8%">
        <col width="9%">
        <col width="8%">
        <col width="9%">        
        <col width="9%">        
        <col width="9%">        
        <col width="8%">        
        <col width="10%">        
        <col width="10%">        
        <col width="10%">        
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->escapeHtml($this->translate('User ID')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Locum')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('Jobs Applied')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('Jobs accepted')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('Success rate')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('Cancel rate')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('Jobs frozen')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('frozen and accepted')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('Frozen Success rate')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('Private jobs added')); ?></th>
            <th style="text-align:center"><?php echo $this->escapeHtml($this->translate('Detailed reports')); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($paginator as $key => $value):  ?>
            <tr>
                <td><?php echo $this->escapeHtml($value['fre_id']); ?></td>
                <td><?php echo $this->escapeHtml($value['name']); ?></td>
                <td style="text-align:center"><?php echo $this->escapeHtml($value['job_applied']); ?></td>
                <td style="text-align:center"><?php echo $this->escapeHtml($value['job_accepted']); ?></td>
                <td style="text-align:center"><?php echo $this->escapeHtml($value['job_success_rate']); ?>%</td>
                <td style="text-align:center"><?php echo $this->escapeHtml($value['job_cancellation_rate']); ?>%</td>
                <td style="text-align:center"><?php echo $this->escapeHtml($value['job_freeze']); ?></td>
                <td style="text-align:center"><?php echo $this->escapeHtml($value['job_freeze_accepted']); ?></td>
                <td style="text-align:center"><?php echo $this->escapeHtml($value['job_freeze_success_rate']); ?>%</td>
                <td style="text-align:center"><?php echo $this->escapeHtml($value['private_job']); ?></td>
                <td><a href="/admin/config/report/fre-job-report/single-fre/<?php echo $value['fre_id']; ?>" ><span class="glyphicon glyphicon-eye-open" style="margin: 0 auto;    display: block; color:#00a9e0;    font-size: 14px;"></span></a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="pagination">
    <?php 
        if (isset($_GET['startdate']) && isset($_GET['enddate'])) {
            echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/report/fre-job-report?startdate='.$_GET['startdate'].'&enddate='.$_GET['enddate'].'&downloaded=0'));
        }else{
            echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/report/fre-job-report'));
        }
    ?>
</div>

</div>
        
 
<script>
    $(function() {
        $( "#datepicker1" ).datepicker({dateFormat: "yy-mm-dd",changeYear: true,});
        $( "#datepicker2" ).datepicker({dateFormat: "yy-mm-dd",changeYear: true,});
    });
</script>
<style type="text/css">
    #datepicker1,#datepicker2 {
        width: 100%;
        height: 35px;
        padding: 6px 10px;
        border-radius: 3px;
        border: 1px solid #ccc;
    }
    form#filter {
        background: #f0f0f0;
        padding: 10px 12px 8px;
        border-bottom: 1px solid;
    }
</style>