<?php
    $start_date = $end_date = '';
    if (isset($_GET['startdate']) && isset($_GET['enddate']) ){
        $start_date = $_GET['startdate'];
        $end_date = $_GET['enddate'];
    }


    $userCollection = new Gc\User\Lastlogin\Collection();
    $userData = new Gc\User\Collection();
    $userProfessional = new Gc\User\Professional\Collection();
    $paginator = new \Zend\Paginator\Paginator(new \Zend\Paginator\Adapter\ArrayAdapter($userCollection->getLastLoginUsers(true,$start_date,$end_date)));
    $paginator->setItemCountPerPage(30);
    $paginator->setCurrentPageNumber(empty($_GET['page']) ? 1 : (int)$_GET['page']);    
?>
    <form id="filter" action="" method="GET">
        <div class="row">
            <div class="col-md-3">
                <input type="text"  name="startdate" id="datepicker1" placeholder='Enter start date' value="<?php echo $start_date; ?>">
            </div>
            <div class="col-md-3">
                <input type="text"  name="enddate" id="datepicker2" placeholder='Enter end date' value="<?php echo $end_date; ?>">
            </div>
            <div class="col-md-2">
                <input type="hidden"  name="type" value="last_login_user">
                <?php if(empty($paginator)): ?><input type="hidden"  name="downloaded" value="0"> <?php endif; ?>
                <input id="user_record" type="submit" value="Export" style="  margin-top: 0px; float:left;  border: 1px solid #0a9aca;  padding: 5px 10px;  text-decoration: none;  background: #00a9e0;  color: #fff;  font-size: 16px; margin-right: 10px; border-radius: 3px;">
                <?php  if (isset($_GET['startdate']) && isset($_GET['enddate']) && !isset($_GET['downloaded'])) { ?>
                    <a href="<?php echo $this->serverUrl().'/admin/config/report/last-login-user'; ?>"  style="  margin-top: 0px; float:left;  border: 1px solid #b5b3b3;  padding: 5px 10px;  text-decoration: none;  background: #ccc;  color: #000000;  font-size: 16px; border-radius: 3px;">Clear</a>
                <?php } ?>
            </div>
        </div>    
    </form>
<?php    

    if (isset($_GET['user_record']) && $_GET['user_record']) {
       echo "<script>alert('No record were found.')</script>";
    }
    if (isset($_GET['startdate']) && isset($_GET['enddate']) && !isset($_GET['downloaded'])) {
        echo '<iframe src="'.$this->serverUrl().'/report?startdate='.$_GET['startdate'].'&enddate='.$_GET['enddate'].'&type=last_login_user&downloaded=1" style="display:none;"></iframe> ';
    }
?>
<hr style="clear:both" />
<table class="table clickable table-striped table-hover">
    <colgroup>
        <col width="10%">        
        <col width="15%">
        <col width="15%">
        <col width="20%">
        <col width="10%">
        <col width="10%">        
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->escapeHtml($this->translate('User ID')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Last Login Date')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Email')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Category')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('User Type')); ?></th>
            <!--<th><?php echo $this->escapeHtml($this->translate('IP Address')); ?></th>-->
            
        </tr>
    </thead>
    <tbody>
        <?php 
            if($paginator->count() > 0): 
            foreach ($paginator as $lastloginusers): 
            
            $userPresonalData = $userData->getUserById($lastloginusers->getUid());
            if (!empty($userPresonalData)) {
            /*echo "<pre>";
            print_r($userPresonalData);
            echo "</pre>";*/
        ?>
            <tr>
                <td><?php echo $this->escapeHtml($lastloginusers->getUid()); ?></td>
                <?php ?>
                <td><?php echo date('d-m-Y', strtotime($lastloginusers->getLoginAt())); ?></td>
                <?php foreach ($userPresonalData as $key => $value) {
                    ?>
                    <td><?php echo $this->escapeHtml($value->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($value->getEmail()); ?></td>
                    <?php 
                        if ($value->getUserAclProfessionId() != '') {
                            $profInfo = $userProfessional->getProfessionalById($value->getUserAclProfessionId());
                            foreach ($profInfo as $key => $profInfo) {
                                $profName = $profInfo->getName();
                            }
                        }
                    ?>
                    <td><?php echo $this->escapeHtml($profName); ?></td>
                    <?php 
                        if($value->getUserAclRoleId() == 2){
                            $userType = 'Locum';
                        }elseif ($value->getUserAclRoleId() == 3) {
                            $userType = 'Employer';
                        } 
                    ?>
                    <td><?php echo $this->escapeHtml($userType); ?></td>
                <?php } ?>
                <!--<td><?php echo $this->escapeHtml($lastloginusers->getIpAddress()); ?></td>-->
                               
            </tr>
        <?php } endforeach; else: ?>
            <tr><td colspan="6" style="text-align:center">No records were found.</td></tr>
        <?php endif; ?>
    </tbody>
</table>
<div class="pagination">
     <?php echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/report/last-login-user'));?>
</div>

 
<script type="text/javascript">
    Gc.initTableList();
</script>

<script>
    $(function() {
        $( "#datepicker1" ).datepicker({dateFormat: "yy-mm-dd"});
        $( "#datepicker2" ).datepicker({dateFormat: "yy-mm-dd"});
    });   
</script>
<style type="text/css">
    input[type="text"] {
        width: 100%;
        height: 35px;
        padding: 6px 10px;
        border-radius: 3px;
        border: 1px solid #ccc;
    }
    form#filter {
        background: #f0f0f0;
        padding: 10px 12px 8px;
        border-bottom: 1px solid;
    }
</style>
