<?php
$start_date = $end_date = '';
if (isset($_GET['startdate']) && isset($_GET['enddate']) ){
    $start_date = $_GET['startdate'];
    $end_date = $_GET['enddate'];
}
$userCollection = new Gc\User\Collection();
$paginator = new \Zend\Paginator\Paginator(new \Zend\Paginator\Adapter\ArrayAdapter($this->leaveUsers));
$paginator->setItemCountPerPage(20);
$paginator->setCurrentPageNumber(empty($_GET['page']) ? 1 : (int)$_GET['page']);
?>
<form id="filter" action="" method="GET">
    <div class="row">
        <div class="col-md-3"> 
            <input type="text"  name="startdate" id="datepicker1" placeholder='Enter start date' value="<?php echo $start_date; ?>">
        </div>
        <div class="col-md-3">
            <input type="text"  name="enddate" id="datepicker2" placeholder='Enter end date' value="<?php echo $end_date; ?>">
        </div>
        <div class="col-md-2">
            <input type="hidden"  name="type" value="Leave_User">
            <input id="user_record" type="submit" value="export" style="margin-top: 0px; float:left;  border: 1px solid #0a9aca;  padding: 5px 10px;  text-decoration: none;  background: #00a9e0;  color: #fff;  font-size: 16px; margin-right: 10px; border-radius: 3px;">
            <?php  if (isset($_GET['startdate']) && isset($_GET['enddate']) && !isset($_GET['downloaded'])) { ?>
                <a href="<?php echo $this->serverUrl().'/admin/config/report/leave-user'; ?>"  style="  margin-top: 0px; float:left;  border: 1px solid #b5b3b3;  padding: 5px 10px;  text-decoration: none;  background: #ccc;  color: #000000;  font-size: 16px; border-radius: 3px;">Clear</a>
            <?php } ?>
        </div>
    </div>
</form>
<?php 
    if (isset($_GET['user_record']) && $_GET['user_record']) {
       echo "<script>alert('No record were found.')</script>";
    }
    if (isset($_GET['startdate']) && isset($_GET['enddate']) && !isset($_GET['downloaded'])) {
        echo '<iframe src="'.$this->serverUrl().'/report?startdate='.$_GET['startdate'].'&enddate='.$_GET['enddate'].'&type=Leave_User&downloaded=1" style="display:none;"></iframe> ';
    }
?>
<hr/>
<table class="table clickable table-striped table-hover">
    <colgroup>
        <col width="10%">
        <col width="15%">        
        <col width="20%">
        <col width="20%">
        <col width="35%">
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->escapeHtml($this->translate('User ID')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Leave Date')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Email')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Reason of leaving')); ?></th>
            
        </tr>
    </thead>
    <tbody>
        <?php if($paginator->count() > 0): foreach ($paginator as $leaveuser): ?>
            <tr>
                <td><?php echo $this->escapeHtml($leaveuser->getUid()); ?></td>
                <td><?php echo date('d-m-Y', strtotime($leaveuser->getCreatedAt())); ?></td>
                <td><?php echo $this->escapeHtml($leaveuser->getUserName()); ?></td>
                <td><?php echo $this->escapeHtml($leaveuser->getUserEmail()); ?></td>
                <td><?php                         
                        $reasons = unserialize($leaveuser->getUserReasonToLeave());
                        if (is_array($reasons)) {
                            $i = 1;
                            foreach ($reasons as $key => $value) {
                                echo  $i.'.  '.$this->escapeHtml($value).'<br/>'; 
                                $i++;
                            }
                        }else{
                            echo $leaveuser->getUserReasonToLeave();
                        }
                        
                    ?></td>                
            </tr>
        <?php endforeach; else: ?>
                <tr><td colspan="5" style="text-align:center">No record found</td></tr>
        <?php endif; ?>
    </tbody>
</table>
<div class="pagination">
    <?php 
        if (isset($_GET['startdate']) && isset($_GET['enddate'])) {
            echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/report/leave-user?startdate='.$_GET['startdate'].'&enddate='.$_GET['enddate'].'&downloaded=0'));
        }else{
            echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/report/leave-user'));
        }
    ?>
</div>

 
<script type="text/javascript">
    Gc.initTableList();
</script>
<style type="text/css">
    input[type="date"] {
        width: 100%;
        height: 35px;
        padding: 6px 10px;
        border-radius: 3px;
        border: 1px solid #ccc;
    }
</style>
<script>
    $(function() {
        $( "#datepicker1" ).datepicker({dateFormat: "yy-mm-dd"});
        $( "#datepicker2" ).datepicker({dateFormat: "yy-mm-dd"});
    });
</script>
<style type="text/css">
    input[type="text"] {
        width: 100%;
        height: 35px;
        padding: 6px 10px;
        border-radius: 3px;
        border: 1px solid #ccc;
    }
    form#filter {
        background: #f0f0f0;
        padding: 10px 12px 8px;
        border-bottom: 1px solid;
    }
</style>
