<?php
$package_id = 1;
if (isset($_GET['pkg'])){
    $package_id = $_GET['pkg'];
}


use GcFrontend\Controller\DbController as DbController;
use Gc\User\Package\Collection as PackageCollection;
use GcConfig\Controller\ReportController as ReportController;
$reportController   = new ReportController();
$userCollection     = new Gc\User\Collection();
$userProfessional   = new Gc\User\Professional\Collection();
$dbConfig           = new DbController();
$adapter            = $dbConfig->locumkitDbConfig();

$paginator = new \Zend\Paginator\Paginator(new \Zend\Paginator\Adapter\ArrayAdapter($userCollection->getFreelancerUsersByPkgId($package_id)));
$paginator->setItemCountPerPage(20);
$paginator->setCurrentPageNumber(empty($_GET['page']) ? 1 : (int)$_GET['page']);

?>
<form id="filter" action="" method="GET">
    <div class="row">
        <div class="col-md-3">
            <select name="pkg" id="pkg_option">                
                <?php 
                    $packageCollection = new PackageCollection();
                    $packagesList      = $packageCollection->getPackages();
                    foreach ($packagesList as $packagesModel) {?>
                    <option value="<?php echo $packagesModel->getId(); ?>" <?php echo ($package_id == $packagesModel->getId() ) ? 'Selected' : ''; ?>><?php echo $packagesModel->getName(); ?></option>
                    <?php }
                ?>
            </select>
        </div>  

        <div class="col-md-2">
            <input type="hidden"  name="downloaded" value="1">
            <input type="hidden"  name="type" value="Package_User">
            <input id="user_record" type="submit" value="Export" style="margin-top: 0px; float:left;  border: 1px solid #0a9aca;  padding: 5px 10px;  text-decoration: none;  background: #00a9e0;  color: #fff;  font-size: 16px; margin-right: 10px; border-radius: 3px;">
            <?php  if (isset($_GET['package_name']) && !isset($_GET['downloaded'])) { ?>
                <a href="<?php echo $this->serverUrl().'/admin/config/report/package-report'; ?>"  style="  margin-top: 0px; float:left;  border: 1px solid #b5b3b3;  padding: 5px 10px;  text-decoration: none;  background: #ccc;  color: #000000;  font-size: 16px; border-radius: 3px;">Clear</a>
            <?php } ?>
        </div>
    </div>
</form>
<?php 
    if (isset($_GET['user_record']) && $_GET['user_record']) {
       echo "<script>alert('No record were found.')</script>";
    }

    if (isset($package_id) && isset($_GET['downloaded']) && $_GET['downloaded'] == 1) {
        echo '<iframe src="'.$this->serverUrl().'/report?pkg='.$package_id.'&type=Package_User&downloaded=1" style="display:none;"></iframe> ';
    }
?>
<hr/>

<div id="tabs">
    <div class="qus-tabs">
        <ul>
            <?php foreach ($packagesList as $packagesModel){ ?>
                <li class="<?php echo ($package_id == $packagesModel->getId() ) ? 'active' : '';?>"><a href="<?php echo $this->serverUrl() ?>/admin/config/report/package-report?pkg=<?php echo $packagesModel->getId(); ?>&downloaded=0"><?php echo $packagesModel->getName(); ?></a></li>
            <?php } ?>
        </ul>
    </div>
   
    <div id="emp-tab">
        <table class="table clickable table-striped table-hover">
            <colgroup>
                <col width="8%">
                <col width="10%">
                <col width="15%">
                <col width="15%">
                <col width="15%">        
                <col width="12%">        
                <col width="12%">        
                <col width="13%">        
            </colgroup>
            <thead>
                <tr>             
                    <th><?php echo $this->escapeHtml($this->translate('User ID')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('Package')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('First Name')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('Last Name')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('Email')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('Category')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('User Type')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('Activation Date')); ?></th>
                </tr>
            </thead>
            <tbody>

                <?php 
                    if($paginator->count() > 0):
                    foreach ($paginator as $user): 
                        $activationDateArray = $reportController->getPkgActivationDateFre($user->getId(),$adapter);
                ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($user->getId()); ?></td>
                        <?php 
                            foreach ($packagesList as $packagesModel) {
                                if ($packagesModel->getId() == $user->getUserAclPackageId()) { ?>
                                   <td><?php echo $this->escapeHtml($packagesModel->getName()); ?> </td>
                        <?php   }
                            }
                        ?>   
                        <td><?php echo $this->escapeHtml($user->getFirstname()); ?></td>
                        <td><?php echo $this->escapeHtml($user->getLastname()); ?></td>
                        <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
                        <?php 
                            if ($user->getUserAclProfessionId() != '') {
                                $profInfo = $userProfessional->getProfessionalById($user->getUserAclProfessionId());
                                foreach ($profInfo as $key => $profInfo) {
                                    $profName = $profInfo->getName();
                                }
                            }
                        ?>
                        <td><?php echo $this->escapeHtml($profName); ?></td>
                        <?php 
                            if($user->getUserAclRoleId() == 2){
                                $userType = 'Freelancer';
                            }elseif ($user->getUserAclRoleId() == 3) {
                                $userType = 'Employer';
                            } 
                        ?>
                        <td><?php echo $this->escapeHtml($userType); ?></td>
                        <td><?php echo $activationDateArray['package_active_date'] != '' ? $this->escapeHtml($activationDateArray['package_active_date']) : '<span style="color:red">Expired</span>'; ?></td>
                    </tr>                                         
                <?php  endforeach; else: ?>
                    <tr><td colspan="8" style="text-align:center;">No record found.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>
        <div class="pagination">
             <?php echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/report/package-report?pkg='.$package_id));?>
        </div>        
    </div>
    

    <?php /*if($pkg == 'silver'){ ?>
        <div id="fre-tab">
            <table class="table clickable table-striped table-hover">
                <colgroup>
                    <col width="8%">
                    <col width="10%">
                    <col width="15%">
                    <col width="15%">
                    <col width="15%">        
                    <col width="12%">        
                    <col width="12%">        
                    <col width="13%">            
                </colgroup>
                <thead>
                    <tr>
                        <th><?php echo $this->escapeHtml($this->translate('User ID')); ?></th>  
                        <th><?php echo $this->escapeHtml($this->translate('Package')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('First Name')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('Last Name')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('Email')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('Category')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('User Type')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('Activation Date')); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php                         
                        foreach ($allUserByPkg as $user):                             
                            if ($user->getUserAclPackageId() == 2) {
                            $activationDateArray = $reportController->getPkgActivationDateFre($user->getId(),$adapter);
                    ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($user->getId()); ?></td>
                            <?php 
                                foreach ($packagesList as $packagesModel) {
                                    if ($packagesModel->getId() == $user->getUserAclPackageId()) { ?>
                                       <td><?php echo $this->escapeHtml($packagesModel->getName()); ?> </td>
                            <?php   }
                                } 
                            ?>                
                            <td><?php echo $this->escapeHtml($user->getFirstname()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getLastname()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
                            <?php 
                                if ($user->getUserAclProfessionId() != '') {
                                    $profInfo = $userProfessional->getProfessionalById($user->getUserAclProfessionId());
                                    foreach ($profInfo as $key => $profInfo) {
                                        $profName = $profInfo->getName();
                                    }
                                }
                            ?>
                            <td><?php echo $this->escapeHtml($profName); ?></td>
                            <?php 
                                if($user->getUserAclRoleId() == 2){
                                    $userType = 'Freelancer';
                                }elseif ($user->getUserAclRoleId() == 3) {
                                    $userType = 'Employer';
                                } 
                            ?>
                            <td><?php echo $this->escapeHtml($userType); ?></td>
                            <td><?php echo $this->escapeHtml($activationDateArray['package_active_date']); ?></td>                            
                        </tr>

                    <?php } endforeach; ?>

                </tbody>
            </table>
            <div class="pagination">
                 <?php //echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/report/package-report'));?>
            </div>
            <script type="text/javascript">
                $("#pkg_option").val(2);
            </script>
        </div>
    <?php }elseif($pkg == 'bronze'){ ?>
        <div id="fre-tab">
            <table class="table clickable table-striped table-hover">
                <colgroup>
                    <col width="8%">
                    <col width="10%">
                    <col width="15%">
                    <col width="15%">
                    <col width="15%">        
                    <col width="12%">        
                    <col width="12%">        
                    <col width="13%">        
                </colgroup>
                <thead>
                    <tr>
                        <th><?php echo $this->escapeHtml($this->translate('User ID')); ?></th> 
                        <th><?php echo $this->escapeHtml($this->translate('Package')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('First Name')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('Last Name')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('Email')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('Category')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('User Type')); ?></th>
                        <th><?php echo $this->escapeHtml($this->translate('Activation Date')); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                        foreach ($allUserByPkg as $user):                            
                            if ($user->getUserAclPackageId() == 3) {
                            $activationDateArray = $reportController->getPkgActivationDateFre($user->getId(),$adapter); 
                    ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($user->getId()); ?></td>
                            <?php 
                                foreach ($packagesList as $packagesModel) {
                                    if ($packagesModel->getId() == $user->getUserAclPackageId()) { ?>
                                       <td><?php echo $this->escapeHtml($packagesModel->getName()); ?></td>
                            <?php   }
                                }
                            ?>                
                            <td><?php echo $this->escapeHtml($user->getFirstname()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getLastname()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
                            <?php 
                                if ($user->getUserAclProfessionId() != '') {
                                    $profInfo = $userProfessional->getProfessionalById($user->getUserAclProfessionId());
                                    foreach ($profInfo as $key => $profInfo) {
                                        $profName = $profInfo->getName();
                                    }
                                }
                            ?>
                            <td><?php echo $this->escapeHtml($profName); ?></td>
                            <?php 
                                if($user->getUserAclRoleId() == 2){
                                    $userType = 'Freelancer';
                                }elseif ($user->getUserAclRoleId() == 3) {
                                    $userType = 'Employer';
                                } 
                            ?>
                            <td><?php echo $this->escapeHtml($userType); ?></td>
                            <td><?php echo $this->escapeHtml($activationDateArray['package_active_date']); ?></td>
                        </tr>
                    <?php } endforeach; ?>
                </tbody>
            </table>
            <div class="pagination">
                 <?php //echo $this->paginationControl($paginator, 'sliding', 'paginator', array('path' => $this->serverUrl().'/admin/config/report/package-report'));?>
            </div>
            <script type="text/javascript">
                $("#pkg_option").val(3);
            </script>
        </div>
    <?php }*/ ?>
 
<script type="text/javascript">
    Gc.initTableList();
</script>
<style type="text/css">
    select {
        width: 100%;
        height: 35px;
        padding: 6px 10px;
        border-radius: 3px;
        border: 1px solid #ccc;
    }
    form#filter {
        background: #f0f0f0;
        padding: 10px 12px 8px;
        border-bottom: 1px solid;
    }
</style>

